### ISSUE TITLE
LACP Op YML: Insufficient information gathered

### ISSUE THREAD

**Issue by amitmi704** [Juniper/py-junos-eznc#1002]
The "lacp.yml" file does not parse the "get-lacp-interface-information" output for the name of the AE, or the name of the participating ports.

**Comment by rahkumar651991** [comment]
@amitmi704  - Table-views end output may differ based on user requirements. 
User may have to make minor changes to get results specific to their needs. 
Here is a link to documentation for further help in this regard - https://www.juniper.net/documentation/en_US/junos-pyez/topics/concept/junos-pyez-tables-and-views-overview.html 

As you have already made respective changes which fulfils your requirement, closing the issue. You may re-open or open a new issue if something still prevails.
