### ISSUE TITLE
PyEZ overwirtes host with hostname 

### ISSUE THREAD

**Issue by a-v-popov** [Juniper/py-junos-eznc#1006]
If we have config like this
```
Host mx480
  HostName 192.168.100.22
  ProxyCommand ssh -W %h:%p -q lab
```
PyEZ will overwrite Host with Hostname here:
https://github.com/Juniper/py-junos-eznc/blob/6f02b26cdca98f9153ac3c83d98882b872477f23/lib/jnpr/junos/device.py#L431
It is then passed to ncclient as host. As result ncclient will be trying to get config for wrong Host and fail to get ProxyCommand.

_Originally posted by @a-v-popov in https://github.com/Juniper/py-junos-eznc/issues/153#issuecomment-601967611_

**Comment by vnitinv** [comment]
@a-v-popov Alex, please check if anything extra need to be done to fix this issue in https://github.com/Juniper/py-junos-eznc/pull/1007
