### ISSUE TITLE
error when importing jnpr.junos

### ISSUE THREAD

**Issue by CodeTechies** [Juniper/py-junos-eznc#1015]
>>> import jnpr.junos
Traceback (most recent call last):
  File "C:\Python38-32\lib\site-packages\ntc_templates\parse.py", line 5, in <module>
    from textfsm import clitable
  File "C:\Python38-32\lib\site-packages\textfsm\clitable.py", line 41, in <module>
    from textfsm import texttable
  File "C:\Python38-32\lib\site-packages\textfsm\texttable.py", line 42, in <module>
    from textfsm import terminal
  File "C:\Python38-32\lib\site-packages\textfsm\terminal.py", line 25, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python38-32\lib\site-packages\jnpr\junos\__init__.py", line 3, in <module>
    from jnpr.junos.factory.to_json import PyEzJSONEncoder
  File "C:\Python38-32\lib\site-packages\jnpr\junos\factory\__init__.py", line 4, in <module>
    from jnpr.junos.factory.factory_loader import FactoryLoader
  File "C:\Python38-32\lib\site-packages\jnpr\junos\factory\factory_loader.py", line 14, in <module>
    from jnpr.junos.factory.factory_cls import *
  File "C:\Python38-32\lib\site-packages\jnpr\junos\factory\factory_cls.py", line 7, in <module>
    from jnpr.junos.factory.cmdtable import CMDTable
  File "C:\Python38-32\lib\site-packages\jnpr\junos\factory\cmdtable.py", line 18, in <module>
    from ntc_templates import parse as ntc_parse
  File "C:\Python38-32\lib\site-packages\ntc_templates\parse.py", line 7, in <module>
    import clitable
ModuleNotFoundError: No module named 'clitable'

**Comment by vnitinv** [comment]
@CodeTechies Share the o/p of `pip list`

**Comment by CodeTechies** [comment]
c:\Python38-32>pip list
Package               Version
--------------------- -------
appdirs               1.4.3
astroid               2.3.3
bcrypt                3.1.7
cffi                  1.14.0
colorama              0.4.3
cryptography          2.9
distlib               0.3.0
filelock              3.0.12
future                0.18.2
importlib             1.0.4
isort                 4.3.21
Jinja2                2.11.1
junos-eznc            2.4.0
lazy-object-proxy     1.4.3
lxml                  4.5.0
MarkupSafe            1.1.1
mccabe                0.6.1
ncclient              0.6.7
netaddr               0.7.19
ntc-templates         1.4.0
paramiko              2.7.1
pip                   19.2.3
pycparser             2.20
pylint                2.4.4
PyNaCl                1.3.0
pyparsing             2.4.7
pyserial              3.4
PyYAML                5.3.1
scp                   0.13.2
setuptools            41.2.0
six                   1.14.0
terminal              0.4.0
textfsm               1.1.0
transitions           0.8.1
virtualenv            20.0.16
wrapt                 1.11.2
yamlordereddictloader 0.4.0
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

c:\Python38-32>pip freeze
appdirs==1.4.3
astroid==2.3.3
bcrypt==3.1.7
cffi==1.14.0
colorama==0.4.3
cryptography==2.9
distlib==0.3.0
filelock==3.0.12
future==0.18.2
importlib==1.0.4
isort==4.3.21
Jinja2==2.11.1
junos-eznc==2.4.0
lazy-object-proxy==1.4.3
lxml==4.5.0
MarkupSafe==1.1.1
mccabe==0.6.1
ncclient==0.6.7
netaddr==0.7.19
ntc-templates==1.4.0
paramiko==2.7.1
pycparser==2.20
pylint==2.4.4
PyNaCl==1.3.0
pyparsing==2.4.7
pyserial==3.4
PyYAML==5.3.1
scp==0.13.2
six==1.14.0
terminal==0.4.0
textfsm==1.1.0
transitions==0.8.1
virtualenv==20.0.16
wrapt==1.11.2
yamlordereddictloader==0.4.0

c:\Python38-32>

**Comment by ntwrkguru** [comment]
These seem to be other imports failing, not pyez. Open IDLE and try a plain import of `jnpr.junos`, pasting the output. The first error was:

> import fcntl
   ModuleNotFoundError: No module named 'fcntl'

The second error was:

> import clitable
   ModuleNotFoundError: No module named 'clitable'

**Comment by CodeTechies** [comment]
Thanks solve by removing the textfsm and install the pip install textfsm==0.4.1

**Comment by ntwrkguru** [comment]
"The fcntl module is not available on Windows. The functionality it exposes does not exist on that platform." From [SO](https://stackoverflow.com/questions/45228395/error-no-module-named-fcntl).

@vnitinv May need to work around this with a try during the load, but since it's loaded with `ntc-templates`, that may not be trivial. Must we depend on ntc-templates just to get TextFSM?

**Comment by vnitinv** [comment]
textfsm already has this fix but in github. I asked the owner to release it to PyPI. Let's see if he responds back

https://github.com/google/textfsm/issues/78

**Comment by vnitinv** [comment]
fixed via https://github.com/Juniper/py-junos-eznc/pull/1019

**Comment by ktbyers** [comment]
FYI, a new TextFSM release is not sufficient, TextFSM also needs to incorporate this PR:

https://github.com/google/textfsm/pull/82

FYI, @vnitinv
