### ISSUE TITLE
when ssh_private_key_file is specified that has passphrase, and none specified, incorrect exception raised

### ISSUE THREAD

**Issue by ipmonk** [Juniper/py-junos-eznc#1017]
user@ubuntu-16-04-4-server-amd64:~$ python3
Python 3.5.2 (default, Oct  8 2019, 13:06:37)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from jnpr.junos import Device
>>> from jnpr.junos.utils.start_shell import StartShell

//  pass in a private RSA key with passphrase and passwd as None

>>> dev = Device(host="8.8.8.8", ssh_private_key_file="id_rsa", passwd="None")
>>> ss = StartShell(dev)
>>> ss.open()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.5/site-packages/jnpr/junos/utils/start_shell.py", line 87, in open
    self._client = open_ssh_client(dev=self._nc)
  File "/home/user/.local/lib/python3.5/site-packages/jnpr/junos/utils/ssh_client.py", line 44, in open_ssh_client
    sock=sock, **kwargs
  File "/home/user/.local/lib/python3.5/site-packages/paramiko/client.py", line 446, in connect
    passphrase,
  File "/home/user/.local/lib/python3.5/site-packages/paramiko/client.py", line 764, in _auth
    raise saved_exception
  File "/home/user/.local/lib/python3.5/site-packages/paramiko/client.py", line 751, in _auth
    self._transport.auth_password(username, password)
  File "/home/user/.local/lib/python3.5/site-packages/paramiko/transport.py", line 1509, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "/home/user/.local/lib/python3.5/site-packages/paramiko/auth_handler.py", line 250, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

// this should raise PasswordRequiredException according to Paramiko docs.

**Comment by vnitinv** [comment]
```python
dev = Device(host="8.8.8.8", ssh_private_key_file="id_rsa", passwd="None")
```

Can you try changing `passwd` to `None` and not `"None"`

**Comment by ipmonk** [comment]
Thanks Nitin, rookie mistake in the submission. The documentation link is: https://docs.paramiko.org/en/stable/api/agent.html exception is raised by from_private_key() and from_private_key_file(). 

I discovered that the bug as described is in paramiko. 
We hit this code path in _read_private_key_pem():

> 
        # if no password was passed in,
        # raise an exception pointing out that we need one
        if password is None:
            raise PasswordRequiredException("Private key file is encrypted")

As the exception is raised, it gets caught by this try: except: block in _auth from client.py:

> 

             for key_filename in key_filenames:
                for pkey_class in (RSAKey, DSSKey, ECDSAKey, Ed25519Key):
                    try:
                        key = self._key_from_filepath(
                            key_filename, pkey_class, passphrase
                        )
                        allowed_types = set(
                            self._transport.auth_publickey(username, key)
                        )
                        two_factor = allowed_types & two_factor_types
                        if not two_factor:
                            return
                        break
                    except SSHException as e:
                        saved_exception = e

                        
The loop doesn't stop at this point, carries on processing the other key types until another exception is hit which overwrites PasswordRequiredException, this newer one is raised instead resulting in a nonsensical error. This should be improved, I'll raise a issue with paramiko.
