### ISSUE TITLE
circular dependency with napalm

### ISSUE THREAD

**Issue by ntwrkguru** [Juniper/py-junos-eznc#1018]
When installing 2.4.0, napalm throws an error:

```text
ERROR: napalm 2.5.0 has requirement junos-eznc==2.2.1, but you'll have junos-eznc 2.4.0 which is incompatible.
```

Not sure why we're including napalm now, but we should probably pressure the napalm folks to update their requirements to perhaps be >=2.2.1?

**Comment by ntwrkguru** [comment]
This appears to be resolved in [master](https://github.com/napalm-automation/napalm/blob/develop/requirements.txt), but not yet released.

**Comment by vnitinv** [comment]
@ntwrkguru We dont install NAPALM. You must be having that module already installed. Hence `pip` is complaining about NAPALM mismatch for PyEZ

**Comment by ntwrkguru** [comment]
It's a dependency of ntc-templates.

**Comment by vnitinv** [comment]
@ntwrkguru we can check with NAPALM when they are releasing new version

**Comment by ntwrkguru** [comment]
So, NAPALM has a dependency on PyEZ, but in 2.5, they changed from >= to ==. This is fixed in master, so should be all good now.
