### ISSUE TITLE
dev.rpc.get_config(options={'format':'set'}) return xml output

### ISSUE THREAD

**Issue by CodeTechies** [Juniper/py-junos-eznc#1023]
full_config_set = dev.rpc.get_config(options={'format':'set'})
result_set=etree.tostring(full_config_set, encoding='unicode', pretty_print=True)

**sample oututput:**
<configuration changed-seconds="1587285337" changed-localtime="2020-04-19 08:35:37 UTC">
  <version>14.1R1.10</version>
  <system>
    <host-name>R1</host-name>
    <root-authentication>
      <encrypted-password>$1$wzba3NOW$n.NtL/8/JDVunJWwmMPZT0</encrypted-password>
    </root-authentication>
    <name-server>
      <name>208.67.222.222</name>
    </name-server>
    <name-server>
      <name>208.67.220.220</name>
    </name-server>
    <login>
      <user>

$ python --version
Python 3.8.2
(venv)

$ pip freeze
asgiref==3.2.7
bcrypt==3.1.7
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
colorama==0.4.3
cryptography==2.9
Django==3.0.5
djangorestframework==3.11.0
future==0.18.2
get==2019.4.13
idna==2.9
Jinja2==2.11.1
junos-eznc==2.4.0
lxml==4.5.0
MarkupSafe==1.1.1
ncclient==0.6.7
netaddr==0.7.19
ntc-templates==1.4.0
paramiko==2.7.1
post==2019.4.13
public==2019.4.13
pycparser==2.20
PyNaCl==1.3.0
pyparsing==2.4.7
pyserial==3.4
pytz==2019.3
PyYAML==5.3.1
query-string==2019.4.13
request==2019.4.13
requests==2.23.0
scp==0.13.2
six==1.14.0
sqlparse==0.3.1
terminal==0.4.0
textfsm==0.4.1
transitions==0.8.1
urllib3==1.25.8
yamlordereddictloader==0.4.0

**Comment by vnitinv** [comment]
@CodeTechies Can you add this logging line in your script and share log too understand what rpc was fired and the corresponding response from device.
```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by vnitinv** [comment]
get config RPC support for `set` format was included only from 15.x Junos. Hence the issue.

**Comment by CodeTechies** [comment]
noted the vmx is in 14.1
