### ISSUE TITLE
Pushing simple config changes to Junos switch using pyez

### ISSUE THREAD

**Issue by Birajan2019** [Juniper/py-junos-eznc#1024]
Hi Guys,

I am looking for a simple program to perform similar configuration changes to nearly 10 switches.

The command should look something like this:

- Log into 10 switches, using the IP address, username and password through ssh
- Perform a rollback 0
- Configure multiple domain name and DNS server
- Issue a commit
- Print the output of the following 2 show commands from each of the switches:
"show configuration system domain-search"
"show configuration system name-server"

Below are the configuration changes required at the operational and configuration level
hierarchy in a sequential manner:

Operational mode command:
rollback 0

Configuration mode commands:
set system domain-search domain1.edu
set system domain-search domain2.edu
set system name-server 10.X.X.X
set system name-server 172.X.X.X
commit

Operational mode command:
show configuration system domain-search
show configuration system name-server

Would really appreciate the help.

**Comment by vnitinv** [comment]
@Birajan2019 Have you explored using Ansible for this purpose.

**Comment by Birajan2019** [comment]
Thanks Vinit, I will check the ansible option as well.

**Comment by sean1986** [comment]
@Birajan2019, you might also find a couple books from Juniper's "Day One" library helpful:
https://www.juniper.net/documentation/jnbooks/en_US/day-one-books/

"Automating Junos with Ansible, 2nd edition" -- writing Ansible playbooks to query devices for information and make configuration changes. 

"Junos PyEZ Cookbook" -- a series of "recipes" for using PyEZ.

**Comment by ntwrkguru** [comment]
@Birajan2019 [This](https://www.juniper.net/documentation/en_US/junos-pyez/topics/task/program/junos-pyez-program-configuration-data-loading.html) may help you. 

Keep in mind that there are myriad ways to accomplish any given task. If this is purely for this one exercise, then it's fairly basic. However batch configuration and operational tasks are pretty common place. If it were me, I would write something that is flexible enough to make arbitrary configuration changes and arbitrary operational commands. Consider taking this opportunity to also move those switches into an infrastructure as code paradigm where the configurations are Jinja templates and the device specifics are variables. That is way to advanced to cover in this reply, so I'll focus on the task-driven request at hand.

You would need to construct the device from variables, iterate over the devices, and apply the configuration. 

This example should help get you going. *ALWAYS* do development and testing in a *SAFE* environment. Do not copy/paste code from the Internet and apply it to a production device blindly. 

```python
#!/usr/bin/env python3

from jnpr.junos import Device
from jnpr.junos.utils.config import Config

devices = [ { 'host': 'R1', 'user': 'lab' }, { 'host': 'R2', 'user': 'lab' } ]
configlet = """
system {
    domain-search [ domain1.edu domain2.edu ];
    name-server {
        8.8.8.8;
        4.4.4.4;
    }
}
"""

for device in devices:
    with Device(host=device['host'], user=device['user']) as dev:
        print("Connecting to %s" % device['host'])
        with Config(dev,mode='private') as conf:
            if conf.diff() is None:
                conf.load(configlet,format='text')
                if conf.commit_check():
                    if conf.pdiff() is None:
                        print("Nothing to commit")
                        break
                    print(conf.pdiff())
                    confirmation = input("Commit? (yes/no)\n")
                    if confirmation == 'yes':
                        print("Committing configuration")
                        conf.commit()
                    else:
                        print("rolling Back")
                        conf.rollback()
                else:
                    conf.rollback()
            else:
               print("There are uncommitted changes on %s. Changes: %s" % (device['host'], conf.diff))

        op = ['show configuration system name-server','show configuration system domain-search']
        for line in op:
            print(line)
            print(dev.cli(line))
```

**Comment by Birajan2019** [comment]
Thanks @sean1986  and @ntwrkguru. It really helps to see the different options available. I will try the ansible option 1st (which I am close to finishing) and then try the python option suggested by @ntwrkguru. This case can be closed.
