### ISSUE TITLE
Need more information from the pyez regarding the software install

### ISSUE THREAD

**Issue by ldhulipala-49** [Juniper/py-junos-eznc#1026]
Hi Nitin,
       As discussed, we need more information from the pyez during the software install failure other than just "False" as status. It would be good if more information regarding the reason for failure is returned to TOBY. 

Thanks,
Raghu

**Comment by rahkumar651991** [comment]
Code changes done for the issue in https://github.com/Juniper/py-junos-eznc/pull/1045 . 
Closing the issue as it is merged in latest release. Do read release notes of 2.5.0 for further info.
