### ISSUE TITLE
wrong device version when fetching pyez facts for nfx250ha-c

### ISSUE THREAD

**Issue by Kajalwaldiya** [Juniper/py-junos-eznc#1032]
Hi,
The pyez version info received for this particular device:nfx250ha-c for is coming wrong.

{'2RE': False, 'HOME': '/var/home/regress', 'RE0': {'status': 'OK', 'up_time': '10 hours, 35 minutes, 48 seconds', 'mastership_state': 'master', 'model': 'RE-NFX250-S2', 'last_reboot_reason': '0x1:power cycle/failure'}, 'RE1': None, 'RE_hw_mi': True, 'current_re': ['master', 'fpc0', 'node', 'fwdd', 'member', 'pfem', 're0', 'fpc0.pic0'], 'domain': 'englab.juniper.net', 'fqdn': None, 'hostname': None, 'hostname_info': {'node0': 'nfx250ha-c', 'node1': 'nfx250ha-d'}, 'ifd_style': 'CLASSIC', 'junos_info': {'node0': {'text': '20.2I-20200427.0.0631', 'object': junos.version_info(major=(20, 2), type=I, minor=-20200427, build=0)}, 'node1': {'text': '20.2I-20200427.0.0631', 'object': junos.version_info(major=(20, 2), type=I, minor=-20200427, build=0)}}, 'master': 'RE0', 'model': None, 'model_info': {'node0': 'NFX250_S2_10_T', 'node1': 'NFX250_S2_10_T'}, 'personality': None, 're_info': {'node0': {'0': {'status': 'OK', 'mastership_state': 'master', 'model': 'RE-NFX250-S2', 'last_reboot_reason': '0x1:power cycle/failure'}, 'default': {'status': 'OK', 'mastership_state': 'master', 'model': 'RE-NFX250-S2', 'last_reboot_reason': '0x1:power cycle/failure'}}, 'default': {'0': {'status': 'OK', 'mastership_state': 'master', 'model': 'RE-NFX250-S2', 'last_reboot_reason': '0x1:power cycle/failure'}, 'default': {'status': 'OK', 'mastership_state': 'master', 'model': 'RE-NFX250-S2', 'last_reboot_reason': '0x1:power cycle/failure'}}}, 're_master': {'node0': '0', 'default': '0'}, 'serialnumber': 'DD1917AF0016', 'srx_cluster': True, 'srx_cluster_id': '255', 'srx_cluster_redundancy_group': {'0': {'cluster_id': '255', 'node0': {'status': 'primary', 'failover_mode': 'no', 'priority': '1', 'preempt': 'no'}, 'failover_count': '1', 'node1': {'status': 'disabled', 'failover_mode': 'no', 'priority': '1', 'preempt': 'no'}}}, 'switch_style': 'VLAN_L2NG', 'vc_capable': False, 'vc_fabric': None, 'vc_master': None, 'vc_mode': None, '**_version': '0.0I0.0_**', 'version_RE0': '20.2I-20200427.0.0631', 'version_RE1': '20.2I-20200427.0.0631', 'version_info': junos.version_info(major=(0, 0), type=I, minor=0, build=0), 'virtual': None}. 

Here the version seems to be incorrect 0.0I0.0, as the right version is 20.3I.

**Comment by mirceaulinic** [comment]
I'm noticing the same on multi-node SRX 4100 series.

I personally find it's a very surprising decision to just return a dummy, meaningless version when unable to extract the information (usually it's better to raise an error, than silently make it look like everything is fine).

**Comment by ntwrkguru** [comment]
> I'm noticing the same on multi-node SRX 4100 series.
> 
> I personally find it's a very surprising decision to just return a dummy, meaningless version when unable to extract the information (usually it's better to raise an error, than silently make it look like everything is fine).

That isn't a PyEZ error or dummy data; it's coming from Junos. It won't matter if it's multi-node, or not, I don't think. It's an issue of being virtual Junos and not populating `version_info`.

**Comment by mirceaulinic** [comment]
> That isn't a PyEZ error or dummy data; it's coming from Junos. It won't matter if it's multi-node, or not, I don't think. It's an issue of being virtual Junos and not populating version_info.

What do you mean by `being virtual Junos`? The devices I'm seeing this on are actual production firewalls, and in `show version | display xml` I'm seeing the version being reported correctly as `<junos-version>15.1X49-D120.3</junos-version>`.
Alas, that dummy data does seem to be set by PyEZ when being unable to extract the data from the reply: https://github.com/Juniper/py-junos-eznc/blob/master/lib/jnpr/junos/facts/get_software_information.py#L236-L237

Note, the XML reply on my devices is wrapped around `<multi-routing-engine-results><multi-routing-engine-item>` tags which I believe is the root cause of why PyEZ fails to extract the information correctly.

**Comment by ntwrkguru** [comment]
2 things:
- The newer chassis use virtual Junos on a Junos-branded box, running a hypervisor. Much like a vSRX on an NFX.
- So you would prefer "None" to some placeholder data? Or you would prefer it to throw an exception, even if otherwise the logic would be fine without it?

**Comment by mirceaulinic** [comment]
Thanks for clarifying @ntwrkguru. I would prefer to throw an exception, than filling up with meaningless data -- this way, it's clear to the ens user that there's a problem, report it and get it fixed; otherwise, it masks an issue, and makes it confusing (both for the user, and the maintainers as it seems to be the case as per discussion above).

**Comment by ntwrkguru** [comment]
Problem with the exception is that, unless you disable fact gathering, you will always hit an exception in these cases, where you may not even need that key from the facts. I think the best course of action is for us to raise a PR to Junos to populate that field with a value. I do think a valid interim step would be to set it to "unknown" or some self-explanatory string as opposed to"0.0|0.0", though. Thoughts @vnitinv ?

**Comment by mirceaulinic** [comment]
Before I start working on a PR, let me share some more details of what I'm seeing:

- The full XML reply is:

 ```xml
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/15.1X49/junos">
    <multi-routing-engine-results>
        
        <multi-routing-engine-item>
            
            <re-name>node0</re-name>
            
            <software-information>
                <host-name>some-firewall</host-name>
                <product-model>srx4100</product-model>
                <product-name>srx4100</product-name>
                <junos-version>15.1X49-D120.3</junos-version>
                <package-information>
                    <name>junos</name>
                    <comment>JUNOS Software Release [15.1X49-D120.3]</comment>
                </package-information>
            </software-information>
        </multi-routing-engine-item>
        
        <multi-routing-engine-item>
            
            <re-name>node1</re-name>
            
            <software-information>
                <host-name>some-firewall</host-name>
                <product-model>srx4100</product-model>
                <product-name>srx4100</product-name>
                <junos-version>15.1X49-D120.3</junos-version>
                <package-information>
                    <name>junos</name>
                    <comment>JUNOS Software Release [15.1X49-D120.3]</comment>
                </package-information>
            </software-information>
        </multi-routing-engine-item>
        
    </multi-routing-engine-results>
    <cli>
        <banner>{primary:node0}</banner>
    </cli>
</rpc-reply>
```

- ``current_re`` in the facts is: ``['master', 'fpc0', 'node', 'fwdd', 'member', 'pfem', 're0', 'fpc0.pic0']``. Notice that ``node0`` and ``node1`` from the `show version`` output above, are not listed in there. This seems to have an implication around the logic from https://github.com/Juniper/py-junos-eznc/blob/master/lib/jnpr/junos/facts/get_software_information.py#L197-L225.

That said, I'd be tempted to work a 6th case in that sequence to treat this scenario.

**Comment by vnitinv** [comment]
These are the commands used by PyEZ to gather some facts based on which version is decided
 
Working device
 
```
xxxx@porter2-branch-a> show chassis cluster status
Monitor Failure codes:
    CS  Cold Sync monitoring        FL  Fabric Connection monitoring
    GR  GRES monitoring             HW  Hardware monitoring
    IF  Interface monitoring        IP  IP monitoring
    LB  Loopback monitoring         MB  Mbuf monitoring
    NH  Nexthop monitoring          NP  NPC monitoring
    SP  SPU monitoring              SM  Schedule monitoring
    CF  Config Sync monitoring      RE  Relinquish monitoring
    IS  IRQ storm
 
Cluster ID: 10
Node   Priority Status               Preempt Manual   Monitor-failures
 
Redundancy group: 0 , Failover count: 1
node0  1        primary              no      no       None
node1  1        secondary            no      no       None
 
Redundancy group: 1 , Failover count: 1
node0  254      primary              no      no       None
node1  1        secondary            no      no       None
 
Redundancy group: 2 , Failover count: 1
node0  254      primary              no      no       None
node1  1        secondary            no      no       None
 
xxx@nfx250ha-c> show chassis cluster status
Monitor Failure codes:
    CS  Cold Sync monitoring        FL  Fabric Connection monitoring
    GR  GRES monitoring             HW  Hardware monitoring
    IF  Interface monitoring        IP  IP monitoring
    LB  Loopback monitoring         MB  Mbuf monitoring
    NH  Nexthop monitoring          NP  NPC monitoring
    SP  SPU monitoring              SM  Schedule monitoring
    CF  Config Sync monitoring      RE  Relinquish monitoring
    IS  IRQ storm
 
Cluster ID: 255
Node   Priority Status               Preempt Manual   Monitor-failures
 
Redundancy group: 0 , Failover count: 1
node0  1        primary              no      no       None
node1  1        secondary            no      no       None
 
```

is cluster id 255 expected value?
Above cluster id is operated with bit wise operator

https://github.com/Juniper/py-junos-eznc/blob/master/lib/jnpr/junos/facts/current_re.py#L62-L80
 
and then is matched with below commands o/p to decide current ids. 10 << 4 is 160
 
```
xxxx@porter2-branch-a> show interfaces routing-instance __juniper_private1__
 
q  Logical interface em1.0 (Index 5) (SNMP ifIndex 24)
    Flags: Up SNMP-Traps 0x4000000 Encapsulation: ENET2
    Input packets : 14342889
    Output packets: 16616598
    Protocol inet, MTU: 1500
    Max nh cache: 75000, New hold nh limit: 75000, Curr nh cnt: 5, Curr new hold cnt: 0, NH drop cnt: 0
      Flags: Is-Primary
      Addresses, Flags: Is-Preferred
        Destination: 0/8, Local: 0.0.0.0, Broadcast: 0.255.255.255
      Addresses, Flags: Primary Is-Preferred Is-Primary
        Destination: 128/2, Local: 129.160.0.1, Broadcast: 191.255.255.255
      Addresses, Flags: Kernel
        Destination: 128/2, Local: 143.160.0.1, Broadcast: 191.255.255.255
    Protocol tnp, MTU: 1500
      Flags: Is-Primary
      Addresses
        Local: 0x1a00001
 
```
But in case of non-working device  255 << 4 is 4080 which doesn’t match in the interface o/p. Hence logic breaks.

PyEZ looks to not support higher cluster id. We need to fix this.

Another issue on same line: https://github.com/Juniper/py-junos-eznc/issues/819
