### ISSUE TITLE
OSPF get commands return no data for non-default routing-instances

### ISSUE THREAD

**Issue by pieterdejaeghere** [Juniper/py-junos-eznc#1061]
JunOS version:
Model: EX9208
Junos: 17.3R3-S7

On CLI:

```
me@junos> show ospf neighbor
OSPF instance is not running

{master}
me@junos> show ospf neighbor instance all
Instance: inside
Address          Interface              State     ID               Pri  Dead
10.1.62.10      irb.900                Full      10.1.62.10      128    36
10.1.63.18      irb.909                Full      10.1.0.35         0    36
10.1.191.6      xe-0/0/2.10            Full      10.1.128.1        1    38

me@junos> show ospf neighbor instance all | display xml rpc
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/17.3R3/junos">
    <rpc>
        <get-ospf-neighbor-information>
                <instance>all</instance>
        </get-ospf-neighbor-information>
    </rpc>
    <cli>
        <banner>{master}</banner>
    </cli>
</rpc-reply>
```

On eznc 2.5.0:
```
dev.rpc.get_ospf_neighbor_information({"format":"json","instance":"all"})
{'output': [{'data': 'OSPF instance is not running'}]}
```

From my understanding of how eznc works, this should be fixable by editing the yaml files for OSPF and include a parameter instance with a default. However couldn't get that to work yet on a first attempt. Situation is identical for OSPFv3.

Thanks for looking into it.

**Comment by rahkumar651991** [comment]
@pieterdejaeghere  - can you share the output for the following 

*) ssh test@10.93.22.65 -s netconf 
*) <rpc><get-ospf-neighbor-information><instance>all</instance></get-ospf-neighbor-information></rpc>

The rpc-reply of this and "show ospf neighbor instance all " is expected to be same as you have already checked the 
"show ospf neighbor instance all | display xml rpc"

**Comment by pieterdejaeghere** [comment]
The netconf command seems to provide all the info needed. 

`<rpc><get-ospf-neighbor-information><instance>all</instance></get-ospf-neighbor-                                                                                                                                                             information></rpc>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://x                                                                                                                                                             ml.juniper.net/junos/19.1R0/junos">
<ospf-neighbor-information-all xmlns="http://xml.juniper.net/junos/19.1R0/junos-                                                                                                                                                             routing">
<ospf-instance-neighbor>
<ospf-instance-name>inside</ospf-instance-name>
<ospf-neighbor>
<neighbor-address>10.1.62.10</neighbor-address>
<interface-name>irb.900</interface-name>
<ospf-neighbor-state>Full</ospf-neighbor-state>
<neighbor-id>10.1.62.10</neighbor-id>
<neighbor-priority>128</neighbor-priority>
<activity-timer>39</activity-timer>
</ospf-neighbor>
<ospf-neighbor>
<neighbor-address>10.1.63.18</neighbor-address>
<interface-name>irb.909</interface-name>
<ospf-neighbor-state>Full</ospf-neighbor-state>
<neighbor-id>10.1.0.35</neighbor-id>
<neighbor-priority>0</neighbor-priority>
<activity-timer>38</activity-timer>
</ospf-neighbor>
<ospf-neighbor>
<neighbor-address>10.1.191.6</neighbor-address>
<interface-name>xe-0/0/2.10</interface-name>
<ospf-neighbor-state>Full</ospf-neighbor-state>
<neighbor-id>10.1.128.1</neighbor-id>
<neighbor-priority>1</neighbor-priority>
<activity-timer>37</activity-timer>
</ospf-neighbor>
</ospf-instance-neighbor>
</ospf-neighbor-information-all>
</rpc-reply>
]]>]]>`

eznc (2.6.0) still says it's not running (retested because we changed from 17.3 -> 19.1):
`>>> d.rpc.get_ospf_neighbor_information({"format":"json","instance":"all"})
{'output': [{'data': 'OSPF instance is not running'}]}`

**Comment by rahkumar651991** [comment]
@pieterdejaeghere - try this. 
dev.rpc.get_ospf_neighbor_information({"format":"json"}, instance='all')

**Comment by pieterdejaeghere** [comment]
you're absolutely right 🤦 

Sorry to have wasted your time and thanks for the help.

**Comment by rahkumar651991** [comment]
@pieterdejaeghere - Good to know that issue is resolved. 

Closing this issue. In case of any related issues feel free to open a new issue.
