### ISSUE TITLE
Cannot escape quotes from cli -c using Start Shell

### ISSUE THREAD

**Issue by dmtx97** [Juniper/py-junos-eznc#1076]
This is more an issue with cli on Junos devices but I am not too sure how to match case with spaces.

Documentation states to escape quotes with ``\``, however even on my physical device, doing this does not work. Does anyone have a similar issue or am I doing this incorrectly? 

Thank you.

Below is a simple example of what I am trying to accomplish. I never use the -c flag when checking information usually, but this seems the only way to use Start Shell.

```
 'cli -c "show configuration | display set | match \"set ethernet-switching-options\""'
```

**Comment by ntwrkguru** [comment]
It doesn't answer your question, but this is pretty anti-pattern for automation tasks. Typically, one would use the `get_config` RPC and parse with XPATH to get the information desired.

**Comment by dmtx97** [comment]
@ntwrkguru thank you I ended up doing this and it works great. My original intention was to check what ports have enabled yet link down status. I was able to parse it using Start Shell but wasn't sure if there is a way to use match flag parameter with spaces.

**Comment by ntwrkguru** [comment]
@dmtx97 In that case, I would use [table views](https://www.juniper.net/documentation/en_US/junos-pyez/topics/concept/junos-pyez-tables-and-views-overview.html).
