### ISSUE TITLE
Enhance sw.install to supported mixed mode VC

### ISSUE THREAD

**Issue by sebastianw** [Juniper/py-junos-eznc#108]
Mixed mode Virtual-Chassis require multiple packages as a set. Currently this isn't supported by the util.sw.install routine.

**Comment by shermdog** [comment]
General note for implementation

* Will have to specify the packages for all types of VCF members
  * We will probably leave this up to the user to verify
* SCP those packages to master
* ```request system software add set [package1 package2 ...] reboot```

**Comment by sebastianw** [comment]
@jeremyschulman Sorry for never getting back to you about this, somehow I forgot all about it. We have EX4500/EX4200 or EX4550/EX4200 mixed VCs. Sadly I can't remember the code we had but @shermdog has the right idea. :) In regards to verification I think `request system software add ...` will fail anyway if it has the wrong type(s) of software for the members. At least I hope it does, I don't think we ever tested this.
