### ISSUE TITLE
mac-address issue with junos-eznc python library

### ISSUE THREAD

**Issue by alexandreseitz** [Juniper/py-junos-eznc#1097]
I am using: junos-eznc   2.5.4

It seems that jnpr library change mac-addresses values, all my mac-addresses are changed to f4:cc:55....
for example, on a Juniper MX-104 device, my xe-0/0/0 interface has:
**Current address: 28:a2:4b:12:df:f0, Hardware address: 28:a2:4b:12:d8:00**

When I use jnpr library to display interface xe-0/0/0 it returns: 
**Current address: f4:cc:55:a2:df:f0, Hardware address: f4:cc:55:a2:df:03**
```python
dev.rpc.cli(command='show interface xe-0/0/0',format='text',normalize=False)
```

I am trying to discover all mac-addresses from several devices, and the jnpr library returns me several times the same mac-address for different devices.

Is there an option to avoid this behavior?
thanks

**Comment by alexandreseitz** [comment]
Sorry, it is an error on my side

**Comment by alexandreseitz** [comment]
please ignore this issue

**Comment by ntwrkguru** [comment]
Have you considered using the `get-interface-information` RPC as opposed to throwing cli commands? Also, check out table views, as they are pretty handy for this type of situation.
