### ISSUE TITLE
Internal error: Huge input lookup

### ISSUE THREAD

**Issue by dseira** [Juniper/py-junos-eznc#1100]
Trying to get configuration in json format from a Juniper that has a huge configuration file I get the following error:

```
/usr/local/lib/python3.6/site-packages/jnpr/junos/device.py:801: RuntimeWarning: An unknown exception occured - please report.
  RuntimeWarning)
internal error: Huge input lookup, line 288211, column 1 (<string>, line 288211)
```

The code is just the rpc `get_config`:

```
data = dev.rpc.get_config(options={'format': 'json'})
```

Trying the same in XML or TEXT doesn't fail:

```
data = dev.rpc.get_config()                            --> OK
data = dev.rpc.get_config(options={'format': 'text'})  --> OK
```

The configuration from the JunOS CLI has the following lines count:

```
juni1> show configuration | display xml | count     
Count: 255926 lines

juni1> show configuration | display json | count   
Count: 288209 lines

juni1> show configuration | count                   
Count: 150139 lines
```

Also tried with `huge_tree=True` with the same result.

Any idea?

**Comment by ipmonk** [comment]
Wondering if the json itself is ok. Have you tried doing 'show configuration | display json | save foobar', then reading in the file contents using json.load()? Does that work ?

**Comment by rahkumar651991** [comment]
@dseira  - Could you share the sc ript how huge_tree was passed. Huge_tree should have resolved this issue.

**Comment by JorisvDumper** [comment]
Hi, 

I am facing the same issue with large vpls mac-tables. 

`/usr/local/lib/python3.8/dist-packages/jnpr/junos/device.py:857: RuntimeWarning: An unknown exception occurred - please report.
  warnings.warn(
internal error: Huge input lookup, line 433400, column 1 (<string>, line 433400)`

using this code
```
try:
    with Device(host=hostname, user=junos_username, passwd=junos_password, port=22) as dev:
        d1 = dev.rpc.get_vpls_connection_information({'format':'json'})

except Exception as err:
    print (err)
    sys.exit(1)
```

With XML there are no problems, this code works on other devices with smaller vpls-mac tables. 

```
joris@router> show vpls mac-table | display json | count    
Count: 229674 lines

joris@router> show vpls mac-table | count                   
Count: 34929 lines
```

With Netmiko it is possible to fetch the big vpls table:
`output = net_connect.send_command('show interface terse | display json')`

Any ideas, how to get this working?

**Comment by rahkumar651991** [comment]
Closing it due to inactivity.
