### ISSUE TITLE
commit_check() does not catch rpc-errors of warning severity

### ISSUE THREAD

**Issue by anee-git** [Juniper/py-junos-eznc#1119]
The following does not raise an exception for commits that are successful with a warning; for example a warning for a mandatory reboot, following commit.
```
try:
   self.rpc.commit_configuration(check=True, **rpc_args)
```
Because of the above behavior, the following condition in the commit_check() code,  (if err.rsp is not None and err.rsp.find("ok") is not None:) is never met:
```
      except RpcError as err:  # jnpr.junos exception
            if err.rsp is not None and err.rsp.find("ok") is not None:
                # this means there is a warning, but no errors
                return True
```
Is this expected behavior ? How can I catch a commit warning in a successful commit ? If this is expected behavior, the comments need to be updated in the code to indicate it.

**Comment by rahkumar651991** [comment]
@anee- Can you share the netconf logs captured at the device for the scenario and highlight the warning in it so we can understand the issue better and try to replicate it locally. 

Refer the link for more information - 
https://www.juniper.net/documentation/us/en/software/junos/junos-xml-protocol/topics/example/netconf-traceoptions-configuring.html

**Comment by anee-git** [comment]
@rahkumar651991 
Below is my execution code snippet and I've attached the relevant netconf logs as a .docx with the error highlighted.

I tried modifying my local imported copy of the module containing commit_check() to see if the execution enters the RpcError Exception that I'd pointed out in my issue above, but it doesn't. 

```
        try:
            print('Setting chassis network-services enhanced-ip')
            conf = 'set chassis network-services enhanced-ip'
            cu.load(conf, format='set', merge=True)
            cu.commit()
            print('Configuration successful')

        except RpcError as err: 
            print('Caught RpcError')
            if (err.rsp.lower()).find('reboot') is not None:
                rpc_msg = err.rsp.findtext('.//error-message')
                print(str(rpc_msg))
            print('chassis network-services enhanced-ip: config failed')
            pass
```

[netconf-ops.log.docx](https://github.com/Juniper/py-junos-eznc/files/6670910/netconf-ops.log.docx)

**Comment by rahkumar651991** [comment]
@anee-git - The commit function is written in a way that if <ok/> is returned in the rpc-reply then this means there are warnings, but no errors and the return type will be a boolean(true). the commit() api itself is raising the RpcError and handling it. It doesn't raise the RpcError to Python script if it only receives warning with an <ok/> in rpc-reply. 
 
In case you want warning as part of return in the commit() api then you can pass it as below
```
    print('Setting chassis network-services enhanced-ip')
    conf = 'set chassis network-services enhanced-ip'
    cu.load(conf, format='set', merge=True)
    print(etree.tostring(cu.commit(detail=True)))
    print('Configuration successful')
 ```
This will have the warnings but also have a lot other details as part of commit. "detail" parameter.

**Comment by rahkumar651991** [comment]
Closing this ticket as there are no follow up queries.
