### ISSUE TITLE
exception raised on rollback when warnings are present in config

### ISSUE THREAD

**Issue by ekoyle** [Juniper/py-junos-eznc#1128]
I am attempting to push a configuration to a device (ie. load override), do a diff, then rollback the configuration.  The rollback is raising an exception and does not have the ignore_warning parameter available.

The configuration I'm pushing is generating warnings (`warning: 25g config will be applied to ports 0 to 3` when setting port speed to 25g on 0/0/0 on a QFX5120-48Y, junos 18.4R2-S4).  This configuration is already in the running configuration on the switch.

The load and diff calls work as expected with ignore_warning set appropriately.

Is it expected to raise an exception on warnings during a rollback 0?  If so, would it be possible to add the ignore_warning parameter for rollback?

**Comment by rahkumar651991** [comment]
Can you check pull request 1131, if that works for you?
