### ISSUE TITLE
ConfigLoadError(severity: error, bad_element: None, message: error: SSL support disabled

### ISSUE THREAD

**Issue by fishert123** [Juniper/py-junos-eznc#1133]
I have three switches. One is QFX5100, the other two are vQFX.
I have the following codes:
httpscmd = 'https://10.10.10.10/junosConfig/' + UPDATEFile
cu.load(url=httpscmd,format='set')

QFX5100 works fine, but vQFX got the following:

Unable to load configuration changes: ConfigLoadError(severity: error, bad_element: None, message: error: SSL support disabled
error: fetch: https://10.10.10.10/junosConfig/testConfig: Authentication error)

I could not find any documentation about whether SSL  is officially supported. or what model supports it.

Anyone can shed some light here .

thanks !!

**Comment by rahkumar651991** [comment]
This is mostly a device configuration issue as displayed in error. Share us the configuration statement which is failing and the snippet of netconf logs captured on device where the error comes. We will look into it but not sure about this issue as not the right place for this query. 

For netconf logs - https://www.juniper.net/documentation/us/en/software/junos/junos-xml-protocol/topics/example/netconf-traceoptions-configuring.html

**Comment by chidanandpujar** [comment]
Hi ,

I am able to reproduce this issue on vQFX and load works fine with http and fails with following error for https

Traceback (most recent call last):
  File "issue_1133.py", line 7, in <module>
    cu.load(url=httpscmd,format='set')
  File "/usr/local/lib/python3.5/dist-packages/jnpr/junos/utils/config.py", line 584, in load
    return try_load(rpc_contents, rpc_xattrs, ignore_warning=ignore_warning)
  File "/usr/local/lib/python3.5/dist-packages/jnpr/junos/utils/config.py", line 496, in try_load
    raise ConfigLoadError(cmd=err.cmd, rsp=err.rsp, errs=err.errs)
jnpr.junos.exception.ConfigLoadError: ConfigLoadError(severity: error, bad_element: None, message: error: SSL support disabled
error: fetch: https://10.102.226.145/junosConfig/UPDATEFile: Authentication error)

Thanks & Regards
Chidanand

**Comment by chidanandpujar** [comment]
Hi @fishert123 ,

Issue looks to be related to RPC and RPC fails with following errors for https url on vQFX ,please file JUNOS defect/case to track this issue .
```
netconf 
<!-- No zombies were killed during the creation of this user interface -->
<!-- user root, class super-user -->
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file</capability>
    <capability>urn:ietf:params:xml:ns:netconf:base:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:confirmed-commit:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:url:1.0?scheme=http,ftp,file</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring</capability>
    <capability>http://xml.juniper.net/netconf/junos/1.0</capability>
    <capability>http://xml.juniper.net/dmi/system/1.0</capability>
  </capabilities>
  <session-id>5691</session-id>
</hello>
]]>]]>
<?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:75d49dd4-2670-4dee-a570-899d9492d37a"><load-configuration act
ion="set" format="text" url="https://xx.xx.xx.xx/junosConfig/UPDATEFile"/></nc:rpc>]]>]]><rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/20.4I0/junos" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:75d49dd4-2670-4dee-a570-899d9492d37a">

<load-configuration-results>
<rpc-error>
<error-type>protocol</error-type>
<error-tag>operation-failed</error-tag>
<error-severity>error</error-severity>
<error-message>
SSL support disabled
</error-message>
</rpc-error>
<rpc-error>
<error-type>protocol</error-type>
<error-tag>operation-failed</error-tag>
<error-severity>error</error-severity>
<error-message>
fetch: https://xx.xx.xx.xx/junosConfig/UPDATEFile: Authentication error
</error-message>
</rpc-error>
</load-configuration-results>
</rpc-reply>
]]>]]>

```

Thanks & Regards
Chidanand

**Comment by chidanandpujar** [comment]
Hi @fishert123 

   Thanks for reporting the issue , I have submitted JUNOS PR to track the RPC failure and closing this issue .

Thanks & Regards
Chidanand

**Comment by fishert123** [comment]
thanks a lot !!
