### ISSUE TITLE
RPC Returns "syntax error"

### ISSUE THREAD

**Issue by blkangl** [Juniper/py-junos-eznc#1142]
This basic python script will show the issue. Please note that there is an SSH key in this user's .ssh folder that is authorized on the firewall, so credentials are not required for us.

Notes: This is a CLUSTERED firewall (RPC works fine on non-clustered). 
Juniper support case 2021-1116-363294 has been opened for this issue to check the Juniper software side. This case includes the rsi from the firewall.

============================
import json
import sys
from jnpr.junos import Device

config = {
 "ip" : "10.192.229.175",
  "node_num" : "node 0"
}

Device.auto_probe = 10
with Device( host = config["ip"], user = "salt-admin", port = 22 ) as dev:
  rsp = dev.rpc.retrieve_source_nat_pool_resource_usage({'format':'json'}, all=True)
  print(json.dumps(rsp))
============================

This script returns the following output:

============================
{"multi-routing-engine-results": [{"multi-routing-engine-item": [{"re-name": [{"data": "node0"}], "error": [{"attributes": {"xmlns": "http://xml.juniper.net/xnm/1.1/xnm", "xmlns:xnm": "http://xml.juniper.net/xnm/1.1/xnm"}, "column": [{"data": "0"}], "token": [{"data": "source-pool"}], "message": [{"data": "syntax error, expecting <command> or </command>"}]}]}, {"re-name": [{"data": "node1"}], "error": [{"attributes": {"xmlns": "http://xml.juniper.net/xnm/1.1/xnm", "xmlns:xnm": "http://xml.juniper.net/xnm/1.1/xnm"}, "column": [{"data": "0"}], "token": [{"data": "source-pool"}], "message": [{"data": "syntax error, expecting <command> or </command>"}]}]}]}]}
============================

The big issue here is that the response from the firewall is saying there is a syntax error and it expects a command.  Since these are RPC calls, I cannot control this, and this is either an issue in Juniper or an issue with this library.

**Comment by chidanandpujar** [comment]
Hi ,

this looks to be related to RPC issue , rpc execution fails on the SRX cluster.
This is junos issue , RPC fails with following errors 



<nc:hello xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
   <nc:capabilities>
    <nc:capability>urn:ietf:params:netconf:base:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:candidate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:validate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:netconf:base:1.0?module=ietf-netconf&amp;revision=2011-06-01</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:netconf:capability:candidate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:netconf:capability:confirmed-commit:1.0</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:netconf:capability:validate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:netconf:capability:url:1.0?scheme=http,ftp,file</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:yang:ietf-inet-types?module=ietf-inet-types&amp;revision=2013-07-15</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring</nc:capability>
    <nc:capability>http://xml.juniper.net/netconf/junos/1.0</nc:capability>
    <nc:capability>http://xml.juniper.net/dmi/system/1.0</nc:capability>
  </nc:capabilities>
  <nc:session-id>7294</nc:session-id>
</nc:hello>
]]>]]>
<rpc>
        <retrieve-source-nat-pool-resource-usage>
                <all/>
        </retrieve-source-nat-pool-resource-usage>
</rpc><nc:rpc-reply xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/19.3R0/junos">
<multi-routing-engine-results>

<multi-routing-engine-item>

<re-name>node0</re-name>

<error xmlns="http://xml.juniper.net/xnm/1.1/xnm" xmlns:xnm="http://xml.juniper.net/xnm/1.1/xnm">
<column>0</column>
<token>source-pool</token>
<message>syntax error, expecting &lt;command&gt; or &lt;/command&gt;</message>
</error>
</multi-routing-engine-item>

<multi-routing-engine-item>

<re-name>node1</re-name>

<error xmlns="http://xml.juniper.net/xnm/1.1/xnm" xmlns:xnm="http://xml.juniper.net/xnm/1.1/xnm">
<column>0</column>
<token>source-pool</token>
<message>syntax error, expecting &lt;command&gt; or &lt;/command&gt;</message>
</error>
</multi-routing-engine-item>

</multi-routing-engine-results>

</nc:rpc-reply>
]]>]]>

**Comment by chidanandpujar** [comment]
Hi @blkangl 

Thanks for reporting the issue, I have submitted JUNOS PR -1638653 to track the issue and closing this PyEz issue .

Thanks & Regards
Chidanand
