### ISSUE TITLE
please upgrade ncclient version

### ISSUE THREAD

**Issue by nskalis** [Juniper/py-junos-eznc#1153]
Hi,

In the `requirements.txt` file there is a comment
```
# ncclient version 0.6.10 has issues with PyEZ(junos-eznc) and needs to be avoided
ncclient==0.6.9
```

Looking at the [releases](https://github.com/ncclient/ncclient/releases) page of the `ncclient` project it seems that any problems should be resolved since 29 May 2021 (in `0.6.12`).
```
Fix for unintentional breakage of JunOS ExecuteRPC
```

Would you be so kind to confirm the fix and release the new version of `PyEZ` on PyPI?

Right now, it is impossible for a network running *juniper/junos* and *nokia/sros* (supported by `0.6.10` that most ISPs do) to use `PyEZ` (to interact with *junos*) and `ncclient` (to interact with *sros*).

**Comment by itheodoridis** [comment]
I am having the same problem, trying to install nornir-netconf which requires at least ncclient 0.6.12, while py-junos-eznc enforces ncclient 0.6.9. I don't have even have juniper on my network.
Please resolve this matter.

**Comment by ydnath** [comment]
https://github.com/Juniper/py-junos-eznc/pull/1175 provided the changes
