### ISSUE TITLE
Custom TextFSM Templates : TextFSM File name format when "\" is used in the command name 

### ISSUE THREAD

**Issue by balasankarrajaguru** [Juniper/py-junos-eznc#1162]
Background : 

Junos PyEZ Tables can use the TextFSM templates that are installed as part of the ntc-templates package, or they can reference custom TextFSM templates. To use custom TextFSM templates in your Junos PyEZ application, you must stage the template and then specify the absolute path to the template directory when you define the Table instance.

Ref : https://www.juniper.net/documentation/us/en/software/junos-pyez/junos-pyez-developer/topics/concept/junos-pyez-tables-op-using-textfsm-templates.html

PyEZ expects the custom textfsm to be of the below convention

 "platform_command.textfsm"

Example :  juniper_show-verion.textfsm

With this convention, if the command for example "show interface ge-0/0/0" contains "/", then the custom textfsm for this command cannot be created as the slash "/" character cannot be used as a file name.  

Error Logs for one of the samle commands involving "/" : 

"Failed due to: Template 'cisco_xe_show_hw-module_subslot_0/0_transceiver_0_status.textfsm' not found",

This is blocking using of textfsm feature for command involving "/"

**Comment by chidanandpujar** [comment]
fix is merged , please verify the fix .
https://github.com/Juniper/py-junos-eznc/pull/1163

**Comment by chidanandpujar** [comment]
fix is merged , please verify the fix .
https://github.com/Juniper/py-junos-eznc/pull/1163fix is merged , please verify the fix .

**Comment by chidanandpujar** [comment]
fix is merged , please verify the fix .
https://github.com/Juniper/py-junos-eznc/pull/1163fix is merged , please verify the fix .
