### ISSUE TITLE
Problem parsing JSON from returned config

### ISSUE THREAD

**Issue by topranks** [Juniper/py-junos-eznc#1166]
Hi,

We have some Juniper devices with the following configuration:

    cmooney@re0.cr1-eqiad> show configuration snmp filter-interfaces 
    interfaces {
        "^.*\.0$";
    }

When I try to retrieve the JSON formatted config from this device PyEZ throws the following error:

      File "/usr/local/lib/python3.8/dist-packages/jnpr/junos/device.py", line 884, in execute
        raise JSONLoadError(ex, rpc_rsp_e.text)
    jnpr.junos.exception.JSONLoadError: JSONLoadError(reason: Invalid \escape: line 2798 column 34 (char 121376), 
    The offending config appears to be: 
    2796:                 "interfaces" : [
    2797:                 {
    2798:                     "name" : "^.*\.0$"
    2799:                 }
    2800:                 ]
    )

The line which causes this is not in PyEZ, just the standard Python JSON library:

https://github.com/Juniper/py-junos-eznc/blob/e0e33ddc53c43b19635187db5ab48f3cf4c0a07b/lib/jnpr/junos/device.py#L878

I've been able to work around this by changing the line as follows, to add an additional backslash and properly escape the regex string from the config:

    return json.loads(rpc_rsp_e.text.replace("\\", "\\\\"), strict=False)

Obviously this is not really ideal though, there may well be a much better fix so I'm reluctant to submit a PR.  It's working for me right now but wanted to raise the issue so you are aware.

**Comment by stacywsmith** [comment]
The device is producing configuration output that is not valid JSON. Specifically, the string doesn't have the `\` properly escaped. That's a Junos bug, and I encourage you to open a case with JTAC.

**Comment by topranks** [comment]
Thanks for the feedback, and yep that makes sense.

Looking at it actually we get this problem on our MX devices on 17.3.  Some QFX switches with the same config, running 20.4, do not have the problem, looks like they escape the backslash in the JSON output correctly:

    cmooney@lsw1-e1-eqiad> show configuration snmp filter-interfaces | display json 
    {
        "configuration" : {
            "@" : {
                "junos:commit-seconds" : "1649780227", 
                "junos:commit-localtime" : "2022-04-12 16:17:07 UTC", 
                "junos:commit-user" : "cmooney"
            }, 
            "snmp" : {
                "filter-interfaces" : {
                    "@" : {
                        "comment" : "/* T283060 */" 
                    }, 
                    "interfaces" : [
                    {
                        "name" : "^.*\\.0$"
                    }
                    ]
                }
            }
        }
    }

So it's likely this will be solved in an upgrade.  I'll close this issue now but hopefully it'll show up in search results for anyone else who hits it.
