### ISSUE TITLE
Request security policies check RPC error

### ISSUE THREAD

**Issue by natzberg** [Juniper/py-junos-eznc#1168]
dev.rpc.check_security_policies() fails with error "Unrecognized command (network-security)"

using CLI to debug says: 
"CLI command is for debug use only!
Instead of:
cli('request security policies check')
Use:
rpc.check_security_policies()"

**Comment by dineshbaburam91** [comment]
This is a device bug. Bug ticket created internally.

https://gnats.juniper.net/web/default/1674207
