### ISSUE TITLE
Delimiter `]]>]]>` not removed completely and raw data isn't parsed properly 

### ISSUE THREAD

**Issue by sharanyabhat** [Juniper/py-junos-eznc#1171]
The issue is seen while parsing the raw data in pyez. The delimiter `]]>]]>` isnt removed completely while parsing the raw data, residues are retained which causes the error to skip all further rows. Issue not seen recently, and can only be replicated randomly with huge raw-data influx.

Seen in junos-eznc==2.5.4

**Comment by chidanandpujar** [comment]
Please provide the steps to reproduce this  issue .

Thanks
