### ISSUE TITLE
start_shell broken in 2.6.4

### ISSUE THREAD

**Issue by andsouth44** [Juniper/py-junos-eznc#1190]
In 2.6.4 version, in the start_shell utility, in the open() method, on line 127:

                self.send("start shell" + self.shell_type)
                
             
The code creates a string with no space, e.g. self.send("start shellcsh")>
This results in syntax error on device but creates no Exception in the code.

Code should be:

                self.send("start shell " + self.shell_type)

plus relevant code to catch syntax error.

**Comment by dineshbaburam91** [comment]
Fixed #1191
