### ISSUE TITLE
"ping-success": null

### ISSUE THREAD

**Issue by tamaszl** [Juniper/py-junos-eznc#1195]
ping_results.append(dev.rpc.ping(host='4.2.2.2', count='3', rapid=True, source='113.31.156.1'))

>>> print (json.dumps(ping_results))
[{"target-host": "4.2.2.2", "source": "113.31.166.1", "target-ip": "4.2.2.2", "packet-size": "56", "probe-result": {"probe-index": "3", "probe-success": null, "sequence-number": "2", "ip-address": "4.2.2.2", "time-to-live": "49", "response-size": "64", "rtt": "262859"}, "probe-results-summary": {"probes-sent": "3", "responses-received": "3", "packet-loss": "0", "rtt-minimum": "262859", "rtt-maximum": "272456", "rtt-average": "268830", "rtt-stddev": "4254"}, "ping-success": null}]

As you can see from the results all 3 pings responded, but "ping-success" returned null. Why is this?

**Comment by dineshbaburam91** [comment]
In Junos device, in case of ping successful "ping-success" returns null which is expected behavior. This is not a bug.
