### ISSUE TITLE
EVO software package delete RPC doesn't return full output 

### ISSUE THREAD

**Issue by harshitakapadia** [Juniper/py-junos-eznc#1196]
I came across kind of issue while executing RPC’s : From REST API Explorer API when I test RPC request from explorer, I do get to see the entire output but when I do it via script the output from the device is only limited to the first line between the first tag of <output> </output>

Here is the execution code : 

dev = Device(host=<host> user='username', password='password', port=<port>)
 dev.open()

try :     
       sw = dev.rpc.request_package_delete(archived=True, dev_timeout=3600)  
except Exception as error:     
       print(error) 

print(type(sw)) 
print(etree.tostring(sw,method='html',with_tail=False))

![REST_API_explorer_output](https://user-images.githubusercontent.com/110109773/181264013-5062a1e2-486f-4c57-8d65-6b7194aa8b52.png)
![PYEZ_execution_output ](https://user-images.githubusercontent.com/110109773/181264084-b6a5f4fe-9ebd-4f2b-8e01-ace4c844f339.png)

**Comment by chidanandpujar** [comment]
Hi,

Could you please check with following options .

```

from jnpr.junos import Device
import xml.etree.ElementTree as etree 

dev = Device(host='xx.xx.xx.xx', user='xyz', password='xyz', port=22)
dev.open()

try :
    sw = dev.rpc.request_package_delete(package_name="na-telemetry", dev_timeout=3600)
except Exception as error:
    print(error)

print(type(sw))
print(etree.tostring(sw,method='html'))

<class 'lxml.etree._Element'>
b'<output>\nNOTICE: Validating configuration against absence of na-telemetry\nInitializing...\nMounting os-libs-11-x86-64-20210722.b0da34e0_builder_stable_11-204ab\nMounting os-runtime-x86-64-20210722.b0da34e0_builder_stable_11-204ab\nMounting os-zoneinfo-20210722.b0da34e0_builder_stable_11-204ab\nMounting junos-net-prd-x86-64-20211110.173530_builder_junos_202_r3_s3\nMounting junos-libs-x86-64-20211110.173530_builder_junos_202_r3_s3\nMounting os-libs-compat32-11-x86-64-20210722.b0da34e0_builder_stable_11-204ab\nMounting os-compat32-x86-64-20210722.b0da34e0_builder_stable_11-204ab\nMounting junos-libs-compat32-x86-64-20211110.173530_builder_junos_202_r3_s3\nMounting junos-runtime-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting jsim-pfe-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting sflow-mx-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting py-extensions2-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting py-extensions-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting py-base2-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting py-base-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting os-vmguest-x86-64-20210722.b0da34e0_builder_stable_11-204ab\nMounting os-crypto-x86-64-20210722.b0da34e0_builder_stable_11-204ab\nMounting junos-secintel-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting junos-libs-compat32-mx-x86-64-20211110.173530_builder_junos_202_r3_s3\nMounting junos-runtime-mx-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting junos-rpd-telemetry-application-x86-64-20.2R3-S3.6\nMounting junos-redis-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting junos-platform-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting junos-openconfig-x86-32-20.2R3-S3.6\nMounting junos-modules-x86-64-20211110.173530_builder_junos_202_r3_s3\nMounting junos-modules-mx-x86-64-20211110.173530_builder_junos_202_r3_s3\nMounting junos-libs-mx-x86-64-20211110.173530_builder_junos_202_r3_s3\nMounting junos-jsqlsync-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting junos-dp-crypto-support-mtx-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting junos-daemons-x86-64-20211110.173530_builder_junos_202_r3_s3\nMounting junos-daemons-mx-x86-64-20211110.173530_builder_junos_202_r3_s3\nMounting jsim-wrlinux-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting jsim-pfe-vmx-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting jsim-pfe-internal-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting jsdn-x86-32-20.2R3-S3.6\nMounting jsd-x86-32-20.2R3-S3.6-jet-1\nMounting jpfe-wrlinux9-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting jpfe-wrlinux-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting jpfe-spc3-mx-x86-32-20.2R3-S3.6\nMounting jpfe-X960-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting jpfe-common-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting jpfe-aft-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting jpfe-X-x86-32-20211110.173530_builder_junos_202_r3_s3\nMounting jmrt-base-x86-64-20211110.173530_builder_junos_202_r3_s3\nMounting jinsight-x86-32-20.2R3-S3.6\nMounting jfirmware-x86-32-20.2R3-S3.6\nMounting jdocs-x86-32-20211110.173530_builder_junos_202_r3_s3\nHardware Database regeneration succeeded\nValidating against /config/juniper.conf.gz\nmgd: commit complete\nValidation succeeded\n/packages/db/na-telemetry-x86-32-20.2R3-S3.6\nRebuilding schema and Activating configuration...\nmgd: commit complete\nRestarting MGD ...\n</output>'
```

**Comment by chidanandpujar** [comment]
Hi ,

issue is reproducible only on EVO , 

 python issue_1196.py 
<class 'lxml.etree._Element'>
b'<output>\nSoftware delete in progress...</output>'


Netconf trace logs :

Dec  6 05:38:43 [NETCONF] - [20029] Incoming: Received ']]>]]>' token which is split in two consecutive streams or has leading/trailing spaces/tabs or both.
Dec  6 05:38:44 [NETCONF] - [20029] Incoming: <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:0c7fbf6f-6252-4684-a9b9-556dd7659451"><request-package-delete><archived/></request-package-delete></nc:rpc>]]>]]>
Dec  6 05:38:44 [NETCONF] - [20029] Outgoing: <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/23.1I0/junos" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:0c7fbf6f-6252-4684-a9b9-556dd7659451">
Dec  5 21:38:45 [NETCONF] - [20029] Outgoing: <output>
Dec  5 21:38:45 [NETCONF] - [20029] Outgoing: Software delete in progress...
Dec  5 21:38:45 [NETCONF] - [20029] Outgoing: </output>
Dec  5 21:38:48 [NETCONF] - [20029] Outgoing: <output>
Dec  5 21:38:48 [NETCONF] - [20029] Outgoing: re0: Executing Software delete...
Dec  5 21:38:48 [NETCONF] - [20029] Outgoing: </output>
Dec  5 21:38:50 [NETCONF] - [20029] Outgoing: <output>
Dec  5 21:38:50 [NETCONF] - [20029] Outgoing: re0: Removing external packages for junos-evo-install-ptx-x86-64-...
Dec  5 21:38:50 [NETCONF] - [20029] Outgoing: </output>
Dec  5 21:38:50 [NETCONF] - [20029] Outgoing: <output>
Dec  5 21:38:50 [NETCONF] - [20029] Outgoing: re0: Done.
Dec  5 21:38:50 [NETCONF] - [20029] Outgoing: </output>
Dec  5 21:38:57 [NETCONF] - [20029] Outgoing: <output>
Dec  5 21:38:57 [NETCONF] - [20029] Outgoing: re1: Removing external packages for junos-evo-install-ptx-x86-64-2...
Dec  5 21:38:57 [NETCONF] - [20029] Outgoing: </output>
Dec  5 21:38:57 [NETCONF] - [20029] Outgoing: <output>
Dec  5 21:38:57 [NETCONF] - [20029] Outgoing: re1: Done.
Dec  5 21:38:57 [NETCONF] - [20029] Outgoing: </output>
Dec  5 21:39:01 [NETCONF] - [20029] Outgoing: <output>
Dec  5 21:39:01 [NETCONF] - [20029] Outgoing: Image deletion succeeded.
Dec  5 21:39:01 [NETCONF] - [20029] Outgoing: </output>
Dec  5 21:39:01 [NETCONF] - [20029] Outgoing: </rpc-reply>
Dec  5 21:39:01 [NETCONF] - [20029] Outgoing: ]]>]]>
Dec  5 21:39:01 [NETCONF] - [20029] Incoming: Received ']]>]]>' token which is split in two consecutive streams or has leading/trailing spaces/tabs or both.
Dec  5 21:39:01 [NETCONF] - [20029] Outgoing: 

Thanks 
Chidanand

**Comment by chidanandpujar** [comment]
Hi,

please check following solution ,

from jnpr.junos import Device
import xml.etree.ElementTree as etree

dev = Device(host='xx.xx.xx.xx', user='xyz', password='xyz', port=22)
dev.open()

try :
    sw = dev.rpc.request_package_delete(archived=True, dev_timeout=3600)
except Exception as error:
    print(error)

print(etree.tostring(sw.getparent()))



python issue_1196.py 
b'<rpc-reply message-id="urn:uuid:e50fbdaf-f7a8-4643-999b-9152f41dfe3c"><output>\nSoftware delete in progress...</output><output>\nre0: Executing Software delete...</output><output>\nre0: Removing external packages for junos-evo-install-ptx-x86-64-...</output><output>\nre0: Done.</output><output>\nre1: Removing external packages for junos-evo-install-ptx-x86-64-...</output><output>\nre1: Done.</output><output>\nImage deletion succeeded.</output></rpc-reply>'


Thanks
Chidanand
