### ISSUE TITLE
sw.install giving parse error when running on windows system

### ISSUE THREAD

**Issue by Aaron-MJohn** [Juniper/py-junos-eznc#1206]
Getting this error when running this code on windows system but works on Linux system.  
```
ok, msg = sw.install(
                        package=firmware_file,
                        progress=True,
                        no_copy=False,
                        validate=False,
                        cleanfs=True,
                    )
```
where firmware_file is file path to the firmware on the host system.

`fetch-secure: C:\Users\****\Desktop\****\network_switch_tool\ex2300-c\junos-arm-32-20.2R3-S3.6.tgz: parse error
ERROR: Cannot fetch file: C:\Users\****\Desktop\****\network_switch_tool\ex2300-c\junos-arm-32-20.2R3-S3.6.tgz`

**Comment by Aaron-MJohn** [comment]
Thanks you. 
My current solution is scp the file and update it from locally from the switch.

**Comment by chidanandpujar** [comment]
Fixed and merged via https://github.com/Juniper/py-junos-eznc/pull/1242
