### ISSUE TITLE
EthPortTable broken with v2.6.5

### ISSUE THREAD

**Issue by MarcoBorrini99** [Juniper/py-junos-eznc#1215]
In the following scenario:

- many MX960 devices (Junos: 19.4R3-S9.4)
- many ACX5448 devices (Junos: 21.4R2-S1.4)

within a 2.6.5 env, the following code outputs an empty EthPortTable (e.g.mip-12 is a mx960 with ge-*, xe-*, et-*, ae* interfaces):

```
>>> from jnpr.junos import Device
>>> dev = Device(host='mip-12', user='USER', password='PASSWORD')
>>> dev.open()
>>> from jnpr.junos.op.ethport import EthPortTable
>>> ethports = EthPortTable(dev)
>>> ethports.get()
EthPortTable:mip-12: 0 items
```

but in a 2.6.4 env:
```
>>> from jnpr.junos import Device
>>> dev = Device(host='mip-12', user='USER', password='PASSWORD')
>>> dev.open()
>>> from jnpr.junos.op.ethport import EthPortTable
>>> ethports = EthPortTable(dev)
>>> ethports.get()
EthPortTable:mip-12: 249 items
```

Can someone confirm this issue?

BR

**Comment by chidanandpujar** [comment]
UT logs:

from jnpr.junos import Device
from jnpr.junos.op.ethport import EthPortTable

with Device(host='xx.xx.xx.xx', password='xyz', gather_facts=False ) as dev:
    eths = EthPortTable(dev)
    eths.get()
    for port in eths:
        print ("{}: {}".format(port.name, port.oper))


pyez_table_view_test# python tableview.py 
ge-0/0/8: up
ge-0/0/9: down
ge-0/0/10: up
ge-0/0/11: up
ge-0/0/12: down
ge-0/0/13: up
ge-0/0/14: down
ge-0/0/15: up
ge-0/0/16: down
ge-0/0/17: down
ge-0/0/18: down
ge-0/0/19: down
ge-0/0/20: down
ge-0/0/21: down
ge-0/0/22: down
ge-0/0/23: down

python tableview.py 
et-0/0/1: up
et-0/0/3: up
et-0/0/5: up
et-0/0/7: up
et-0/0/9: up
et-0/0/11: up
et-0/0/13: up
et-0/0/15: up

python tableview.py 
ge-0/0/0: up
ge-0/0/1: up
ge-0/0/2: down
ge-0/0/3: down
ge-0/0/4: down
ge-0/0/5: down
ge-0/0/6: down
ge-0/0/7: down
ge-0/0/8: down
ge-0/0/9: down
ge-0/1/0: down
ge-0/1/1: down
ge-0/1/2: down
ge-0/1/3: down
ge-0/1/4: down
ge-0/1/5: down
ge-0/1/6: down
ge-0/1/7: down
ge-0/1/8: down
ge-0/1/9: down
xe-0/2/0: down
xe-0/2/1: down
xe-0/3/0: down
xe-0/3/1: down

**Comment by chidanandpujar** [comment]
Fixed https://github.com/Juniper/py-junos-eznc/pull/1216
