### ISSUE TITLE
Bug - jnpr.junos.utils.fs .tgz() method

### ISSUE THREAD

**Issue by suhaibasaeed** [Juniper/py-junos-eznc#1226]
We are coming across issues when we're trying to use the `.tgz()` method against our core routers to create a tgz file from everything inside the /var/log directory. (Device model: ptx10001-36mr - SW version: 20.4R3-S4.2-EVO)

The resulting tgz file is quite large (almost 3GB) and the RPC takes about 10 mins to execute before failing with the below error.
`jnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: None, message: error: File does not exist: /var/tmp//09-01-2023-12-00_cr1.tra_logs.tgzsqot4a
error: File fetch failed)`

Note: the random string after the tgz file extension was not in our code. i.e. `sqot4a`.

Workarounds attempted to no avail:

1. Increase netconf timeout to over 10 mins
2. Use underlying file_archive() method on the rpc object as well as increasing rpc timeout via the dev_timeout argument

Our code is below

```
import datetime
import sys
from getpass import getpass
from jnpr.junos import Device
from jnpr.junos.exception import ConnectError
from jnpr.junos.utils.fs import FS
from jnpr.junos.utils.start_shell import StartShell
from jnpr.junos.utils.scp import SCP
import ftplib

# User Prompts
hostname = input("Device hostname: ")
junos_username = input("Junos OS username: ")
junos_password = getpass("Junos OS password: ")
xtac_ftp_username = input("XTAC FTP username: ")
xtac_ftp_passwd = getpass("XTAC FTP password: ")

# Get today's date
now = datetime.datetime.now()

def time():
    result = ((datetime.datetime.now().strftime("%H:%M:%S")))
    return(result)

if __name__ == '__main__':
    # JUNOS Start
    try:
        with Device(host=hostname, user=junos_username, passwd=junos_password, port=22) as dev:
            rsi_file_name = (now.strftime("%d-%m-%Y-%H-%M") +  "_" + dev.hostname + "_rsi.txt")
            logs_file_name = (now.strftime("%d-%m-%Y-%H-%M") + "_" + dev.hostname + "_logs.tgz")
            # Timeout increased from 30s to 60s for some LNS
            dev.timeout = 60
            print("%s Connected to the device." % time())
            try:
                print("%s Compressing Logs..." % time())
                fileSystem = FS(dev)
                fileSystem.tgz(from_path = "/var/log/*", tgz_path = "/var/tmp/" + logs_file_name)
            except Exception as err:
                print (err)
                sys.exit(1)
```

**Comment by chidanandpujar** [comment]
Hi @suhaibasaeed 
   Thanks, 
   I am trying to replicate the issue .

Thanks

**Comment by chidanandpujar** [comment]
Hi @suhaibasaeed 
    Thanks,
    filesystem.tgz calls the RPC file_archive .
        rsp = self._dev.rpc.file_archive(
            compress=True, source=from_path, destination=tgz_path
        )

    Could you please try to run the file archive command and  RPC on the device and share the results .

file archive source /var/log/ destination /var/tmp/08-11-2023-14-55_10.53.102.xyz_logs.tgz compress

    <rpc>
        <file-archive>
                <compress/>
                <destination>/var/tmp/08-11-2023-14-55_10.53.102.xyz_logs.tgz</destination>
                <source>/var/log/</source>
        </file-archive>
    </rpc>


file archive source /var/log/ destination /var/tmp/08-11-2023-14-55_10.53.102_xyz_logs.tgz compress | display xml rpc 
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/21.2R0/junos">
    <rpc>
        <file-archive>
                <compress/>
                <destination>/var/tmp/08-11-2023-14-55_10.53.102.xyz_logs.tgz</destination>
                <source>/var/log/</source>
        </file-archive>
    </rpc>
    <cli>
        <banner></banner>
    </cli>
</rpc-reply>

    

file archive source /var/log/ destination /var/tmp/08-11-2023-14-55_10.53.102.xyz_logs.tgz compress   
tar: Removing leading '/' from member names

/.mount: write failed, filesystem is full
cp: /var/tmp/08-11-2023-14-55_10.53.102.xyz_logs.tgz: No space left on device
error: put-file failed
error: could not send local copy of file

Thanks

**Comment by chidanandpujar** [comment]
Hi @suhaibasaeed 
    we are not able replicate this issue, closing this issue for now.
    Please feel free to re-open .

Thanks
