### ISSUE TITLE
EthernetSwitchingTable returns 0 items

### ISSUE THREAD

**Issue by aniljham** [Juniper/py-junos-eznc#1228]
Hi,
I am trying to use EthernetSwitchingTable op on EX3300 and EX2200 switches and always returns 0 items.
On switches like EX2300 i use ElsEthernetSwitchingTable and they work normally and return the expexted items.
any help with this table/view would be appreciated.

**Comment by ydnath** [comment]
Which version of Junos are you using on EX2200 and 3300?

**Comment by aniljham** [comment]
15.1R7-S10 on both

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by charrrr93** [comment]
Hi @aniljham , I was having the same issue and I fixed it by adding a key to the yaml file definition.
---
EthernetSwitchingTable:
    rpc: get-ethernet-switching-table-information
    args:
        detail: True
    key: mac-table-count
    item: ethernet-switching-table
    view: EthernetSwitchingView

**Comment by aniljham** [comment]
Yes I figured that the key was missing
I did try but not sure what and did not get the result I was wanting.
I will try your recommendation
Thanks for sharing
Anil jham

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dineshbaburam91** [comment]
Fixed  #1341. Hence, closed it.
