### ISSUE TITLE
cp() and install() need "routing-instance" options

### ISSUE THREAD

**Issue by bsherjnpr** [Juniper/py-junos-eznc#1246]
In order to support the Juniper management routing instance the cp() method needs to support the "routing-instance" option for a remote source.  Ex: if the source is "http://some.server/junos.image" and the customer is using the management instance this will fail since it will use the default instance and not the management instance.

"file copy" command has support for "routing-instance" today.
ER-085969 request "routing-instance" option for "request system software add" command. 

ER-085969  "request system software add" needs "routing-instance" option to use mgmt instance.
ER-085971  PYeZ support for "routing-instance" option in install() and cp() methods

Thanks

**Comment by dineshbaburam91** [comment]
Raised pull request #1249 for routing instance support in cp() API

**Comment by dineshbaburam91** [comment]
Fixed
