### ISSUE TITLE
Cannot gather facts for RE2

### ISSUE THREAD

**Issue by LukeRoberson** [Juniper/py-junos-eznc#1251]
PROBLEM Description:

I would like to get the uptime string from a VC
I make a call to a 3-member EX3400-48P virtual chassis to get facts.

I then get the master RE by looking at the 'master' key. It looks like this:
'master': 'RE2',

So far this is correct.
I then read the 'RE2' key, to get the 'up_time' key.
this fails with the error:
Exception of type KeyError occurred: 'RE2: There is no function to gather the RE2 fact'

When I look at the facts, I can confirm there's no key for RE2.
There are keys for RE0 and RE1.

If I test this on another virtual-chassis where RE0 or RE1 is the master, this works perfectly.

**Comment by LukeRoberson** [comment]
I have confirmed this happens in both 2.6.6 and 2.6.7

**Comment by chidanandpujar** [comment]
@LukeRoberson 
 Thanks ,
 get facts data : last reboot reason and uptime is for only Master device REs of VC and not for the line cards /members .
could you please share the "show chassis routing-engine " output of VC .

```
show chassis routing-engine 
Routing Engine status:
  Slot 0:
    Current state                  Master
    Temperature                 47 degrees C / 116 degrees F
    CPU temperature             47 degrees C / 116 degrees F
    DRAM                      4042 MB (4096 MB installed)
    Memory utilization          20 percent
    5 sec CPU utilization:
      User                       7 percent
      Background                 0 percent
      Kernel                     6 percent
      Interrupt                  0 percent
      Idle                      87 percent
    Model                          xxxxxx
    Serial ID                      BUILTIN
    Start time                     2023-05-26 18:36:50 PDT
    Uptime                         3 days, 12 hours, 51 minutes, 40 seconds
    Last reboot reason             0x1:power cycle/failure
    Load averages:                 1 minute   5 minute  15 minute
                                       0.38       0.41       0.39
```

Thanks & Regards
Chidanand

**Comment by chidanandpujar** [comment]
Hi @LukeRoberson ,
    I will close this issue, this is expected behavior , uptime info is available only for REs and not for fpcs .

py-junos-eznc/tests/functional# python test_get_facts.py 
{'last_reboot_reason': 'Router rebooted after a normal shutdown.',
 'mastership_state': 'backup',
 'model': 'RE-EX4400-48F',
 'status': 'OK',
 'up_time': '4 hours, 2 minutes, 52 seconds'}
{'last_reboot_reason': 'Router rebooted after a normal shutdown.',
 'mastership_state': 'master',
 'model': 'RE-EX4400-48F',
 'status': 'OK',
 'up_time': '4 hours, 32 minutes, 44 seconds'}
'4 hours, 2 minutes, 52 seconds'
'4 hours, 32 minutes, 44 seconds'


Thanks & Regards

**Comment by chidanandpujar** [comment]
Hi @LukeRoberson 
    Please test with following script and let me know the results .
```
from jnpr.junos import Device
from pprint import pprint

dev = Device(host='xx.xx.xx.xx', user='xyz', password='xyz', port=830)
dev.open()

pprint (dev.facts['RE0'])
pprint (dev.facts['RE1'])
pprint(dev.facts['RE0']['up_time'])
pprint(dev.facts['RE1']['up_time'])
```

Thanks

**Comment by LukeRoberson** [comment]
Yes, that script works.
I can see the state of VC member 0 and 1.
Thanks for your help, I understand it better now.
