### ISSUE TITLE
inspect.getargspec is deprecated and removed in Python 3.11

### ISSUE THREAD

**Issue by daemonkeeper** [Juniper/py-junos-eznc#1252]
Python 3.11 removed the inspect.getargspec function from the inspect module. This function is used in the SCP module here: https://github.com/Juniper/py-junos-eznc/blob/a106028765d791a515229d422ddfbdfed5c08e0c/lib/jnpr/junos/utils/scp.py#L46

Please replace the invokation by inspect.getfullargspec which acts as a drop-in replacement as per https://docs.python.org/3/library/inspect.html#inspect.getfullargspec.

Since getfullargspec is available since the early days of Python 3.x (and definitely available in Python 3.5 which you name as minimum version) you probably don't need to bump your python dependencies unless you plan to support Python 2. 

edit: the same probably applies to https://github.com/Juniper/py-junos-eznc/blob/a106028765d791a515229d422ddfbdfed5c08e0c/lib/jnpr/junos/device.py#L49 

However there, it looks, you have remainders of Python 2 compatibility code in place which can probably stay around.

**Comment by ludal35** [comment]
Hello - same problem occurs with while copying files:

```
File "/usr/local/lib/python3.11/dist-packages/jnpr/junos/utils/sw.py", line 936, in install
    copy_ok = self.safe_copy(
              ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jnpr/junos/utils/sw.py", line 671, in safe_copy
    self.put(package, remote_path=remote_path, progress=progress)
  File "/usr/local/lib/python3.11/dist-packages/jnpr/junos/utils/sw.py", line 203, in put
    with SCP(self._dev, progress=progress) as scp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jnpr/junos/utils/scp.py", line 46, in __init__
    spec = inspect.getargspec(self._user_progress)
           ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```

See https://github.com/Juniper/py-junos-eznc/blob/53054ea685951f1726c521305a4eb87e21839f91/lib/jnpr/junos/utils/scp.py#L46

**Comment by dineshbaburam91** [comment]
pyEZ support python3.10 and above
