### ISSUE TITLE
wait for boot options?

### ISSUE THREAD

**Issue by akielaries** [Juniper/py-junos-eznc#1256]
I am looking to use pyez to configure some junos devices I have in an EVE-NG topology but am struggling on handing the errors/exceptions that appear when trying to connect to a device that is booting. Does pyez feature any methods to handle devices that are booting before configuring them?

**Comment by chidanandpujar** [comment]
Hi @akielaries 
    Thanks,
    Please check the option "Connect to a Device Using a Serial Console Connection"

```
import sys
from getpass import getpass
from jnpr.junos import Device
from jnpr.junos.utils.config import Config

junos_username = input("Junos OS username: ")
junos_password = getpass("Junos OS password: ")

try:
    with Device(mode='serial', port='port', user=junos_username, passwd=junos_password) as dev:
        print (dev.facts)
        cu = Config(dev)
        cu.lock()
        cu.load(path='/tmp/config_mx.conf')
        cu.commit()
        cu.unlock()

except Exception as err:
    print (err)
    sys.exit(1)
```
https://www.juniper.net/documentation/us/en/software/junos-pyez/junos-pyez-developer/topics/topic-map/junos-pyez-connection-methods.html

Please feel to re-open the issue  ,if the above mentioned solution does not solve it .
Thanks
