### ISSUE TITLE
configuration Diff cannot be fetched in json format 

### ISSUE THREAD

**Issue by shreeraj2698** [Juniper/py-junos-eznc#1259]
issue with pyEZ where I am trying to fetch a json diff between the candidate config and active config ... by default the diff function dosent even allow the format you want to be specified and only outputs the diff in patch format... but when I digged deep in the actual code i found out it was sending the format="text" as a hard coding so just for testing i changed the format to xml and it did work. it gave me the diff in xml format but however i changed it to format="json" its giving me an error index out of bounds. 
Here are the links to the mentioned code:

https://github.com/Juniper/py-junos-eznc/blob/e19a7683be1da67140798987ac42e8c82041c393/lib/jnpr/junos/utils/config.py#L239

https://www.juniper.net/documentation/us/en/software/junos-pyez/junos-pyez-developer/topics/task/junos-pyez-program-configuration-comparing.html

my juniper mail is ssuryavanshi@juniper.net

**Comment by chidanandpujar** [comment]
Hi @shreeraj2698 
    All the 3 formats returns same output in text format   with options compare , rollback  and this is Junos behavior ,
   As per JUNOS behavior the option format=text  looks to be fine with pdiff  method . 
   
```
<rpc>
<get-configuration compare="rollback" rollback="5" format="text"/>
</rpc><rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/24.1I20230906_0836_chipujar/junos">
<configuration-information>
<configuration-output>
[edit system syslog]
+    file test {
+        any any;
+    }
</configuration-output>
</configuration-information>

</rpc-reply>
]]>]]>
<rpc>
<get-configuration compare="rollback" rollback="5" format="json"/>
</rpc>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/24.1I20230906_0836_chipujar/junos">
<configuration-information>
<configuration-output>
[edit system syslog]
+    file test {
+        any any;
+    }
</configuration-output>
</configuration-information>
</rpc-reply>
]]>]]>

<rpc>
<get-configuration compare="rollback" rollback="5" format="xml"/>
</rpc>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/24.1I20230906_0836_chipujar/junos">
<configuration-information>
<configuration-output>
[edit system syslog]
+    file test {
+        any any;
+    }
</configuration-output>
</configuration-information>
</rpc-reply>
]]>]]>
```
Thanks

**Comment by shreeraj2698** [comment]
Yes according to documentation its correct, in the documentation it mentions that the output will be in patch format always.
I was wondering if we just allowed the user to fetch the diff in different formats, the format="xml"(I hardcoded) did gave me the diff in XML format instead of patch format but only in the case of format="json" it failed. If there are no plans of this feature then its all ok. Thank you

**Comment by chidanandpujar** [comment]
Hi @shreeraj2698 
     Thanks,
      Yeah, we rely on JUNOS RPC response , so feel free to report JUNOS PR for this enhancement .
     Closing this issue as per JUNOS documentation .
     https://www.juniper.net/documentation/us/en/software/junos/junos-xml-protocol/topics/ref/tag/junos-xml-protocol-get-configuration.html

Thanks ,
