### ISSUE TITLE
rpc.get_trace() returning pipe element

### ISSUE THREAD

**Issue by ipmonk** [Juniper/py-junos-eznc#1261]
expectation is the traces will be shown, instead a pipe tag is returned.

```
>>> foo = d.rpc.get_trace(node='re1', application='rpdagent')
>>> etree.tostring(foo)
b'<pipe>\n</pipe>'
```

Model: ptx10008
Junos: 23.3R1-202308210311.0-EVO
Yocto: 3.0.2
Linux Kernel: 5.2.60-yocto-standard-g120e65b
JUNOS-EVO OS 64-bit [junos-evo-install-ptx-x86-64-23.3R1-202308210311.0-EVO]

**Comment by dineshbaburam91** [comment]
Junos Evolved Platform issue not PyEZ issue.

Internal PR 1843247 was raised and it was fixed in the 25.1R1 release. Hence, closing the ticket.
