### ISSUE TITLE
StartShell not Honoring Port Setting from Device Setup

### ISSUE THREAD

**Issue by HammaBamma** [Juniper/py-junos-eznc#1266]
So I don't use default port 22 for my SSH connections. Let's say I use 47332 (total example).. 

The Script I run will connect to the router fine, but when I try and run StartShell(dev)
`paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on ` and my Router's Ipv4 and IPv6 address are listed.. 

Every other function I throw at this amazing Python Package works great, but I now need to get a little more information from the box so I want to run a show command and just parse that data on my own. Not sure if anyone else has seen this isssue.

Thanks in Advance.

-Con

**Comment by chidanandpujar** [comment]
Hi @HammaBamma 
    Thanks,
    Simillar issue was reported earlier , fix has been merged .
    Could you please re-check your use case with latest PyEZ dev or the fix provided below and share the results.
https://github.com/Juniper/py-junos-eznc/pull/1241

Thanks

**Comment by chidanandpujar** [comment]
Hi @HammaBamma 
    Thanks,
     Could you please try with following script and let me know  the fix works or not 

from jnpr.junos import Device
from jnpr.junos.utils.start_shell import StartShell
host_ip = "10.52.133.204"
port = "8011"
username = "xyz"
password = "xyz"
dev = Device(host=host_ip, port=port, user=username, password=password)
dev.open()
print(dev.facts)
ss = StartShell(dev)
ss.open()
ss.run('cli -c "ping 10.52.135.127 count 5 rapid”')

Thanks

**Comment by HammaBamma** [comment]
I will test this in the morning, sorry for my delay in getting back. My test system is currently offline as that equipment was getting re-racked into a travel case. 

Will be spun back up in the morning and I can retest..

-Bamma

**Comment by HammaBamma** [comment]
I edited the script below for my parameters in my environment. 

I don’t have a development environment setup for testing dev branch builds of this package.. The script you provided still has the same problem of being hard coded to attach itself to port 22 instead of the port assigned by Device. 

It looks like you merged your fix into master back in April but there hasn't been a release since Feb. 

{'2RE': False, 'HOME': '/var/home/creilly', 'RE0': {'mastership_state': 'master', 'status': 'OK', 'model': 'RE-S-1600x8', 'last_reboot_reason': '0x1:power cycle/failure', 'up_time': '19 hours, 54 minutes, 37 seconds'}, 'RE1': None, 'RE_hw_mi': False, 'current_re': ['master', 'node', 'fwdd', 'member', 'pfem', 're0'], 'domain': redacted.com', 'fqdn': ‘RtrA.redacted.com', 'hostname': 'RtrA', 'hostname_info': {'re0': 'RtrA'}, 'ifd_style': 'CLASSIC', 'junos_info': {'re0': {'text': '23.2R1.13', 'object': junos.version_info(major=(23, 2), type=R, minor=1, build=13)}}, 'master': 'RE0', 'model': 'MX204', 'model_info': {'re0': 'MX204'}, 'personality': 'MX', 're_info': {'default': {'0': {'mastership_state': 'master', 'status': 'OK', 'model': 'RE-S-1600x8', 'last_reboot_reason': '0x1:power cycle/failure'}, 'default': {'mastership_state': 'master', 'status': 'OK', 'model': 'RE-S-1600x8', 'last_reboot_reason': '0x1:power cycle/failure'}}}, 're_master': {'default': '0'}, 'serialnumber': 'BW489', 'srx_cluster': None, 'srx_cluster_id': None, 'srx_cluster_redundancy_group': None, 'switch_style': 'BRIDGE_DOMAIN', 'vc_capable': False, 'vc_fabric': None, 'vc_master': None, 'vc_mode': None, 'version': '23.2R1.13', 'version_RE0': '23.2R1.13', 'version_RE1': None, 'version_info': junos.version_info(major=(23, 2), type=R, minor=1, build=13), 'virtual': False}
Traceback (most recent call last):
  File "/srv/zabbix_juniper_sender/test.py", line 11, in <module>
    ss.open()
  File "/usr/local/lib/python3.10/dist-packages/jnpr/junos/utils/start_shell.py", line 125, in open
    self._client = open_ssh_client(dev=self._nc)
  File "/usr/local/lib/python3.10/dist-packages/jnpr/junos/utils/ssh_client.py", line 40, in open_ssh_client
    ssh_client.connect(
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 409, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on IPv6::Address or IPv4.Address

**Comment by chidanandpujar** [comment]
Hi @HammaBamma 
     Thanks,
     Please install the master code and verify the fix .

To install the latest MASTER code
pip install git+https://github.com/Juniper/py-junos-eznc.git

Thanks

**Comment by HammaBamma** [comment]
That fixed the issue..

Thank you for the instructions!

-Bamma

**Comment by chidanandpujar** [comment]
Hi @HammaBamma 
   Thanks for the verification ,
   Fix is available in master and will be in next PyEZ release .

Thanks
