### ISSUE TITLE
Unable to install PyEZ in MACOS ventura 13.6.1

### ISSUE THREAD

**Issue by dhotresumit** [Juniper/py-junos-eznc#1280]
I am getting an error while installing PyEZ module on Mac OS 13.6.1 and Python 3.12.0
>>> from jnpr.junos import Device
Traceback (most recent call last):
File “<stdin>”, line 1, in <module>
ModuleNotFoundError:

Please help me to get started.

**Comment by dhotresumit** [comment]
Hi Team, any update on this?

**Comment by dineshbaburam91** [comment]
PyEZ support python 3.10 and above version
