### ISSUE TITLE
Address docker container creation issues.

### ISSUE THREAD

**Issue by ydnath** [Juniper/py-junos-eznc#1317]
docker build --pull --rm -f "Dockerfile" -t pyjunoseznc:latest "." 
[+] Building 125.1s (12/13)                                                           docker:default
 => [internal] load .dockerignore                                                               0.1s
 => => transferring context: 187B                                                               0.0s
 => [internal] load build definition from Dockerfile                                            0.2s
 => => transferring dockerfile: 895B                                                            0.0s
 => [internal] load metadata for docker.io/library/alpine:3.12                                  5.3s
 => [1/9] FROM docker.io/library/alpine:3.12@sha256:c75ac27b49326926b803b9ed43bf088bc220d22556  1.4s
 => => resolve docker.io/library/alpine:3.12@sha256:c75ac27b49326926b803b9ed43bf088bc220d22556  0.1s
 => => sha256:c75ac27b49326926b803b9ed43bf088bc220d22556de1bc5f72d742c91398f69 1.64kB / 1.64kB  0.0s
 => => sha256:cb64bbe7fa613666c234e1090e91427314ee18ec6420e9426cf4e7f314056813 528B / 528B      0.0s
 => => sha256:24c8ece58a1aa807c0d8ea121f91cee2efba99624d0a8aed732155fb31f28993 1.47kB / 1.47kB  0.0s
 => => sha256:1b7ca6aea1ddfe716f3694edb811ab35114db9e93f3ce38d7dab6b4d9270cb0c 2.81MB / 2.81MB  1.1s
 => => extracting sha256:1b7ca6aea1ddfe716f3694edb811ab35114db9e93f3ce38d7dab6b4d9270cb0c       0.1s
 => [internal] load build context                                                               0.1s
 => => transferring context: 718.38kB                                                           0.0s
 => [2/9] WORKDIR /source                                                                       0.1s
 => [3/9] ADD setup.* ./                                                                        0.2s
 => [4/9] ADD versioneer.py .                                                                   0.1s
 => [5/9] ADD requirements.txt .                                                                0.1s
 => [6/9] ADD lib lib                                                                           0.2s
 => [7/9] ADD entrypoint.sh /usr/local/bin/.                                                    0.1s
 => ERROR [8/9] RUN apk add --no-cache build-base python3-dev py-lxml     libxslt-dev libxml  117.1s
------                                                                                               
 > [8/9] RUN apk add --no-cache build-base python3-dev py-lxml     libxslt-dev libxml2-dev libffi-dev openssl-dev curl     ca-certificates py3-pip bash     && pip install -U pip     && pip install -r requirements.txt     && apk del -r --purge gcc make g++     && ln -s /usr/bin/python3 /usr/bin/python     && pip install .     && rm -rf /source/*     && chmod +x /usr/local/bin/entrypoint.sh:            
0.400 fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz                   
0.886 fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
1.995 (1/78) Upgrading libcrypto1.1 (1.1.1n-r0 -> 1.1.1o-r0)
2.846 (2/78) Upgrading libssl1.1 (1.1.1n-r0 -> 1.1.1o-r0)
3.022 (3/78) Upgrading zlib (1.2.12-r0 -> 1.2.12-r3)
3.076 (4/78) Installing ncurses-terminfo-base (6.2_p20200523-r1)
3.116 (5/78) Installing ncurses-libs (6.2_p20200523-r1)
3.262 (6/78) Installing readline (8.0.4-r0)
3.362 (7/78) Installing bash (5.0.17-r0)
3.625 Executing bash-5.0.17-r0.post-install
3.627 (8/78) Installing libgcc (9.3.0-r2)
3.667 (9/78) Installing libstdc++ (9.3.0-r2)
4.194 (10/78) Installing binutils (2.34-r2)
5.744 (11/78) Installing libmagic (5.38-r0)
6.002 (12/78) Installing file (5.38-r0)
6.031 (13/78) Installing gmp (6.2.1-r1)
6.200 (14/78) Installing isl (0.18-r0)
6.621 (15/78) Installing libgomp (9.3.0-r2)
6.702 (16/78) Installing libatomic (9.3.0-r2)
6.731 (17/78) Installing libgphobos (9.3.0-r2)
7.886 (18/78) Installing mpfr4 (4.0.2-r4)
8.028 (19/78) Installing mpc1 (1.1.0-r1)
8.075 (20/78) Installing gcc (9.3.0-r2)
33.37 (21/78) Installing musl-dev (1.1.24-r10)
35.48 (22/78) Installing libc-dev (0.7.2-r3)
35.51 (23/78) Installing g++ (9.3.0-r2)
47.88 (24/78) Installing make (4.3-r0)
47.99 (25/78) Installing fortify-headers (1.1-r0)
48.05 (26/78) Installing patch (2.7.6-r7)
48.25 (27/78) Installing build-base (0.5-r2)
48.27 (28/78) Installing ca-certificates (20220614-r0)
48.39 (29/78) Installing nghttp2-libs (1.41.0-r0)
48.45 (30/78) Installing libcurl (7.79.1-r1)
48.61 (31/78) Installing curl (7.79.1-r1)
48.73 (32/78) Installing linux-headers (5.4.5-r1)
49.63 (33/78) Installing libffi (3.3-r2)
49.66 (34/78) Installing pkgconf (1.7.2-r0)
49.71 (35/78) Installing libffi-dev (3.3-r2)
49.79 (36/78) Installing zlib-dev (1.2.12-r3)
49.84 (37/78) Installing xz-libs (5.2.5-r1)
49.91 (38/78) Installing xz-dev (5.2.5-r1)
50.02 (39/78) Installing libxml2 (2.9.14-r0)
50.38 (40/78) Installing libxml2-dev (2.9.14-r0)
52.05 (41/78) Installing libgpg-error (1.37-r0)
52.11 (42/78) Installing libgcrypt (1.8.8-r1)
52.40 (43/78) Installing libxslt (1.1.35-r0)
52.51 (44/78) Installing libxslt-dev (1.1.35-r0)
52.67 (45/78) Installing openssl-dev (1.1.1o-r0)
52.86 (46/78) Installing py3-lxml (4.5.1-r1)
54.25 (47/78) Installing libbz2 (1.0.8-r1)
54.29 (48/78) Installing expat (2.2.10-r4)
54.37 (49/78) Installing gdbm (1.13-r1)
54.43 (50/78) Installing sqlite-libs (3.32.1-r1)
54.76 (51/78) Installing python3 (3.8.10-r0)
63.33 (52/78) Installing py3-appdirs (1.4.4-r1)
63.37 (53/78) Installing py3-ordered-set (4.0.1-r0)
63.40 (54/78) Installing py3-parsing (2.4.7-r0)
63.59 (55/78) Installing py3-six (1.15.0-r0)
63.63 (56/78) Installing py3-packaging (20.4-r0)
63.69 (57/78) Installing py3-setuptools (47.0.0-r0)
63.97 (58/78) Installing py3-chardet (3.0.4-r4)
64.15 (59/78) Installing py3-idna (2.9-r0)
64.25 (60/78) Installing py3-certifi (2020.4.5.1-r0)
64.38 (61/78) Installing py3-urllib3 (1.25.9-r0)
64.56 (62/78) Installing py3-requests (2.23.0-r0)
64.67 (63/78) Installing py3-msgpack (1.0.0-r0)
64.74 (64/78) Installing py3-lockfile (0.12.2-r3)
64.78 (65/78) Installing py3-cachecontrol (0.12.6-r0)
64.82 (66/78) Installing py3-colorama (0.4.3-r0)
64.86 (67/78) Installing py3-distlib (0.3.0-r0)
65.21 (68/78) Installing py3-distro (1.5.0-r1)
65.25 (69/78) Installing py3-webencodings (0.5.1-r3)
65.28 (70/78) Installing py3-html5lib (1.0.1-r4)
65.48 (71/78) Installing py3-pytoml (0.1.21-r0)
65.51 (72/78) Installing py3-pep517 (0.8.2-r0)
65.56 (73/78) Installing py3-progress (1.5-r0)
65.59 (74/78) Installing py3-toml (0.10.1-r0)
65.64 (75/78) Installing py3-retrying (1.3.3-r0)
65.67 (76/78) Installing py3-contextlib2 (0.6.0-r0)
65.70 (77/78) Installing py3-pip (20.1.1-r0)
66.22 (78/78) Installing python3-dev (3.8.10-r0)
83.25 Executing busybox-1.31.1-r22.trigger
83.26 Executing ca-certificates-20220614-r0.trigger
83.30 OK: 338 MiB in 89 packages
84.30 Collecting pip
84.38   Downloading pip-24.2-py3-none-any.whl (1.8 MB)
85.75 Installing collected packages: pip
85.75   Attempting uninstall: pip
85.75     Found existing installation: pip 20.1.1
85.75     Uninstalling pip-20.1.1:
85.77       Successfully uninstalled pip-20.1.1
87.13 Successfully installed pip-24.2
87.97 Requirement already satisfied: lxml>=3.2.4 in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (4.5.1)
88.08 Collecting ncclient>=0.6.15 (from -r requirements.txt (line 3))
88.16   Downloading ncclient-0.6.15.tar.gz (634 kB)
88.60      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 634.9/634.9 kB 1.5 MB/s eta 0:00:00
88.71   Installing build dependencies: started
93.01   Installing build dependencies: finished with status 'done'
93.01   Getting requirements to build wheel: started
93.33   Getting requirements to build wheel: finished with status 'done'
93.33   Preparing metadata (pyproject.toml): started
93.66   Preparing metadata (pyproject.toml): finished with status 'done'
93.73 Collecting scp>=0.7.0 (from -r requirements.txt (line 4))
93.76   Downloading scp-0.15.0-py2.py3-none-any.whl.metadata (4.3 kB)
93.84 Collecting jinja2>=2.7.1 (from -r requirements.txt (line 5))
93.87   Downloading jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
94.02 Collecting PyYAML>=5.1 (from -r requirements.txt (line 6))
94.05   Downloading PyYAML-6.0.1-cp38-cp38-musllinux_1_1_x86_64.whl.metadata (2.1 kB)
94.06 Requirement already satisfied: six in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (1.15.0)
94.11 Collecting pyserial (from -r requirements.txt (line 8))
94.13   Downloading pyserial-3.5-py2.py3-none-any.whl.metadata (1.6 kB)
94.19 Collecting yamlordereddictloader (from -r requirements.txt (line 9))
94.22   Downloading yamlordereddictloader-0.4.2-py3-none-any.whl.metadata (3.8 kB)
94.24 Requirement already satisfied: pyparsing in /usr/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (2.4.7)
94.33 Collecting transitions (from -r requirements.txt (line 11))
94.36   Downloading transitions-0.9.1-py2.py3-none-any.whl.metadata (89 kB)
94.46 Requirement already satisfied: setuptools>0.6 in /usr/lib/python3.8/site-packages (from ncclient>=0.6.15->-r requirements.txt (line 3)) (47.0.0)
94.62 Collecting paramiko>=1.15.0 (from ncclient>=0.6.15->-r requirements.txt (line 3))
94.64   Downloading paramiko-3.4.0-py3-none-any.whl.metadata (4.4 kB)
94.83 Collecting MarkupSafe>=2.0 (from jinja2>=2.7.1->-r requirements.txt (line 5))
94.85   Downloading MarkupSafe-2.1.5-cp38-cp38-musllinux_1_1_x86_64.whl.metadata (3.0 kB)
95.00 Collecting bcrypt>=3.2 (from paramiko>=1.15.0->ncclient>=0.6.15->-r requirements.txt (line 3))
95.03   Downloading bcrypt-4.2.0-cp37-abi3-musllinux_1_1_x86_64.whl.metadata (9.6 kB)
95.63 Collecting cryptography>=3.3 (from paramiko>=1.15.0->ncclient>=0.6.15->-r requirements.txt (line 3))
95.66   Downloading cryptography-43.0.0.tar.gz (686 kB)
96.12      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 686.9/686.9 kB 1.6 MB/s eta 0:00:00
96.27   Installing build dependencies: started
116.6   Installing build dependencies: finished with status 'done'
116.6   Getting requirements to build wheel: started
116.7   Getting requirements to build wheel: finished with status 'done'
116.7   Preparing metadata (pyproject.toml): started
116.7   Preparing metadata (pyproject.toml): finished with status 'error'
116.8   error: subprocess-exited-with-error
116.8   
116.8   × Preparing metadata (pyproject.toml) did not run successfully.
116.8   │ exit code: 1
116.8   ╰─> [6 lines of output]
116.8       
116.8       Cargo, the Rust package manager, is not installed or is not on PATH.
116.8       This package requires Rust and Cargo to compile extensions. Install it through
116.8       the system's package manager or via https://rustup.rs/
116.8       
116.8       Checking for Rust toolchain....
116.8       [end of output]
116.8   
116.8   note: This error originates from a subprocess, and is likely not a problem with pip.
116.8 error: metadata-generation-failed
116.8 
116.8 × Encountered error while generating package metadata.
116.8 ╰─> See above for output.
116.8 
116.8 note: This is an issue with the package mentioned above, not pip.
116.8 hint: See above for details.
------
Dockerfile:16
--------------------
  15 |     ## Install dependancies and PyEZ
  16 | >>> RUN apk add --no-cache build-base python3-dev py-lxml \
  17 | >>>     libxslt-dev libxml2-dev libffi-dev openssl-dev curl \
  18 | >>>     ca-certificates py3-pip bash \
  19 | >>>     && pip install -U pip \
  20 | >>>     && pip install -r requirements.txt \
  21 | >>>     && apk del -r --purge gcc make g++ \
  22 | >>>     && ln -s /usr/bin/python3 /usr/bin/python \
  23 | >>>     && pip install . \
  24 | >>>     && rm -rf /source/* \
  25 | >>>     && chmod +x /usr/local/bin/entrypoint.sh
  26 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apk add --no-cache build-base python3-dev py-lxml     libxslt-dev libxml2-dev libffi-dev openssl-dev curl     ca-certificates py3-pip bash     && pip install -U pip     && pip install -r requirements.txt     && apk del -r --purge gcc make g++     && ln -s /usr/bin/python3 /usr/bin/python     && pip install .     && rm -rf /source/*     && chmod +x /usr/local/bin/entrypoint.sh" did not complete successfully: exit code: 1

**Comment by dineshbaburam91** [comment]
The issue was resolved. Hence, closed the issue.

### TESTCASE 1: running interpreter
 
 py-junos-eznc % docker run -it juniper/pyez python3  
Python 3.12.5 (main, Aug  7 2024, 19:15:55) [GCC 13.2.1 20240309] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from jnpr.junos import Device
>>> dev = Device('x.x.x.x', user='root',passwd='xxxx', port=22)
>>> dev.open()
Device(x.x.x.x)
>>> dev.facts
{'2RE': True,
'HOME': '/root',
 
 
### Testcase 2: Execute python script from outside the container
 
 py-junos-eznc % docker run -it -v $PWD:/scripts juniper/pyez python test.py            
{'2RE': True, 'HOME': '/root', 'RE0': {'mastership_state': 'master', 'status': 'OK', 'model': 'RE-VMX',
 
 
### Testcase 3: Inside the container
 
 py-junos-eznc % docker run -it -v $PWD:/scripts juniper/pyez                           
4ee3962901f8:/scripts# python test.py
{'2RE': True, 'HOME': '/root', 'RE0': {'mastership_state': 'master', 'status': 'OK', 'model': 'RE-VMX',
 
 
### Testcase 4: allias
 
 py-junos-eznc % alias pyez="docker run -it --rm -v $PWD:/scripts juniper/pyez python"
py-junos-eznc % pyez test.py                                               
{'2RE': True, 'HOME': '/root', 'RE0': {'mastership_state': 'master', 'status': 'OK', 'model': 'RE-VMX',
