### ISSUE TITLE
Bug: When using StartShell.run to run commands, commands can fail but still return that they executed successfully

### ISSUE THREAD

**Issue by jakobsen-lrz** [Juniper/py-junos-eznc#1319]
When using `StartShell.run()` to run commands on a juniper switch, some commands return success even when they are not successful.

When trying to run syntactically invalid commands, you receive `syntax error`, but `run()` still returns success. Same thing when trying to run unknown commands.

When `configure exclusive` fails because of a dirty candidate config or because it is already locked, it will still return success but not enter configuration mode.

**Comment by jakobsen-lrz** [comment]
I am currently on junos-eznc version 2.7.1

**Comment by chidanandpujar** [comment]
Hi @jakobsen-lrz,
    StartShell supports execution of shell commands on the device.

    https://www.juniper.net/documentation/us/en/software/junos-pyez/junos-pyez-developer/topics/task/junos-pyez-program-shell-accessing.html

   could you please share the commands and steps to replicate this issue.

Thanks 
Chidanand

**Comment by jakobsen-lrz** [comment]
Sorry i cant seem to replicate the error.

**Comment by chidanandpujar** [comment]
Hi @jakobsen-lrz,
   We will close this issue as not reproducible as of now.
    Please feel to report/re-open a issue if issue persists.

Thanks
Chidanand
