### ISSUE TITLE
fault on attempting to pull results in json format from switches in virtual chassis. 

### ISSUE THREAD

**Issue by baldgeek** [Juniper/py-junos-eznc#1325]
Error dump:

```
   phy_int=decom_switch.rpc.get_interface_information({'format':'json'},interface_name=decom_int['name'],terse=True)
  File "/usr/local/lib/python3.9/site-packages/jnpr/junos/rpcmeta.py", line 363, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/usr/local/lib/python3.9/site-packages/jnpr/junos/decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jnpr/junos/decorators.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jnpr/junos/device.py", line 875, in execute
    or (ver_info.major[0] == 14 and ver_info.major[1] >= 2)
```

Code in question:

            if (
                ver_info
                and ver_info.major[0] >= 15
                or (ver_info.major[0] == 14 and ver_info.major[1] >= 2)
            ):

I believe that the fix is likely simply putting () around the two pieces of the "or", so something like this:

            if (
                ver_info
                and (ver_info.major[0] >= 15
                or (ver_info.major[0] == 14 and ver_info.major[1] >= 2))
            ):

However the bigger issue is that in my testing for any EX switch in a virtual chassis the version (as seen from .facts) gets set to None. This prevents the ability to do JSON output even though all the switches are running version 20 or better.  I have not spent time figuring out why that is the case. I can open a separate issue for this if you prefer as well.

**Comment by baldgeek** [comment]
Sorry I realized I forgot the last line of the error. it is:
  
`  AttributeError: 'NoneType' object has no attribute 'major'
`

Full report in one place:

```
   phy_int=decom_switch.rpc.get_interface_information({'format':'json'},interface_name=decom_int['name'],terse=True)
  File "/usr/local/lib/python3.9/site-packages/jnpr/junos/rpcmeta.py", line 363, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/usr/local/lib/python3.9/site-packages/jnpr/junos/decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jnpr/junos/decorators.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jnpr/junos/device.py", line 875, in execute
    or (ver_info.major[0] == 14 and ver_info.major[1] >= 2)
  AttributeError: 'NoneType' object has no attribute 'major'

```

**Comment by dineshbaburam91** [comment]
@baldgeek 
Could you share the specific EX model name and version where this issue occurs? Your input will be extremely valuable in helping us address this issue effectively.

**Comment by baldgeek** [comment]
Virtual chassis that show this issue:
EX3400-48T and code version 21.4R3-S6
EX4400-48T and code version 22.2R3-S2
EX4100-48P and code version 22.4R3-S2

I also have two VC of ex3400-48T running 21.4R3-S1 that do NOT show this problem. I only checked these 5 virtual chassis.

**Comment by dineshbaburam91** [comment]
@baldgeek Merged the fix. Kindly test your setup and close the issue.

**Comment by dineshbaburam91** [comment]
@baldgeek Did you get the chance to validate the use cases using latest PyEZ code.

**Comment by dineshbaburam91** [comment]
Fixed and merged. Hence closing the issue.

**Comment by baldgeek** [comment]
Sorry I wasn't able to test. Thanks for resolving.
