### ISSUE TITLE
dev.cli("show system core-dumps") seems broken

### ISSUE THREAD

**Issue by josephlai2020** [Juniper/py-junos-eznc#299]
## Junos : only tried 12.1X44-D10 and D40

> > > print dev.cli("show system core-dumps")
> > > invalid command: show system core-dumps
## PyEZ

> > > print dev.cli("show system core-dumps")

/var/crash/_core_: No such file or directory
## CLI:

root@EMX-960-re0> show system core-dumps 
/var/crash/_core_: No such file or directory
/var/tmp/_core_: No such file or directory
/var/tmp/pics/_core_: No such file or directory
/var/crash/kernel.*: No such file or directory

Please fix it.

**Comment by cuneytm** [comment]
Hi Shermdog,

I've just started to learn pyez and have a problem about coredump. (Sorry if its a silly problem. )

i'm trying to get coredumpfile count with these code lines below but it does not work

ifcd=get-system-core-dumps()
filecountcheck=ifcd.findtext('directory name=""/total-files')

When i look at the xml format on cli, directory name's empty and i'm getting keyerror.  Is there any other way to get that value?

cuneyt@CUNEYT-PYEZ> show system core-dumps | display xml        
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/12.1X47/junos">
    <directory-list root-path="/var/crash/*core*" junos:seconds="1440584179" junos:style="verbose">
        <output>
            /var/crash/*core*: No such file or directory
        </output>
        <directory name="">
....
        <total-files>4</total-files>

**Comment by vnitinv** [comment]
@cuneytm Looks like you are having issue with the box not PyEZ. Do share the detail of you device.

**Comment by cuneytm** [comment]
["'version': '12.1X47-D20.7'"]
CHASIS MODEL = FIREFLY-PERIMETER

**Comment by sdndude** [comment]
@cuneytm 
Your code needs tweaking.  It should be:

```
ifcd=dev.rpc.get_system_core_dumps()
filecountcheck=ifcd.findtext('directory/total-files')

```
I haven't checked if the findtext is absolutely correct but it should be fairly close.  

 (replace **dev** in the first line with whatever your device object name is)

**Comment by cuneytm** [comment]
not putting dev was a stupid mistake, i dont understand how i did it. Anyway it works now, thanks my friend.

>>> dev.open()
Device(10.34.40.211)
>>> ifcd=dev.rpc.get_system_core_dumps()
>>> filecountcheck=ifcd.findtext('directory/total-files')
>>> print filecountcheck

4

**Comment by sdndude** [comment]
Sure thing.  In the future, if you post your questions to the community you will probably get a lot faster response and there are a lot of knowledgeable people on there wanting to help.

https://groups.google.com/forum/#!forum/junos-python-ez
