### ISSUE TITLE
Robust issue when connecting device.

### ISSUE THREAD

**Issue by mfrank-wang** [Juniper/py-junos-eznc#313]
While trying to connect a device, if the serial number of the chassis/midplane is empty, the following error reported.

>>> dev =Device(host=host,user=user,password=pwd)
>>> dev.open()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "c:\Python27\lib\site-packages\junos_eznc-1.0.2-py2.7.egg\jnpr\junos\devi
ce.py", line 439, in open
self.facts_refresh()
File "c:\Python27\lib\site-packages\junos_eznc-1.0.2-py2.7.egg\jnpr\junos\devi
ce.py", line 660, in facts_refresh
gather(self, self._facts)
File "c:\Python27\lib\site-packages\junos_eznc-1.0.2-py2.7.egg\jnpr\junos\fact
s\chassis.py", line 52, in facts_chassis
'chassis-module[name="Backplane"]/serial-number')[0].text
IndexError: list index out of range

For some old device like M10, the serial number of chassis/midplane might be empty.  See below a snippet from the show result.
=============================
Hardware inventory:
Item Version Part number Serial number Description
Chassis
Midplane
Routing Engine REV 07 740-007603 P11075101xxx RE-3.0

**Comment by mfrank-wang** [comment]
Yes, vnitinv described the issue. the workaround works for me.

**Comment by vnitinv** [comment]
@mfrank-wang As you are aware this issue is mainly related to very specific old version of  M10 device.
I am closing this for now. Can anytime reopen if this issue is replicable on other devices.
