### ISSUE TITLE
Unable to connect to Junos devices with certain ciphers/macs configured.

### ISSUE THREAD

**Issue by milazzom** [Juniper/py-junos-eznc#336]
Using the following SSH configuration, PyEZ is unable to connect to the Junos device remotely.

ssh {
    inactive: root-login deny;
    no-tcp-forwarding;
    protocol-version v2;
    max-sessions-per-connection 1;
    ciphers [ aes256-ctr aes256-cbc aes192-ctr aes192-cbc aes128-ctr aes128-cbc ];
    macs [ hmac-sha2-512 hmac-sha2-256 hmac-sha1 hmac-sha1-96 ];
    key-exchange [ ecdh-sha2-nistp521 ecdh-sha2-nistp384 ecdh-sha2-nistp256 dh-group14-sha1 group-exchange-sha2 ];
    client-alive-count-max 3;
    client-alive-interval 10;
    connection-limit 10;
    rate-limit 4;
}
netconf {
    ssh;
}

The following error message is displayed in the logs:

Feb  2 14:50:34  B6-C1-MX80 sshd[13250]: fatal: Unable to negotiate a key exchange method [preauth]

**Comment by shermdog** [comment]
This appears to be related to the underlying version of Paramiko.  Will try to identify the fixed/updated version and set that as minimum required.
