### ISSUE TITLE
Junos commit errors reports only first rpc-error

### ISSUE THREAD

**Issue by jeremyschulman** [Juniper/py-junos-eznc#338]
In the case where multiple errors are reported during a commit/commit-check RPC, only the first rpc-error is reported (by ncclient).  Thus early "warning" rpc-errors are masking later "error" rpc-errors.  I have opened an issue with ncclient here:  https://github.com/leopoul/ncclient/issues/54

**Comment by leopoul** [comment]
Fixed in https://github.com/leopoul/ncclient/commit/4d61c681889c234949e23f18b13754882202f72c
Will be in the upcoming release. Check my reply here: https://github.com/leopoul/ncclient/issues/54

Best,
Leo

**Comment by shermdog** [comment]
Tie this in with #358

**Comment by fhartung** [comment]
With the merged fixes, multiple RPC errors are now reported for Commit but not for Commit Check operations.

**Comment by vnitinv** [comment]
@fhartung I fixed the same and merged the changes. 
https://github.com/Juniper/py-junos-eznc/pull/454
Please try with latest code.

**Comment by fhartung** [comment]
Fixed, thank you.
