### ISSUE TITLE
how to use with Jython 

### ISSUE THREAD

**Issue by sravanmedarapu** [Juniper/py-junos-eznc#346]
Hi ,

I would like to use py-junos-eznc from jython. but when i am trying to use

import jnpr.junos

statement, I am getting exception saying "ImportError: No module named junos" but I have no issues when I am trying to run from python .

Can some one guide me how to do this from Jython ?

Thanks in Advance
Sravan

**Comment by shermdog** [comment]
Hi @sravanmedarapu ,

We do not support Jython.  The only advice I can give is make sure you're running the latest 2.7 beta as we require Python 2.6 or 2.7.  I'm also not certain if some of our dependencies are supported on Jython.  In particular I'd be concerned about lxml and ecdsa/paramiko.

If you are predominately working with Java I recommend you look at our Java libraries.

http://www.juniper.net/documentation/en_US/junos14.2/information-products/pathway-pages/netconf-java-toolkit/netconf-java-toolkit.html

Thanks,
-Rick
