### ISSUE TITLE
py-junos-eznc Vs NETCONF Java Toolkit

### ISSUE THREAD

**Issue by sravanmedarapu** [Juniper/py-junos-eznc#348]
Hi There,

I am about to choose NETCONF Java Toolkit to automate JunOS Device, Here I have question is there anything that py-junos-eznc does additionally when compare to NETCONF Java Toolkit. Just I want to choose best compatible one to work with JunOS device.

Can Someone help me this.

Thanks in Advance
Sravan

**Comment by vnitinv** [comment]
Hi @sravanmedarapu Both the toolkit has their own pros. You need to chose depending on your requirement. But if you have an option you can pick py-junos-eznc. You can follow the docs http://www.juniper.net/techpubs/en_US/junos-pyez1.0/information-products/pathway-pages/product/1.0/index.html
and still if you have any query please join google group and post it at  https://groups.google.com/forum/#!forum/junos-python-ez

**Comment by sravanmedarapu** [comment]
Thanks for the quick response, As you suggested I have posted my question in the group 

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/junos-python-ez/9Um4kqeIki0/S3o5Vr0IELwJ

can you please give me information about this.

My question: 
I wanted to integrate the scripts to an existing Java Framework,  So I feel NETCONF Java Toolkit gives more flexibility to integrate with an existing Java Framework, but I would look to choose best compatible Toolkit to interact with JunOS devices.

Can you suggest me on this.

Thanks in Advance
Sravan
