### ISSUE TITLE
Invalid host key error not caught

### ISSUE THREAD

**Issue by davidjdv** [Juniper/py-junos-eznc#349]
If the `~.ssh/known_hosts` file contains an invalid entry (in my case, caused by a missing newline) then PyEZ will only return the nondescript `ConnectError` message.

The failure comes from the **ncclient** `manager.connect()` function which, in turn, calls **paramiko**'s `load_known_hosts()`. The latter actually returns a clear error message:

```
InvalidHostKey: ('172.22.196.114 ssh-rsa AAAA...
    <snip />
    ...+SQ==', Error('Incorrect padding',))
```

I think there are 2 issues here:

1. **ncclient** `manager.connect()` takes several arguments, one of which is `hostkey_verify` which we set to `False` so I believe we should not even be loading the `known_hosts` file. I played with different parameters and we always seem to be performing this verification - this is a ncclient bug in my opinion.

2. PyEZ obfuscates the error by using the generic ConnectError message - this occurs in the following bit of code in the `device.py` file:

```python
        except Exception as err:
            # anything else, we will re-raise as a
            # generic ConnectError
            cnx_err = EzErrors.ConnectError(self)
            cnx_err._orig = err
            raise cnx_err
```
If we were to `raise cnx_err._orig` instead then we would have a clearer picture of what's going on.

**Comment by monrad** [comment]
We raised a issue with paramiko, https://github.com/paramiko/paramiko/issues/490, after debugging this today.
But i agree, it would be nice to have better error messages.

**Comment by shermdog** [comment]
To add a bit more information, there is an open PR with ncclient to skip load_known_hosts() when hostkey_verify is False or missing.

leopoul/ncclient#50
