### ISSUE TITLE
simpler version of globals().update(FactoryLoader().load(yaml.load(yml)))

### ISSUE THREAD

**Issue by vnitinv** [Juniper/py-junos-eznc#350]
As now more and more user uses yml in string format (in place of file), how about providing a simple function for "globals().update(FactoryLoader().load(yaml.load(yml)))". 
Say for ex:
dev.load_yaml(yaml_string_var)

**Comment by shermdog** [comment]
The users haven't reported the current method being overly complicated.  It's only 3 lines of code

```python
import yaml
from jnpr.junos.factory.factory_loader import FactoryLoader

globals().update(FactoryLoader().load(yaml.load(yml)))
```

Device is the wrong class to make this change as Tables can be loaded directly with XML objects or files.  If we were to add a convenience function it would be modifying factory.loadyaml() to accept a string or YAML object.

Note* I will not accept this change any earlier than 2.0 as there's plenty of other things that need to be fixed first.

-Rick

**Comment by ydnath** [comment]
Based on feedback, closing this as not fixed.
