### ISSUE TITLE
Commit error via netconf only

### ISSUE THREAD

**Issue by XioNoX** [Juniper/py-junos-eznc#359]
This might be a Junos bug,
When loading a configuration (with the ansible module), the SRX (running 12.1X44-D45.2) returns "msg:Unable to commit configuration:error,any,mgd: application or application-set must be defined"

While if I scp;load;commit the same config, it works fine (not even a warning).

Please let me know if you would like to see a diff of the changes for example and where to send it to if you think it might be an issue with py-junos-eznc.

Thanks

**Comment by shermdog** [comment]
I imagine it's Junos related as we're getting back an rpc-error element.

Please share a sanitized version of the config you're pushing.

You can post that in our Google Group if you'd like:
https://groups.google.com/forum/#!forum/junos-python-ez

**Comment by XioNoX** [comment]
Created: https://groups.google.com/forum/#!topic/junos-python-ez/2RkshnuVXOs
In short, the load via netconf works fine, and returns the diff attached to the post above. The changes don't impact the security policies or application block.
The firewall returns "Mar 17 03:56:44  fw1 file[3594]: UI_CONFIGURATION_ERROR: Process: mgd, path: [edit security policies from-zone corp to-zone corp policy corp-access-any match application], statement: any, application or application-set must be defined"

While it's an "any", it doesn't seem to recognize it.

JTAC replied to my ticket with a "Based on the case description I understand that you are getting a commit error only via netconf. I regret to inform you that JTAC officially does not support scripting and configuration via any software other  than Juniper's such as NSM or Space. However I did some research and found that all the bugs related to this error are caused by the application like NSM and Junos Space and not the SRX. You could try to find some meaning to the error by checking syslog, but  it seems that it is not telling us much.

Since this is out of our scope of support I will shchedule the closure of this case as of close of business today, in case you haveany further questions."

**Comment by shermdog** [comment]
Per the user:

> Okay, I found the issue.

> The Junos configuration file I was pushing had a replace: groups { [...] } statement.
> While loading that through the cli doesn't cause any issue to the hidden junos-defaults group, > > > loading it through netconf causes the group to be deleted.
> I'm not sure if that difference in behavior is expected, but at least I now know about it.

> Thanks for your time!
