### ISSUE TITLE
RouteTable looses prefix-length with extensive=True

### ISSUE THREAD

**Issue by brownian** [Juniper/py-junos-eznc#367]
```
>>> routes = RouteTable(dev)
>>> items = routes.get('<dest>/18')
>>> items.items()
[('<dest>/18', [('nexthop', '<nexthop>'), ('age', 467899), ('via', 'xe-0/0/0.4002'), ('protocol', 'BGP')])]
>>> 
>>> 
>>> routes = RouteTable(dev)
>>> items = routes.get('<dest>/18', extensive=True)
>>> items.items()
[('<dest>', [('nexthop', '<nexthop>'), ('age', 467913), ('via', 'xe-0/0/0.4002'), ('protocol', 'BGP')])]
```

And there is no way to override ```extensive=True``` to ```extensive=False``` in an yaml table definition? --- should I report this as another issue, if so?

**Comment by vnitinv** [comment]
@brownian 
Its not replicable in my device. Do share the output of below cli commad
show route <dest>/18 | display xml

**Comment by brownian** [comment]
@vnitinv 
```
root@Router> show route /18              
                      ^
invalid ip address or hostname: /18 at '/18'
root@Router> show route /18
```

**Comment by vnitinv** [comment]
My bad, github removed some of my syntax. I meant "show route <dest>/18 | display xml"

**Comment by brownian** [comment]
Sorry, my router does not accept ever ```show route /18```.

**Comment by vnitinv** [comment]
My bad, Github removed some syntax, i meant: show route \<dest\>/18 | display xml

**Comment by brownian** [comment]
```
root@Router> show route <dest>/18 | display xml       
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/14.2R2/junos">
    <route-information xmlns="http://xml.juniper.net/junos/14.2R2/junos-routing">
        <!-- keepalive -->
        <route-table>
            <table-name>inet.0</table-name>
            <destination-count>528967</destination-count>
            <total-route-count>528971</total-route-count>
            <active-route-count>528965</active-route-count>
            <holddown-route-count>0</holddown-route-count>
            <hidden-route-count>2</hidden-route-count>
            <rt junos:style="brief">
                <rt-destination><dest>/18</rt-destination>
                <rt-entry>
                    <active-tag>*</active-tag>
                    <current-active/>
                    <last-active/>
                    <protocol-name>BGP</protocol-name>
                    <preference>170</preference>
                    <age junos:seconds="469965">5d 10:32:45</age>
                    <med>0</med>
                    <local-preference>410</local-preference>
                    <as-path>< ... some ASes here ... > I
                    </as-path>
                    <validation-state>unverified</validation-state>
                    <nh>
                        <selected-next-hop/>
                        <to><nexthop></to>
                        <via>xe-0/0/0.4002</via>
                    </nh>
                </rt-entry>
            </rt>
        </route-table>
    </route-information>
    <cli>
        <banner></banner>
    </cli>
</rpc-reply>
```

**Comment by brownian** [comment]
Here ```<dest>``` is a destination, ```<nexthop>``` is a nexthop... Sorry, possibly I should mark tyhem in another way.

**Comment by vnitinv** [comment]
@brownian  You can use google group for such queries. https://groups.google.com/forum/#!forum/junos-python-ez

**Comment by brownian** [comment]
This is not a query, "```RouteTable``` looses prefix-length with ```extensive=True```" and do I believe this is an issue.

**Comment by vnitinv** [comment]
As you know PyEZ uses xml output and parse it to set value to table/view
Now when we do "show route 10.209.0.0/18 | display xml" we get rt-destination tag as
\<rt-destination\>10.209.0.0/18\</rt-destination\>

when we use extensive "show route 10.209.0.0/18 extensive | display xml" we get rt-destination tag as
\<rt-destination\>10.209.0.0\</rt-destination\>  (without prefix). 
Hence you see such output from PyEZ too.

**Comment by brownian** [comment]
Yes. I know.

And here could be a workaround: overriding ```extensive``` to ```False``` --- which is bad thing, as for me, but I failed to get this working anyway --- or adding to the table definition smth like this:
```
fields:
  # None without `extensive`, integer with `extensive`:
  prefix_length: rt-prefix-length
```

I don't know what is better or even acceptable. I just do believe this is an issue.

**Comment by shermdog** [comment]
Hi @brownian ,

The included Op Tables are provided for an example basis only.  As you've experienced, there are a variety of different situations and configurations for our customers that will influence the requirements of any given Op Table.

Please use this information to create a Table that is specific to your needs.

Thanks,
-Rick

**Comment by brownian** [comment]
@shermdog , Thank you! I will use, sure .)

ps. Actually the documentation is a bit unclear --- at least I thougth that ```show route``` and its ```pyez``` companion should not provide any incorrect information. Or this should be documented in any way.

Ok, ```wontfix``` is quite good, thank you .)
