### ISSUE TITLE
OpTable without key seems to be broken

### ISSUE THREAD

**Issue by fugitifduck** [Juniper/py-junos-eznc#371]
It seems the table return no item when there is no key attribute on the table.

This issue is seen with VlanTable

**Comment by shermdog** [comment]
Hi @fugitifduck 

The provided Tables/Views are for example purposes, and may not work on your device without modification.

Please review the following documentation:
https://techwiki.juniper.net/Automation_Scripting/010_Getting_Started_and_Reference/Junos_PyEZ/Troubleshooting%2C_Auditing%2C_and_Reporting/Define_Operational_Table

https://techwiki.juniper.net/Automation_Scripting/010_Getting_Started_and_Reference/Junos_PyEZ/Troubleshooting%2C_Auditing%2C_and_Reporting/Defining_a_Table_View

If you require further assistance, please open a topic in our Google Group.
https://groups.google.com/forum/#!forum/junos-python-ez

Thanks,
-Rick

**Comment by fugitifduck** [comment]
Hi @shermdog ,

I'm agreed with this, I have no problem with others table.
As I see in https://techwiki.juniper.net/Automation_Scripting/010_Getting_Started_and_Reference/Junos_PyEZ/Troubleshooting%2C_Auditing%2C_and_Reporting/Define_Operational_Table , if there is a <name> tag, there is no need for the key, 
but for the rpc reply of get-vlan-information, there is no <name> for the vlan reply...

I'll continue the discussion on the mailing list.
