### ISSUE TITLE
dev.rpc.get_interface_information() doesn't return mask in interface address

### ISSUE THREAD

**Issue by fervid** [Juniper/py-junos-eznc#378]
Hello. I have problem with pyez.

If I type "show interfaces terse | display xml" in Junos CLI I will get 
```xml
        <physical-interface>
            <name>ge-1/1/0</name>
            <admin-status>up</admin-status>
            <oper-status>up</oper-status>
            <description> BLA-BLA </description>
            <logical-interface>
                <name>ge-1/1/0.2</name>
                <admin-status>up</admin-status>
                <oper-status>up</oper-status>
                <description> BLA-BLA </description>
                <filter-information>
                </filter-information>
                <address-family>
                    <address-family-name>inet</address-family-name>
                    <interface-address>
                        <ifa-local junos:emit="emit">x.x.x.x/28</ifa-local>
                    </interface-address>
                    <interface-address>
                        <ifa-local junos:emit="emit">y.y.y.y/29</ifa-local>
                    </interface-address>
                </address-family>
            </logical-interface>
        </physical-interface>
```
BUT in python there is no mask in prefix:
root@test:~# python
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from jnpr.junos import Device
>>> import sys
>>> 
>>> router_login = '...'
>>> router_pass = '...'
>>> dev = Device('some_dev', router_login, router_pass)
... 
>>> dev.open()
>>> r = dev.rpc.get_interface_information()
>>> interface = r.xpath('physical-interface[name/text()="\nge-1/1/0\n"]/logical-interface[name/text()="\nge-1/1/0.2\n"]')
>>> address = interface[0].xpath("address-family[address-family-name/text()='\ninet\n']/interface-address/ifa-local")
>>> address[0].text
'\nx.x.x.x\n'
>>> 

But I expect to recieve '\nx.x.x.x/28\n'.

**Comment by fervid** [comment]
Also, there are no 'oper-status' and 'admin-status' tag for logical interfaces...
>>> interface[0].xpath('oper-status')
[]
>>> interface[0].xpath('admin-status')
[]

**Comment by vnitinv** [comment]
@fervid  You need to pass terse=True to the function
```python
r = dev.rpc.get_interface_information(terse=True)

# also you can get rid of \n from your code using normalize-space
interface = r.xpath('physical-interface[normalize-space(name)="ge-1/1/0"]/logical-interface[normalize-space(name)="ge-1/1/0.2"]')
address = interface[0].xpath("address-family[normalize-space(address-family-name)='inet']/interface-address/ifa-local")
print address[0].text
```

**Comment by fervid** [comment]
Thank you. It works.

**Comment by shermdog** [comment]
#342
