### ISSUE TITLE
Domain fact gathering not in try block, RPCerror uncaught.

### ISSUE THREAD

**Issue by agallo** [Juniper/py-junos-eznc#385]
Was using 1.1.0 until this morning with ssh key authentication.  After upgrade, connecting to the devices fails:

   
    from jnpr.junos import Device
    
    router = 'somerouter'
    username = 'netconf'
    path2keyfile = 'path2privatekey'
    
    dev = Device(router, user=username, ssh_private_key_file=path2keyfile)
    
    dev.open()
    

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 494, in open
    self.facts_refresh()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 758, in facts_refresh
    gather(self, self._facts)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/facts/domain.py", line 16, in facts_domain
    domain = junos.rpc.get_config(domain_filter_xml)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/rpcmeta.py", line 43, in get_config
    return self._junos.execute(rpc)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py", line 71, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 569, in execute
    raise e(cmd=rpc_cmd_e, rsp=rsp)
jnpr.junos.exception.PermissionError: PermissionError(severity: error, bad_element: system, message: permission denied)

rolled back to 1.1.0 to confirm, and authentication was successful. With both versions, the target router logs the following in 'messages':
    Jun 11 11:43:31  sshd[1258]: Accepted publickey for netconf from x.x.x.x port 40132 ssh2
    Jun 11 11:43:31  sshd[1258]: subsystem request for netconf by user netconf

I am able to login interactively with the username/key combination.

**Comment by shermdog** [comment]
Hi @agallo,

This is related to our updated facts gathering - you do not have permission to get this portion of the configuration. (configuration/system/domain-name)

Can you confirm what the permissions are for the user class?

Alternatively you can set `gather_facts=False` to work around.

Thanks,
-Rick

**Comment by agallo** [comment]
The user has read-only permissions:

    set system login user netconf class read-only

  Using 1.1.0, I get the following:

    from jnpr.junos import Device
    from pprint import pprint
    
    
    router = 'somerouter'
    username = 'netconf'
    path2keyfile = 'path2privatekey'
    
    dev = Device(router, user=username, ssh_private_key_file=path2keyfile)
    
    dev.open()
    Device(x.x.x.x)
    pprint( dev.facts )
    {'2RE': True,
     'HOME': '/var/home/netconf',
     'RE0': {'last_reboot_reason': 'Router rebooted after a normal shutdown.',
             'mastership_state': 'master',
             'model': 'RE-S-2000',
             'status': 'OK',
             'up_time': '321 days, 11 hours, 44 minutes, 26 seconds'},
     'domain': 'nit.gwu.edu',
     ...
     'version': '12.3R6.6',
     'version_RE0': '12.3R6.6',
     'version_info': junos.version_info(major=(12, 3), type=R, minor=6, build=6)}
    dev.close()



after a pip install --upgrade junos-eznc

    pip install --upgrade junos-eznc
    <snip>
    Successfully installed junos-eznc-1.2.0

I get the following:

    
    from jnpr.junos import Device
    from pprint import pprint
    
    
    router = 'somerouter'
    username = 'netconf'
    path2keyfile = 'privatekeyfile'
    
    dev = Device(router, user=username, ssh_private_key_file=path2keyfile)
    
    dev.open()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 494, in open
        self.facts_refresh()
      File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 758, in facts_refresh
        gather(self, self._facts)
      File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/facts/domain.py", line 16, in facts_domain
        domain = junos.rpc.get_config(domain_filter_xml)
      File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/rpcmeta.py", line 43, in get_config
        return self._junos.execute(rpc)
      File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py", line 71, in wrapper
        return function(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py", line 26, in wrapper
        return function(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 569, in execute
        raise e(cmd=rpc_cmd_e, rsp=rsp)
    jnpr.junos.exception.PermissionError: PermissionError(severity: error, bad_element: system, message: permission denied)
    pprint( dev.facts )
    {'2RE': False,
     'RE0': {'last_reboot_reason': 'Router rebooted after a normal shutdown.',
             'mastership_state': 'master',
             'model': 'RE-S-2000',
             'status': 'OK',
             'up_time': '321 days, 11 hours, 48 minutes, 51 seconds'},
     ...
     'vc_capable': False,
     'version': '12.3R6.6',
     'version_RE0': '12.3R6.6',
     'version_info': junos.version_info(major=(12, 3), type=R, minor=6, build=6)}
    dev.close()
    

So, it is authenticating successfully, and I can even get and print the device facts and issue other RPC commands, so I'm a little confused to the error message :)

**Comment by shermdog** [comment]
There was a bug prior to 1.2 when trying to gather the domain name of the system.  #332 

Previously we would try to find the domain name based on a resolv.conf file vs. getting it from the Junos config.  That was predominately to work around a Junos bug that existed at the time.

Now when connecting to the system we first check the Junos configuration for it under configuration/system/domain-name

Now I'm seeing that the patch for 1.2.0 doesn't get the configuration in a try block which is why it is bailing out.  (We'll fix that bit).

The view-only class does not contain the appropriate bit to view the 'system' level configuration.

https://www.juniper.net/techpubs/software/junos-es/junos-es93/junos-es-admin-guide/login-classes.html

If you are not using the facts you can disable gathering them (which will also decrease your connection time).

`dev.open(gather_facts=False)`

**Comment by agallo** [comment]
Thank you!  And thanks for the tip about speeding up the connection time.

**Comment by shermdog** [comment]
Hi @agallo 

I've merged in the fixed code.  You can update to the latest dev version using:

`pip install git+https://github.com/Juniper/py-junos-eznc.git`

Thanks,
-Rick

**Comment by agallo** [comment]
works like a champ!
