### ISSUE TITLE
domain-name configured in configuration group is not checked by facts_domain()

### ISSUE THREAD

**Issue by stacywsmith** [Juniper/py-junos-eznc#394]
facts_domain() does not check to see if a domain-name is configured in a configuration group.

Given a configuration like this:

```user@r0> show configuration groups global system domain-name 
example.com;

user@r0> show configuration system domain-name 

user@r0> show configuration system domain-name | display inheritance no-comments 
domain-name example.com;
```

facts_domain() will not find the example.com domain in the configuration.

In most cases, it will successfully revert to finding the configuration in the resolv.conf file, but I'm not sure that would work in logical-system configs + configuration groups.

In all cases where the configuration is being checked for a certain value, it would be best to check the inherited config.

**Comment by shermdog** [comment]
Good catch @stacywsmith !
