### ISSUE TITLE
KeyError: 'version_RE0' jnpr/junos/facts/swver.py", line 165, in facts_software_version

### ISSUE THREAD

**Issue by fervid** [Juniper/py-junos-eznc#398]
Hello.
I get following error while connecting to router:

python
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
from jnpr.junos import Device as Connect
dev = Connect(host='...', port=22, user='...', passwd='...').open()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/.local/lib/python2.7/site-packages/jnpr/junos/device.py", line 457, in open
    self.facts_refresh()
  File "/home/xxx/.local/lib/python2.7/site-packages/jnpr/junos/device.py", line 715, in facts_refresh
    gather(self, self._facts)
  File "/home/xxx/.local/lib/python2.7/site-packages/jnpr/junos/facts/swver.py", line 165, in facts_software_version
    facts['version'] = facts['version_' + master]
KeyError: 'version_RE0'

For experiment I made patch "/home/xxx/.local/lib/python2.7/site-packages/jnpr/junos/facts/swver.py":
```
        for re_ver in versions:
            k = 'version_' + re_ver[0]
            facts[k] = re_ver[1]
        if f_master is not None:
            master = f_master[0] if isinstance(f_master, list) else f_master
            if ('version_' + master) in facts:
                facts['version'] = facts['version_' + master]
            else:
                facts['version'] = facts[k]
```
And it works! But it just experiment.

**Comment by shermdog** [comment]
Hi @fervid ,

What is the device type you are connecting to, is it multiple RE/Chassis?

Please include the output of 'show version' (with invoke all or all members if multi).

Thanks,
-Rick

**Comment by fervid** [comment]
Yes, it is multiple RE device.

sfc0-re1:
--------------------------------------------------------------------------
Hostname: xxx
Model: txp
JUNOS Base OS boot [10.4R15.1]
.....


lcc0-re1:
--------------------------------------------------------------------------
Hostname: xxx-lcc0-re1
Model: t1600
JUNOS Base OS boot [10.4R15.1]
.....


lcc1-re1:
--------------------------------------------------------------------------
Hostname: xxx-lcc1-re1
Model: t1600
JUNOS Base OS boot [10.4R15.1]
JUNOS Base OS Software Suite [10.4R15.1]
.....


lcc2-re1:
--------------------------------------------------------------------------
Hostname: xxx-lcc2-re1
Model: t1600
JUNOS Base OS boot [10.4R15.1]
.....


lcc3-re1:
--------------------------------------------------------------------------
Hostname: xxx-lcc3-re1
Model: t1600
JUNOS Base OS boot [10.4R15.1]
.....

**Comment by shermdog** [comment]
Hi @fervid 

Unfortunately we only support Junos >= 11.4

You can disable facts gathering with `gather_facts=False` and may still be able to use PyEZ.

You should consider upgrading your devices as 10.4 has been EOS for over a year.
http://www.juniper.net/support/eol/junos.html

If you do upgrade to a supported release and still experience issues please let us now.

Thanks,
-Rick
