### ISSUE TITLE
Facts gathering fails on an EX8208 in standalone mode fails

### ISSUE THREAD

**Issue by stacywsmith** [Juniper/py-junos-eznc#402]
The following traceback is raised on an EX8208, operating standalone mode, running 12.3R9 during facts gathering:
```
Traceback (most recent call last):
  File "2.py", line 9, in <module>
    dev.open ()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 494, in open
    self.facts_refresh()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 758, in facts_refresh
    gather(self, self._facts)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/facts/swver.py", line 103, in facts_software_version
    x_swver = _get_swver(junos, facts)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/facts/swver.py", line 83, in _get_swver
    return dev.rpc.cli("show version all-members", format='xml')
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/rpcmeta.py", line 86, in cli
    return self._junos.execute(rpc)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py", line 71, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 569, in execute
    raise e(cmd=rpc_cmd_e, rsp=rsp)
jnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: all-members, message: syntax error, expecting <command>)
```

_get_vc_status() attempts to execute the get-virtual-chassis-information RPC and if this command returns a non-empty response, it sets:
```
 facts['vc_capable'] = True
```

An EX8208 operating in standalone mode returns this response to the get-virtual-chassis-information RPC:
```
user@ex8208> show virtual-chassis status | display xml        
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/12.3R6/junos">
    <virtual-chassis-information>
        <virtual-chassis-id-information>
            <virtual-chassis-id>2893.26ca.afb8</virtual-chassis-id>
            <virtual-chassis-mode>Disabled</virtual-chassis-mode>
        </virtual-chassis-id-information>
        <member-list junos:style="slot-range">
            <member>
                <member-status>Prsnt</member-status>
                <member-id>0</member-id>
                <fpc-slot-range>(FPC 0-7)</fpc-slot-range>
                <member-serial-number>BT0910333396</member-serial-number>
                <member-model>ex8208</member-model>
                <member-priority>128</member-priority>
                <member-mixed-mode>NA</member-mixed-mode>
                <member-role>Master*</member-role>
                <neighbor-list>
                </neighbor-list>
            </member>
        </member-list>
        <next-member-information>
            <next-member-id>1</next-member-id>
        </next-member-information>
    </virtual-chassis-information>
    <cli>
        <banner></banner>
    </cli>
</rpc-reply>
```

This causes facts['vc_capable'] to be set to True

Later, in _get_swver() this code is executed:
```
def _get_swver(dev, facts):
    # See if we're VC Capable
    if facts['vc_capable'] is True:
        return dev.rpc.cli("show version all-members", format='xml')
    else:
        try:
            return dev.rpc.cli("show version invoke-on all-routing-engines", format='xml')
        except:
            return dev.rpc.get_software_information()
```

However, "show version all-members" is not a valid CLI command on an EX8208, at least when it is operating in standalone mode. This causes the unhandled exception to be raised.
```
user@ex8208> show version ?
Possible completions:
  <[Enter]>            Execute this command
  brief                Display brief output
  detail               Display detailed output
  fpc                  Show software version on FPC
  invoke-on            Remote command execution
  rollback             Show version of previous set of packages
  |                    Pipe through a command
user@ex8208> show version all-members
                                 ^
syntax error, expecting <command>.

user@ex8208> 
```

I have been unable to check an EX8208 operating in a virtual chassis, so I'm unsure of the responses in this case.

**Comment by vnitinv** [comment]
Pull request #415 should address this issue.

**Comment by shermdog** [comment]
Hi @stacywsmith ,

Can you please test and verify this fix works for you?

`pip install git+https://github.com/vnitinv/py-junos-eznc.git@bug-fix-402`

Thanks,
-Rick

**Comment by stacywsmith** [comment]
On Jul 29, 2015, at 11:35 AM, Rick Sherman wrote:

Can you please test and verify this fix works for you?

pip install git+https://github.com/vnitinv/py-junos-eznc.git@bug-fix-402

Hi @shermdog,

Yes, I can test the specific issue reported in #402. (It may be a couple of days.)

I think there are a few more things we should consider in this area.

1) What's the behavior on an EX8208 VC, and does this diff cause any regression on an EX8208 VC? (I'm not sure I have the ability to test that easily.)

2) What's the real meaning of facts['vc_capable'], and should it be True or False in this case? Currently, for MX facts['vc_capable'] seems to be used to mean facts['vc_configured'] because an MX480 is "capable" of being configured in a VC, but this fact is only True if it actually "is configured" in a VC. By that meaning, this fact should probably be False on a standalone EX8208. (It might also be best to rename the fact.)

3) There are other situations where _get_swver() and facts_software_version() doesn't do the right thing. We should probably open additional issues to track those situations, but should consider one fix that addresses all the known issues. For example, I know that an MXVC with dual-RE on each member or a TX with dual-RE on SCC/LCC doesn't correctly report the versions on all RE's in the system. In those cases, it reports a subset of the versions rather than throwing an exception.

--Stacy
