### ISSUE TITLE
Junos daemon bounce even if no configuration change

### ISSUE THREAD

**Issue by XioNoX** [Juniper/py-junos-eznc#405]
Hi,

If I "load replace" a configuration that contains the "security ipsec" or "security ike" parts of a Junos device (for example an SRX), even if the diff doesn't show any upcoming changes for those blocks, the device will briefly take the session down and bring it back up (but long enough for BGP to notice).

In other words, if I load replace those parts with the exact same configuration, it will act as if something changed.

That sounds like a Junos issue, where even if there are no changes, the device will flag the daemon for a reload/restart.

This has been observed with Junos up to 12.1X44-D35.5 at least.

Any idea if there is a fix or workaround?

Thanks

**Comment by shermdog** [comment]
Hi @XioNoX ,

This is very likely a Junos related issue.  I believe in 14.1 or 14.2 there were some enhancements around this (but don't quote me).

Try and do a `load replace terminal` on the box itself to verify.

You can probably work around this in PyEZ by checking `if cu.diff() is not None` prior to committing.

If you get more info or want to discuss further, please open up a thread in our Google Group:  https://groups.google.com/forum/#!forum/junos-python-ez

Thanks,
-Rick
