### ISSUE TITLE
py-junos-eznc support for MAG4610 Junos Pulse Gateway

### ISSUE THREAD

**Issue by lalgare** [Juniper/py-junos-eznc#411]
Hello guys!

Is there any possible to add support for MAG4610 and use this module to connect via netconf over ssh?

Thanks in advance,

Regards,

**Comment by shermdog** [comment]
Hi @lalgare ,

That series of equipment was divested by Juniper and is now part of a different company.  We will not be adding support for it into PyEZ.
https://www.pulsesecure.net/products/mag/

That being said, you could try to connect to it with PyEZ by setting `gather_facts=False`.  I imagine if that does or does not work you could use PyEZ/ncclient as a basis for getting something together that does work.

Hope that helps.
-Rick
