### ISSUE TITLE
SCP->put print progress log in loop even if progress is not defined

### ISSUE THREAD

**Issue by vnitinv** [Juniper/py-junos-eznc#422]
from jnpr.junos import Device
from jnpr.junos.utils.scp import SCP

dev = Device(host='xxxx', user='xxx', password='xxxx')
dev.open()
with SCP(dev) as scp:
    scp.put(pkg, remote_path='/var/tmp')

output:
device-xxxx: jinstall-xxx.tgz: 95256576 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95272960 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95289344 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95305728 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95322112 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95338496 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95354880 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95371264 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95387648 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95404032 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95420416 / 952539287 (10%)
device-xxxx: jinstall-xxx.tgz: 95436800 / 952539287 (10%)

-----
-----

**Comment by shermdog** [comment]
That is functionin as I intended.   To turn off set `progress=False or None`

**Comment by vnitinv** [comment]
@shermdog for each bit/byte its printing the log. So the number of log lines goes in thousands. 
Earlier it used to print only when % increased in 10s. 
Also this change resulted in sw.install failure (when progress is being passed). python scp module look for progress function with 3 params. But with this change we provide function with just 2 params.  #421

**Comment by vnitinv** [comment]
Also scp.put(pkg) will print logs even though we are not passing progress function and is set True by default. But sw.install(pkg) will not print any log for scp when it calls it internally.

So we are having different default log rule for SCP and SW module.
