### ISSUE TITLE
Load diff

### ISSUE THREAD

**Issue by XioNoX** [Juniper/py-junos-eznc#424]
It's currently not possible to do a "load diff" using py-junos-eznc.

If possible, that would allow for example to workaround issue #405. Or to commit pre-staged diffs after being approved.

Thanks

**Comment by chidanandpujar** [comment]
Hi @XioNoX 

  Thanks for reporting the issue,  load patch option is implemented and released in 2.4.0 ,so closing this issue.

Release 2.4.0 - 1 APRIL 2020
Features Added

    Added load patch support #1001 

Thanks & Regards
Chidanand
