### ISSUE TITLE
Strip XML namespaces when tables are instantiated from a path to an XML file.

### ISSUE THREAD

**Issue by stacywsmith** [Juniper/py-junos-eznc#430]
When a Table is instantiated from a device instance, the XML RPC response is parsed, and XML namespaces are stripped from the response. When a Table is instantiated from a file containing XML, using the path argument, XML namespaces are not stripped. This causes things to fail unless the user manually strips the XML namespaces.

I feel that this should not be necessary. XML namespaces should be stripped in both cases so that the behavior of Tables/Views remains consistent in both cases.

I believe this MAY be as simple as changing lib/jnpr/junos/factory/optable.py:47 from:

self.xml = etree.parse(self._path).getroot()

to:

self.xml = remove_namespaces(etree.parse(self._path).getroot())

**Comment by jeffbrl** [comment]
I can't find where the XML RPC response is cleaned up by ```remove_namespaces``` except for RPC errors. If this were the case, a lot of Tables/Views would have been broken by #446. RPCs such as ```get-route-information``` have XML comments.

**Comment by vnitinv** [comment]
@stacywsmith Can you please share the steps/script for reproducing this?
