### ISSUE TITLE
Add timeout to wait_for()

### ISSUE THREAD

**Issue by akbhat** [Juniper/py-junos-eznc#431]
Please add a timeout or other logic to break out of the infinite loop in device.py:wait_for() if the pattern match fails.

    def wait_for(self, this=_SHELL_PROMPT):
        chan = self._chan
        got = []
        while True:
            rd, wr, err = select([chan], [], [], _SELECT_WAIT)
            if rd:
                data = chan.recv(_RECVSZ)
                got.append(data)
                if re.search(r'{0}\s?$'.format(this), data):
                    break
        return got

**Comment by spidercensus** [comment]
Why?

**Comment by akbhat** [comment]
Because it is an infinite loop and if the match fails for any reason there is no fail safe. I would argue this is dictated by good software practice.

**Comment by spidercensus** [comment]
Maybe.  I agree that infinite loop is not desirable behavior, but I also think that arbitrarily killing the loop after some number of seconds is also not desirable. 

Some REs can take a very long time to get to a prompt.  

I think it would make more sense to check inside the loop for the proper functioning of the SSH channel, that data is being received, and so forth.

**Comment by vnitinv** [comment]
Fixed in latest code. StartShell take timeout option. By default its 30 second.
Refer #580
