### ISSUE TITLE
gather_facts issue with 14.1X53-D30_vjunos.75

### ISSUE THREAD

**Issue by ddivins** [Juniper/py-junos-eznc#449]
QFX5100 running “14.1X53-D30_vjunos.75” gets error:
invalid literal for int() with base 10: '30_vjunos'
When gather_facts is run.  When set to false and not using any of the facts data, scripts seem ok.

This is a customer facing private build and they will use PyEz.

**Comment by vnitinv** [comment]
fixed via #450
