### ISSUE TITLE
commit error not correctly handled, results in stack trace

### ISSUE THREAD

**Issue by guydavies** [Juniper/py-junos-eznc#452]
Hi,

Apologies but I don't have a suggested fix for this.

I've been working with Ansible to bring a QFX5100 back to a "default" config as part of an automated initialisation process for a Contrail BMS lab.  As part of the lab, it was changing a single ae interface from 

lab@qfx5100-119> show configuration interfaces ae3
description "compute2-3 bond0";
flexible-vlan-tagging;
native-vlan-id 4094;
mtu 9192;
encapsulation extended-vlan-bridge;
aggregated-ether-options {
    minimum-links 1;
    lacp {
        active;
        periodic fast;
    }
}
unit 0 {
    vlan-id 4094;
}

{master:0}
lab@qfx5100-119> show configuration vlans
Contrail-5f28d3c2-9cf0-4aef-ae24-64184d800708 {
    interface ae3.0;
    vxlan {
        vni 4;
    }
}
contrail {
    description "Contrail control & data";
    vlan-id 2342;
    l3-interface irb.2342;
}
default {
    vlan-id 1;
    l3-interface irb.0;
}

to

lab@qfx5100-119> show configuration interfaces ae3
description "compute2-3 bond0";
mtu 9192;
aggregated-ether-options {
    lacp {
       active;
    }
}
unit 0 {
    family {
        ethernet-switching {
            vlan {
                members contrail;
            }
        }
    }
}

leaving the vlans config untouched.  This is evidently broken and cannot be committed.  However, the error output when this was run based on the following YAML

---
- hosts: qfx5100-119
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  tasks:

  - name: load merge (with replace) the default configuration file to qfx5100-119
    junos_install_config:
      user=lab
      passwd=m0naco
      port=830
      host={{ inventory_hostname }}
      file=/root/slab-ansible/qfx5100-default.conf
      replace=yes
      overwrite=no
      logfile=/root/slab-ansible/qfx5100-junos-config.log

...rest of file...

was

==============================start==============================
root@puppet:~/slab-ansible# date; ansible-playbook deploy-BMS-AGD.yml; date
Tue Nov  3 09:30:14 CET 2015

PLAY [qfx5100-119] ************************************************************

TASK: [load merge the default configuration file to qfx5100-119] **************
failed: [172.30.54.97] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1446539414.79-10999738669412/junos_install_config", line 2035, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1446539414.79-10999738669412/junos_install_config", line 420, in main
    _ldr(module)
  File "/root/.ansible/tmp/ansible-tmp-1446539414.79-10999738669412/junos_install_config", line 288, in _load_via_netconf
    cu.commit_check()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/config.py", line 169, in commit_check
    return JXML.rpc_error(err.xml)
AttributeError: 'exceptions.AttributeError' object has no attribute 'xml'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/deploy-BMS-AGD.retry

172.30.54.97               : ok=0    changed=0    unreachable=0    failed=1

Tue Nov  3 09:30:16 CET 2015

================================end==========================

I've fixed the problem by updating the file qfx5100-default.conf to also delete the offending VLAN left over by the Contrail configuration.  However, I don't believe that the system should be throwing a stack trace in the case of a commit error.

Rgds,

Guy

**Comment by vnitinv** [comment]
should be resolved by code changes in #454
