### ISSUE TITLE
PyEZ Device(...) by default runs with 'root' privileges

### ISSUE THREAD

**Issue by dssatya** [Juniper/py-junos-eznc#455]
dev = Device(host='localhost') => By default runs with root user, which will be security concern for few platforms.

Can it be changed to run the Device(host='localhost') API with current user who is executing the script ?

Thanks,
Satya

**Comment by vnitinv** [comment]
>>> from jnpr.junos import Device
>>> dev = Device('localhost')
>>> dev.open()
Device(10.209.16.206)
>>> dev.hostname
'xx.xxx.xx.xxx'
>>> dev.user
'notroot'
