### ISSUE TITLE
Need for PyEZ API which does automatic lock/load/commit/unlock the junos configuration

### ISSUE THREAD

**Issue by dssatya** [Juniper/py-junos-eznc#456]
Hi,

Please refer below link.

http://www.juniper.net/documentation/en_US/junos14.2/topics/reference/scripting/junos-script-automation-template-jcs-load-configuration.html

In SLAX, we do have API called
jcs:load-configuration(...) which does lock/load/commit/unlock the configuration database all in one shot
with lots of commit-options and roll back behavior.

Equivalent API needed in PyEZ , which will be very useful for script writers for off/on box.

Thanks,
Satya

**Comment by vnitinv** [comment]
@dssatya We dont plan to give a single API which does this all but #458 takes care of locking unlocking in one step by using code like:
```python
with Cofig(dev, mode='exclusive') as cu:
    cu.load(....)
    cu.commit()
```
