### ISSUE TITLE
Fact gathering fails when logging in as a logical-system's user

### ISSUE THREAD

**Issue by stacywsmith** [Juniper/py-junos-eznc#457]
This issue is based on a message to the Google group from Dechouniotis Dimitris. The full message is below.

When logging into a Junos device as a logical system's user, some commands are not available.

Specifically, the CLI command ```show cli directory``` is not avialable as shown in this output:
```
adminTest@mo:LS-TEST> show cli ?
Possible completions:
  <[Enter]>            Execute this command
  authorization        Show authorization and authentication information
  history              Show list of previous commands
  |                    Pipe through a command
adminTest@mo:LS-TEST> show cli    
```

This causes fact gathering to fail because it attempts to execute commands/RPCs which are not available to this user.

While this is a specific instance of a specific command failing for a logical-system's user, there may be other commands which fail for a logical system's user.

```
On Nov 28, 2015, at 6:41 AM, Dechouniotis Dimitris <dimitrisd22@gmail.com> wrote:

Hi All, 

I created a logical system and a login class and an administrator using the following xml configuration file

<configuration>
    <system>
             <login>
                <class>
                    <class-name>classTest</class-
name> 
                        <logical-system>LSTest</logical-system>
                     <permissions>all</permissions>
            </class>
                <user>
                    <user-name>adminTest</user-name> 
                        <full-name>AdminName</full-name>
                        <class>classTest</class> 
                        <authentication>
                    <plain-text-password-value>adm1ntest</plain-text-password-value>
                    </authentication>    
            </user>
             </login>
       </system>
</configuration>

Then I wrote the following script to login to the logical system as adminTest:

from jnpr.junos import Device
import sys

dev = Device(host="hostname", user="adminTest", passwd="adm1ntest")

try:
    dev.open()
except Exception as err:
        print "Cannot connect to device:", err

rsp = dev.rpc.get_interface_information(interface_name='ge-1/0/5.3', terse=True, normalize=True)
print rsp.xpath(".//address-family[address-family-name='inet']/ \
interface-address/ifa-local")[0].text
dev.close()

I get the following output:

Cannot connect to device: PermissionError(severity: error, bad_element: directory, message: permission denied)
10.2.2.2/24

It shows the right answer but why this error message is shown?

The same thing happens when I configure something. 

Any comment will be very helpful.

Thanks,
Dimitris
```

**Comment by jamesboswell** [comment]
Junos just doesn't implement `show cli directory` for logical-systems.  This error could be addressed by not calling `facts_session` inside Device.open() when making RPC calls to a logical-system

This would require some changes
* be able to detect the NETCONF session is to a logical-system (how??)
* not call `facts_session` when connected to a logical-system

That said,  as @stacywsmith points out there could be other such commands.  (my own limited testing hasn't found any others yet)

For this particular issue,  `PermissionError` is misleading,  it's just not a supported CLI command, therefore the RPC error.   Users can always set `Device.open(gather_facts=False)`  when they know they are connecting to a logical-system to avoid the error msg.

**Comment by vnitinv** [comment]
with latest code (1.3,1), facts gathering wont exception out, will just be giving warning message and device connection.
