### ISSUE TITLE
Value of unknow when i run a playbook.

### ISSUE THREAD

**Issue by Juniper2016** [Juniper/py-junos-eznc#471]

**Comment by Juniper2016** [comment]
Hello,

I can see the error below when i run the playbook gathering " junos.facts.version".
Any idea if this is a known issue ? Any idea how i could fix it ?

Ansible version
#######################
root@stchoko-ubuntu-vm1:~# ansible --version
ansible 2.0.0.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
########################

Playbook file:
############################################
root@stchoko-ubuntu-vm1:/etc/ansible# cat simple2.yml
---
  - name: Get Device Facts
    hosts: 172.19.163.123
    roles:
     - Juniper.junos
    connection: local
    gather_facts: no
    vars_prompt:
    - name: passwd
      prompt: "assword"

    tasks:
     - name: Checking NETCONF connectivity
       wait_for: host={{ inventory_hostname }} port=830 timeout=5

     - name: Retrieve information from devices running Junos OS
       junos_get_facts:
         host={{ inventory_hostname }} passwd={{ passwd }}
       register: junos

     - name: version
       debug: msg="{{ junos.facts.version }}"

##############################################

Debug playbook output:
############################################

root@stchoko-ubuntu-vm1:/etc/ansible# ansible-playbook simple2.yml
assword:

PLAY [Get Device Facts] ********************************************************

TASK [Checking NETCONF connectivity] *******************************************
ok: [172.19.163.123]

TASK [Retrieve information from devices running Junos OS] **********************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError                      : Value of unknown type: <class 'jnpr.junos.facts.swver.version_info'>, junos.version_info(major=(13, 2),                       type=X, minor=(51, 'D', 32), build=1)
fatal: [172.19.163.123]: FAILED! => {"changed": false, "failed": true, "parsed": false}

PLAY RECAP *********************************************************************
172.19.163.123             : ok=1    changed=0    unreachable=0    failed=1

root@stchoko-ubuntu-vm1:/etc/ansible#
root@stchoko-ubuntu-vm1:/etc/ansible#
root@stchoko-ubuntu-vm1:/etc/ansible#
root@stchoko-ubuntu-vm1:/etc/ansible# ansible-playbook simple2.yml
assword:

PLAY [Get Device Facts] ********************************************************

TASK [Checking NETCONF connectivity] *******************************************
ok: [172.19.163.123]

TASK [Retrieve information from devices running Junos OS] **********************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: Value of unknown type: <class 'jnpr.junos.facts.swver.version_info'>, junos.version_info(major=(13, 2), type=X, minor=(51, 'D', 32), build=1)
fatal: [172.19.163.123]: FAILED! => {"changed": false, "failed": true, "parsed": false}

PLAY RECAP *********************************************************************
172.19.163.123             : ok=1    changed=0    unreachable=0    failed=1

root@stchoko-ubuntu-vm1:/etc/ansible# ansible-playbook simple2.yml -vvvv
Using /etc/ansible/ansible.cfg as config file
Loaded callback default of type stdout, v2.0
1 plays in simple2.yml
assword:

PLAY [Get Device Facts] ********************************************************

TASK [Checking NETCONF connectivity] *******************************************
task path: /etc/ansible/simple2.yml:13
ESTABLISH LOCAL CONNECTION FOR USER: root
172.19.163.123 EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1453299649.54-215142688645792 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1453299649.54-215142688645792 )" )
172.19.163.123 PUT /tmp/tmpHlb4_A TO /root/.ansible/tmp/ansible-tmp-1453299649.54-215142688645792/wait_for
172.19.163.123 EXEC LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1453299649.54-215142688645792/wait_for; rm -rf "/root/.ansible/tmp/ansible-tmp-1453299649.54-215142688645792/" > /dev/null 2>&1
ok: [172.19.163.123] => {"changed": false, "elapsed": 0, "invocation": {"module_args": {"connect_timeout": 5, "delay": 0, "exclude_hosts": null, "host": "172.19.163.123", "path": null, "port": "830", "search_regex": null, "state": "started", "timeout": "5"}, "module_name": "wait_for"}, "path": null, "port": 830, "search_regex": null, "state": "started"}

TASK [Retrieve information from devices running Junos OS] **********************
task path: /etc/ansible/simple2.yml:16
ESTABLISH LOCAL CONNECTION FOR USER: root
172.19.163.123 EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1453299649.77-148474383396101 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1453299649.77-148474383396101 )" )
172.19.163.123 PUT /tmp/tmp5OKx32 TO /root/.ansible/tmp/ansible-tmp-1453299649.77-148474383396101/junos_get_facts
172.19.163.123 EXEC LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1453299649.77-148474383396101/junos_get_facts; rm -rf "/root/.ansible/tmp/ansible-tmp-1453299649.77-148474383396101/" > /dev/null 2>&1
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1453299649.77-148474383396101/junos_get_facts", line 2143, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1453299649.77-148474383396101/junos_get_facts", line 207, in main
    module.exit_json(**m_results)
  File "/root/.ansible/tmp/ansible-tmp-1453299649.77-148474383396101/junos_get_facts", line 1743, in exit_json
    kwargs = remove_values(kwargs, self.no_log_values)
  File "/root/.ansible/tmp/ansible-tmp-1453299649.77-148474383396101/junos_get_facts", line 626, in remove_values
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/root/.ansible/tmp/ansible-tmp-1453299649.77-148474383396101/junos_get_facts", line 626, in <genexpr>
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/root/.ansible/tmp/ansible-tmp-1453299649.77-148474383396101/junos_get_facts", line 626, in remove_values
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/root/.ansible/tmp/ansible-tmp-1453299649.77-148474383396101/junos_get_facts", line 626, in <genexpr>
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/root/.ansible/tmp/ansible-tmp-1453299649.77-148474383396101/junos_get_facts", line 635, in remove_values
    raise TypeError('Value of unknown type: %s, %s' % (type(value), value))
TypeError: Value of unknown type: <class 'jnpr.junos.facts.swver.version_info'>, junos.version_info(major=(13, 2), type=X, minor=(51, 'D', 32), build=1)

fatal: [172.19.163.123]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "junos_get_facts"}, "parsed": false}

PLAY RECAP *********************************************************************
172.19.163.123             : ok=1    changed=0    unreachable=0    failed=1
#################################################################################

Warm regards,
Stephane TCHOKO.

**Comment by vnitinv** [comment]
@Juniper2016 This is fixed with latest code of PyEZ and ansible modules.
