### ISSUE TITLE
Unable to commit changes using jinja template (jnpr.junos.utils.config.Config) 

### ISSUE THREAD

**Issue by ashirke** [Juniper/py-junos-eznc#473]
Hi, 
I am trying to push config jinja template on device using jnpr.junos.utils.config.Config function but cfg.diff() displays none output but same  with jinja template & variables i am able to push config with jnpr.junos.device.bind function & can see diff() output. Suspecting some issue with pyez. Kindly help. Screenshot attached for more information.  

<img width="992" alt="with_jnpr junos device bind" src="https://cloud.githubusercontent.com/assets/16920624/12616861/196b6710-c548-11e5-9629-1e23b8f74990.png">
<img width="987" alt="with_jnpr junos utils config config" src="https://cloud.githubusercontent.com/assets/16920624/12616860/195dfba2-c548-11e5-85f9-a0cd10bfcc3e.png">

**Comment by ganeshnalawade** [comment]
@ashirke 
Please put ```print cfg.diff()``` statement inside with block.
It should work.

**Comment by ashirke** [comment]
Thanks Ganesh. Appreciated your help. Its a silly mistake. 
Thanks once again.
