### ISSUE TITLE
commit_check 

### ISSUE THREAD

**Issue by ejmmanning** [Juniper/py-junos-eznc#485]
It seem that the commit_check throws and error even with the config is write.
I might be wrong but I trying to understand this.

Traceback (most recent call last):
  File "/home/tftpboot/vendor/vendor.py", line 94, in <module>
    main()
  File "/home/tftpboot/vendor/vendor.py", line 26, in main
    push_config()
  File "/home/tftpboot/vendor/vendor.py", line 85, in push_config
    dev.srx.commit_check()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/config.py", line 128, in commit_check
  #   if err.rsp.find('ok') is not None:
AttributeError: 'NoneType' object has no attribute 'find'
 
Process finished with exit code 1

**Comment by ganeshnalawade** [comment]
@ejmmanning Please share more information about device model, JUNOS version and the config you are trying to push.

**Comment by ejmmanning** [comment]
I am using a jinja2 temple load it to a file and then try to load the config to the srx210 I am having errors with the commit_check I don’t unseated the error message



Ed

**Comment by ejmmanning** [comment]
Sorry the device mode is srx210h2POE
 

The Code ver is 12.1x44-d35.5

**Comment by ejmmanning** [comment]
This was fix with upgrading the to the new version. Thank you everyone.
