### ISSUE TITLE
Capability exchange timed out seen for user running Aps with unauthorized / read-only permissions.

### ISSUE THREAD

**Issue by mamathac** [Juniper/py-junos-eznc#495]
User testu created with unauthorised permssion can login but not run any op commands.
When the user tries to run show command , it is expected to throw Permission error.
Instead we see Capability exchange timed out error:

Config:
regress@adora# show 
uid 2006;
class unauthorized;
authentication {
    encrypted-password "$5$/Z7GDnh.$skFAdSeO/eMAqaDUrhcyi8BoAuTZZ6aDVQnnQF82R.B"; ## SECRET-DATA
}

Username : testu
password: test123

Result:
Connecting to device 10.209.10.40 ................

ERROR occurred ConnectError(host: 10.209.10.40, msg: Capability exchange timed out)
Traceback (most recent call last):

Same with user having "read-only" permission.

Works fine for user with ''oper" permission...

**Comment by vnitinv** [comment]
taken care in ncclient via
https://github.com/ncclient/ncclient/pull/131

**Comment by vnitinv** [comment]
@mamathac Can you test this with PyEZ 2.0 and ncclient 0.5.2
