### ISSUE TITLE
dev.cli incorectly returns "invalid command"

### ISSUE THREAD

**Issue by XioNoX** [Juniper/py-junos-eznc#498]
Running "request system configuration rescue save" using dev.cli (through the ansible module) returns:
"invalid command: request system configuration rescue save"

This is because that command, even if being executed successfully, doesn't return anything:
```
xionox@testsrx1> request system configuration rescue save 

xionox@testsrx1> 
```
I guess that comes from line 697 in https://github.com/Juniper/py-junos-eznc/blob/master/lib/jnpr/junos/device.py#L697
```
            if ex.message is not '':
                return "%s: %s" % (ex.message, command)
            else:
                return "invalid command: " + command
```

**Comment by vnitinv** [comment]
@XioNoX  This is already fixed via #493 . You can install PyEZ from github to get this fix.
