### ISSUE TITLE
Shell session does not work for root user.

### ISSUE THREAD

**Issue by spidercensus** [Juniper/py-junos-eznc#505]
I'm using the below example program. 

```
#!/usr/bin/env python
import jnpr.junos.utils
from   jnpr.junos import Device
from   jnpr.junos.utils import *
from   jnpr.junos.utils.start_shell import *
from   jnpr.junos.utils.start_shell import StartShell

DUT = Device(host='10.252.191.104', user="root", passwd = "password!")
DUT.open()
print "Device opened!"
DUT_ss = StartShell(DUT)
DUT_ss.open()
print "got thru shell open."
print DUT_ss.run("pwd")
print DUT_ss.run("ls")
```

We never print the line "got thru shell open" because the library hangs while waiting for the "% " shell prompt to appear.  I have a fix i'll be suggesting.

**Comment by spidercensus** [comment]
It seems that the Junos shell uses the '''% ''' prompt for non-root users, and the '''%\t''' prompt for root users.  This is why it is necessary to set the prompt character in this utility file to be "%", and have the open() function look for this character in the .rstrip() version of the initial prompt.

**Comment by spidercensus** [comment]
https://github.com/Juniper/py-junos-eznc/pull/506

**Comment by spidercensus** [comment]
Vnitinv: Tried your fix.  Still has not fixed the issue on my MX480 running 14.2R5.8.  

This still appears to be because root shell is returning "%\t" , as I originally stated. Do you need debug output from the ssh lib or something?

**Comment by JamesNickerson** [comment]
+1 same problem

**Comment by spidercensus** [comment]
Hey. 
So here's what I did. I added the following line at line 52 of start_shell.py
`		print "RECEIVED!: %s\n" % repr(data)`

And here's the output.  Note the \t.  

```
Device opened!
RECEIVED!: 'Last login: Tue May 17 18:11:25 2016 from 172.24.5.223\r\r\n--- JUNOS 14.2R5.8 built 2015-11-25 00:46:47 UTC\r\n'

RECEIVED!: '\r'

RECEIVED!: '\x1b['

RECEIVED!: '3g\x1b[24;9H\x1bH\x1b[24;17H\x1bH\x1b[24;25H\x1bH\x1b[24;33H\x1bH\x1b[24;41H\x1bH\x1b[24;49H\x1bH\x1b[24;57H\x1bH\x1b[24;65H\x1bH\x1b[24;73H\x1bH\r\r'

RECEIVED!: 'root@re0-sur01%\t'

got thru shell open.
RECEIVED!: 'pwd'

RECEIVED!: '\r\r\n'

RECEIVED!: '/root\r\nroot@re0-sur01%\t'
```

**Comment by spidercensus** [comment]
And the .cshrc, which weirdly does not seem to include the \t. 
```
root@re0-sur01% cat .cshrc
#csh .cshrc file

if ($?prompt) then
        # An interactive shell -- set some stuff up
        set prompt="`whoami`@`hostname -s`% "
        set filec
        set edit
        set history = 100
        set savehist = 100
        set mail = (/var/mail/$USER)
        if ( $?tcsh ) then
                bindkey "^W" backward-delete-word
                bindkey -k up history-search-backward
                bindkey -k down history-search-forward
        endif
endif
```

**Comment by vnitinv** [comment]
@spidercensus  As 
re.search('(%|#)\s', 'xxxx %\t').group()
'%\t'
Hence I have done small change and expect it to work for you. 
https://github.com/Juniper/py-junos-eznc/compare/master...vnitinv:505-statshell-fix?expand=1#diff-f3246ebe903cb8f6f95857de3f668e06R6

Can you please install PyEZ from
pip install -U git+https://github.com/vnitinv/py-junos-eznc.git@505-statshell-fix

and confirm if this works for you. I can accordingly merge the code.

**Comment by spidercensus** [comment]
Confirmed fix.  Thank you.
