### ISSUE TITLE
Error (No handlers could be found for logger "ncclient.transport.ssh") while opening a handle to device

### ISSUE THREAD

**Issue by madhukar32** [Juniper/py-junos-eznc#508]
Hi,

We are trying to open a handle to a junos device from a docker container using pyez module and we are getting an error: No handlers could be found for logger "ncclient.transport.ssh".

Code executed:
from jnpr.junos import Device
dev = Device(host='xx.xx.xx.xx', user='root', password='xxxxxx', port = 22)
dev.open()

Error:
No handlers could be found for logger "ncclient.transport.ssh"
Traceback (most recent call last):
  File "try.py", line 14, in <module>
    main()
  File "try.py", line 10, in main
    dev.open()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 483, in open
    raise cnx_err
jnpr.junos.exception.ConnectError: ConnectError(host: xx.xx.xx.xx, msg: 'EntryPoint' object has no attribute 'resolve')

When we did some debugging, we found the issue arises because of the paramiko/transport.py module. Here is the debug:
> /usr/local/lib/python2.7/dist-packages/paramiko/transport.py(488)start_client()
-> while True:
(Pdb) No handlers could be found for logger "ncclient.transport.ssh"

We also have checked the hello message of the netconf on the junos box and it looks fine, we are able to ssh into the box manually from docker.

Any help would be really appreciated.

Thanks,
Madhukar

**Comment by vnitinv** [comment]
```python
No handlers could be found for logger "ncclient.transport.ssh
```
This is just a logging message and not any error. 
You are hitting issue with pycrypto.
Do follow this link
https://github.com/pyca/cryptography/issues/2853

upgrade pycrypto and then give a try.
```python
sudo pip install --upgrade distribute
```
Do let me know if this helps!!

**Comment by madhukar32** [comment]
Thank you so much Nitin. Above pip command worked like a charm
