### ISSUE TITLE
Cannot install on Fedora 24

### ISSUE THREAD

**Issue by blortox** [Juniper/py-junos-eznc#563]
I'm getting an error when running:

`pip install git+https://github.com/Juniper/py-junos-eznc.git` &&
'sudo pip install junos-eznc'

compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-sdBQU4/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-IxyrtT-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-sdBQU4/cryptography/

I have everything required to install them (As per Juniper documentation):

gcc.x86_64                                                                                   6.1.1-3.fc24                                                                            @updates 
libffi-devel.x86_64                                                                          3.1-9.fc24                                                                              @fedora  
libxml2-devel.x86_64                                                                         2.9.3-3.fc24                                                                            @fedora  
libxslt-devel.x86_64                                                                         1.1.28-12.fc24                                                                          @fedora  
openssl.x86_64                                                                               1:1.0.2h-1.fc24                                                                         @anaconda
python-devel.x86_64                                                                          2.7.12-1.fc24                                                                           @updates 
python-pip.noarch                                                                            8.0.2-1.fc24                                                                            @anaconda

Any help would be appreciated

**Comment by vnitinv** [comment]
@blortox 
try these before installing PyEZ
```
sudo pip install -U setuptools
sudo pip install cryptography==1.2.1```

**Comment by blortox** [comment]
@vnitinv 

`sudo pip install -U setuptools` worked fine.


I get the following error message when installing cryptography 1.2.1

    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-l9wbvu/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-VFiTmy-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-l9wbvu/cryptography/

Looks the same as before.

**Comment by vijay-shetty** [comment]
@blortox 

Try running the below command:

`sudo dnf install python2.7-dev libxml2-dev libxslt-dev libffi-dev libssl-dev git`

**Comment by vnitinv** [comment]
@blortox which version of openssl is there on your device? Do share the output of "openssl version"
Make sure OpenSSL is >=1.0.0

**Comment by blortox** [comment]
@vijay-shetty @vnitinv:

Sorry, forgot to close this, everything is working fine now.

**Comment by vijay-shetty** [comment]
@blortox What was the issue?
