### ISSUE TITLE
dev.facts handling NG switches such as QFX5100

### ISSUE THREAD

**Issue by gavmckee80** [Juniper/py-junos-eznc#576]
I have a suggestion to look at the personality types returned when gathering dev.facts, QFX switches have a completely different schema when looking at their ethernet switching tables etc.  I've found this when gathering switching tables across a large infrastructure , it would be useful to have another type other than switch , say like ng-switch so that we can test for this when deciding which table/view to use to collect information.

Thanks

**Comment by vnitinv** [comment]
@stacywsmith Sounds good to me. Any point from your side.

**Comment by jnpr-raylam** [comment]
from the switch_style.py, it does assign VLAN_L2NG or VLAN to distinguish between Legacy and ELS style, but the definition is out-dated, only classify the EX9200 and EX4300

    if persona in ['MX', 'SRX_HIGHEND']:
        style = 'BRIDGE_DOMAIN'
    elif persona in ['SWITCH', 'SRX_BRANCH']:
        model = facts['model']
        if re.match('firefly', model, re.IGNORECASE):
            style = 'NONE'
        elif re.match('^(EX9)|(EX43)', model):
            style = 'VLAN_L2NG'
        else:
            style = 'VLAN'
    else:
        style = 'NONE'

    facts['switch_style'] = style

Currently, all QFX family and all future EX family will be ELS
Better to check whether the RVI interface is 'irb' or 'vlan' in EX/QFX for classification, Legacy will be 'vlan', ELS will be 'irb'

**Comment by stacywsmith** [comment]
This will be addressed by #638

**Comment by stacywsmith** [comment]
#638 includes this enhancement and is now merged.
