### ISSUE TITLE
'rsp' attribute in RpcError Exception does not hold complete rpc response

### ISSUE THREAD

**Issue by gaddevijay** [Juniper/py-junos-eznc#597]
As per the doc string of RpcError class, 'rsp' should contain rpc response (after `<rpc-reply>`)
But as of now it only hold only one `'<rpc-error>'` info.

As designed earlier, 'rsp' should hold the complete rpc response. If the design is changed could we add new attribute to hold the complete rpc response and update the doc sting?

**Comment by ydnath** [comment]
@gaddevijay You can retrieve the complete error response using ```rsp.parent()```.

**Comment by dineshbaburam91** [comment]
The issue is already closed
