### ISSUE TITLE
RPC call returning XML Syntax error

### ISSUE THREAD

**Issue by gavmckee80** [Juniper/py-junos-eznc#602]
I'm getting the following error when executing the following RPC call

In [12]: rt = dev.rpc.get_route_information()
/Users/gmckee/Virtualenvs/Junos_PyEz/lib/python2.7/site-packages/jnpr/junos/device.py:880: RuntimeWarning: An unknown exception occured - please report.
  RuntimeWarning)
  File "<string>", line unknown
XMLSyntaxError: expected '>', line 1045154, column 5

**Comment by stacywsmith** [comment]
It appears the XML is malformed. It also looks like there are a large number of routes in the output. Have you tried increasing the timeout value?

If increasing the timeout doesn't work, then you will need to provide the full output of "show route | display xml" for additional troubleshooting.

Thanks,
--Stacy


On Sep 22, 2016, at 2:47 PM, gavmckee80 <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm getting the following error when executing the following RPC call

In [12]: rt = dev.rpc.get_route_information()
/Users/gmckee/Virtualenvs/Junos_PyEz/lib/python2.7/site-packages/jnpr/junos/device.py:880: RuntimeWarning: An unknown exception occured - please report.
RuntimeWarning)
File "", line unknown
XMLSyntaxError: expected '>', line 1045154, column 5

-

**Comment by vnitinv** [comment]
@gavmckee80 Gavin, Which version of PyEZ you are using? Can you unicast the output of "show route | display xml" to my mailbox.

**Comment by gavmckee80** [comment]
Hi Guys,

I've tested this on two separate instances of PyEz and against MX960 devices running in both lab and production (the production device is around 70k routes, lab is < 1000 routes) the same issue occurs.

Versions tested (taken from pip list)
junos-eznc (2.0.0)
junos-eznc (2.0.1)

Nitin, I'll forward you the XML from the lab device shortly.  Just out of interest

In [7]: dev = Device(host='x.x.x.x',port=22,user='gmckee',password=password,normalize=True)

In [8]: dev.open()
Out[8]: Device(x.x.x.x)

In [9]: rt = dev.rpc.get_route_information(table='inet.0')
In [10]: rt
Out[10]: <Element route-information at 0x2356368>

So when I specify an argument it works - without it does not

**Comment by stacywsmith** [comment]
@gavmckee80 Closing this issue as I believe we determined this was a case of Junos returning malformed XML. Specifically, the `<instance>.l2id.0` routing table was returning `<rt>` elements which had a missing opening tag for the `<rt-prefix-length>` element.

If this is not the case, please reopen.

**Comment by gavmckee80** [comment]
Thanks Stacy.

Gav
