### ISSUE TITLE
coun't install PyEz

### ISSUE THREAD

**Issue by 15ramky** [Juniper/py-junos-eznc#607]
hi, i can not install PyEz on Ubuntu 14.04.1

it giving me error while installing 

webubuntu-admin@webubuntu:~$ sudo pip install junos-eznc
[sudo] password for webubuntu-admin: 
Downloading/unpacking junos-eznc
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement junos-eznc
Cleaning up...
No distributions at all found for junos-eznc
Storing debug log for failure in /home/webubuntu-admin/.pip/pip.log
webubuntu-admin@webubuntu:~$ pip install junos-eznc
Downloading/unpacking junos-eznc
  Downloading junos-eznc-2.0.1.zip (115kB): 115kB downloaded
  Running setup.py (path:/tmp/pip_build_webubuntu-admin/junos-eznc/setup.py) egg_info for package junos-eznc
    
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.2.4 in /usr/lib/python2.7/dist-packages (from junos-eznc)
Downloading/unpacking ncclient>=0.4.6 (from junos-eznc)
  Downloading ncclient-0.5.2.tar.gz (61kB): 61kB downloaded
  Running setup.py (path:/tmp/pip_build_webubuntu-admin/ncclient/setup.py) egg_info for package ncclient
    
Downloading/unpacking paramiko>=1.15.2 (from junos-eznc)
  Downloading paramiko-2.0.2-py2.py3-none-any.whl (171kB): 171kB downloaded
Downloading/unpacking scp>=0.7.0 (from junos-eznc)
  Downloading scp-0.10.2-py2.py3-none-any.whl
Downloading/unpacking jinja2>=2.7.1 (from junos-eznc)
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB): 263kB downloaded
Downloading/unpacking PyYAML>=3.10 (from junos-eznc)
  Downloading PyYAML-3.12.tar.gz (253kB): 253kB downloaded
  Running setup.py (path:/tmp/pip_build_webubuntu-admin/PyYAML/setup.py) egg_info for package PyYAML
    
Downloading/unpacking netaddr (from junos-eznc)
  Downloading netaddr-0.7.18-py2.py3-none-any.whl (1.5MB): 1.5MB downloaded
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from junos-eznc)
Requirement already satisfied (use --upgrade to upgrade): pyserial in /usr/lib/python2.7/dist-packages (from junos-eznc)
Requirement already satisfied (use --upgrade to upgrade): setuptools>0.6 in /usr/lib/python2.7/dist-packages (from ncclient>=0.4.6->junos-eznc)
Downloading/unpacking pyasn1>=0.1.7 (from paramiko>=1.15.2->junos-eznc)
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Downloading/unpacking cryptography>=1.1 (from paramiko>=1.15.2->junos-eznc)
  Downloading cryptography-1.5.2.tar.gz (400kB): 400kB downloaded
  Running setup.py (path:/tmp/pip_build_webubuntu-admin/cryptography/setup.py) egg_info for package cryptography
    
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
Downloading/unpacking MarkupSafe (from jinja2>=2.7.1->junos-eznc)
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py (path:/tmp/pip_build_webubuntu-admin/MarkupSafe/setup.py) egg_info for package MarkupSafe
    
Downloading/unpacking idna>=2.0 (from cryptography>=1.1->paramiko>=1.15.2->junos-eznc)
  Downloading idna-2.1-py2.py3-none-any.whl (54kB): 54kB downloaded
Downloading/unpacking enum34 (from cryptography>=1.1->paramiko>=1.15.2->junos-eznc)
  Downloading enum34-1.1.6-py2-none-any.whl
Downloading/unpacking ipaddress (from cryptography>=1.1->paramiko>=1.15.2->junos-eznc)
  Downloading ipaddress-1.0.17-py2-none-any.whl
Downloading/unpacking cffi>=1.4.1 (from cryptography>=1.1->paramiko>=1.15.2->junos-eznc)
  Downloading cffi-1.8.3.tar.gz (403kB): 403kB downloaded
  Running setup.py (path:/tmp/pip_build_webubuntu-admin/cffi/setup.py) egg_info for package cffi
    
Downloading/unpacking pycparser (from cffi>=1.4.1->cryptography>=1.1->paramiko>=1.15.2->junos-eznc)
  Downloading pycparser-2.14.tar.gz (223kB): 223kB downloaded
  Running setup.py (path:/tmp/pip_build_webubuntu-admin/pycparser/setup.py) egg_info for package pycparser
    
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
Installing collected packages: junos-eznc, ncclient, paramiko, scp, jinja2, PyYAML, netaddr, pyasn1, cryptography, MarkupSafe, idna, enum34, ipaddress, cffi, pycparser
  Running setup.py install for junos-eznc
    Skipping installation of /usr/local/lib/python2.7/dist-packages/jnpr/__init__.py (namespace package)
    error: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/jnpr'
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_webubuntu-admin/junos-eznc/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-UfyrwE-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/jnpr

copying lib/jnpr/__init__.py -> build/lib.linux-x86_64-2.7/jnpr

creating build/lib.linux-x86_64-2.7/jnpr/junos

copying lib/jnpr/junos/exception.py -> build/lib.linux-x86_64-2.7/jnpr/junos

copying lib/jnpr/junos/rpcmeta.py -> build/lib.linux-x86_64-2.7/jnpr/junos

copying lib/jnpr/junos/device.py -> build/lib.linux-x86_64-2.7/jnpr/junos

copying lib/jnpr/junos/jxml.py -> build/lib.linux-x86_64-2.7/jnpr/junos

copying lib/jnpr/junos/console.py -> build/lib.linux-x86_64-2.7/jnpr/junos

copying lib/jnpr/junos/decorators.py -> build/lib.linux-x86_64-2.7/jnpr/junos

copying lib/jnpr/junos/__init__.py -> build/lib.linux-x86_64-2.7/jnpr/junos

copying lib/jnpr/junos/version.py -> build/lib.linux-x86_64-2.7/jnpr/junos

creating build/lib.linux-x86_64-2.7/jnpr/junos/facts

copying lib/jnpr/junos/facts/routing_engines.py -> build/lib.linux-x86_64-2.7/jnpr/junos/facts

copying lib/jnpr/junos/facts/personality.py -> build/lib.linux-x86_64-2.7/jnpr/junos/facts

copying lib/jnpr/junos/facts/switch_style.py -> build/lib.linux-x86_64-2.7/jnpr/junos/facts

copying lib/jnpr/junos/facts/domain.py -> build/lib.linux-x86_64-2.7/jnpr/junos/facts

copying lib/jnpr/junos/facts/chassis.py -> build/lib.linux-x86_64-2.7/jnpr/junos/facts

copying lib/jnpr/junos/facts/ifd_style.py -> build/lib.linux-x86_64-2.7/jnpr/junos/facts

copying lib/jnpr/junos/facts/session.py -> build/lib.linux-x86_64-2.7/jnpr/junos/facts

copying lib/jnpr/junos/facts/srx_cluster.py -> build/lib.linux-x86_64-2.7/jnpr/junos/facts

copying lib/jnpr/junos/facts/__init__.py -> build/lib.linux-x86_64-2.7/jnpr/junos/facts

copying lib/jnpr/junos/facts/swver.py -> build/lib.linux-x86_64-2.7/jnpr/junos/facts

creating build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/isis.py -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/lacp.py -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/teddb.py -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/l2circuit.py -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/ethernetswitchingtable.py -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/ospf.py -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/routes.py -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/xcvr.py -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/phyport.py -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/nd.py -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/ldp.py -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/intopticdiag.py -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/fpc.py -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/ethport.py -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/idpattacks.py -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/ccc.py -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/arp.py -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/vlan.py -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/bfd.py -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/__init__.py -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/lldp.py -> build/lib.linux-x86_64-2.7/jnpr/junos/op

creating build/lib.linux-x86_64-2.7/jnpr/junos/resources

copying lib/jnpr/junos/resources/user.py -> build/lib.linux-x86_64-2.7/jnpr/junos/resources

copying lib/jnpr/junos/resources/staticroutes.py -> build/lib.linux-x86_64-2.7/jnpr/junos/resources

copying lib/jnpr/junos/resources/syslog.py -> build/lib.linux-x86_64-2.7/jnpr/junos/resources

copying lib/jnpr/junos/resources/bgp.py -> build/lib.linux-x86_64-2.7/jnpr/junos/resources

copying lib/jnpr/junos/resources/interface.py -> build/lib.linux-x86_64-2.7/jnpr/junos/resources

copying lib/jnpr/junos/resources/__init__.py -> build/lib.linux-x86_64-2.7/jnpr/junos/resources

copying lib/jnpr/junos/resources/autosys.py -> build/lib.linux-x86_64-2.7/jnpr/junos/resources

creating build/lib.linux-x86_64-2.7/jnpr/junos/factory

copying lib/jnpr/junos/factory/factory_loader.py -> build/lib.linux-x86_64-2.7/jnpr/junos/factory

copying lib/jnpr/junos/factory/optable.py -> build/lib.linux-x86_64-2.7/jnpr/junos/factory

copying lib/jnpr/junos/factory/viewfields.py -> build/lib.linux-x86_64-2.7/jnpr/junos/factory

copying lib/jnpr/junos/factory/factory_cls.py -> build/lib.linux-x86_64-2.7/jnpr/junos/factory

copying lib/jnpr/junos/factory/view.py -> build/lib.linux-x86_64-2.7/jnpr/junos/factory

copying lib/jnpr/junos/factory/to_json.py -> build/lib.linux-x86_64-2.7/jnpr/junos/factory

copying lib/jnpr/junos/factory/cfgtable.py -> build/lib.linux-x86_64-2.7/jnpr/junos/factory

copying lib/jnpr/junos/factory/table.py -> build/lib.linux-x86_64-2.7/jnpr/junos/factory

copying lib/jnpr/junos/factory/__init__.py -> build/lib.linux-x86_64-2.7/jnpr/junos/factory

creating build/lib.linux-x86_64-2.7/jnpr/junos/transport

copying lib/jnpr/junos/transport/tty_serial.py -> build/lib.linux-x86_64-2.7/jnpr/junos/transport

copying lib/jnpr/junos/transport/tty.py -> build/lib.linux-x86_64-2.7/jnpr/junos/transport

copying lib/jnpr/junos/transport/tty_netconf.py -> build/lib.linux-x86_64-2.7/jnpr/junos/transport

copying lib/jnpr/junos/transport/tty_telnet.py -> build/lib.linux-x86_64-2.7/jnpr/junos/transport

copying lib/jnpr/junos/transport/__init__.py -> build/lib.linux-x86_64-2.7/jnpr/junos/transport

creating build/lib.linux-x86_64-2.7/jnpr/junos/cfg

copying lib/jnpr/junos/cfg/user.py -> build/lib.linux-x86_64-2.7/jnpr/junos/cfg

copying lib/jnpr/junos/cfg/user_ssh_key.py -> build/lib.linux-x86_64-2.7/jnpr/junos/cfg

copying lib/jnpr/junos/cfg/resource.py -> build/lib.linux-x86_64-2.7/jnpr/junos/cfg

copying lib/jnpr/junos/cfg/__init__.py -> build/lib.linux-x86_64-2.7/jnpr/junos/cfg

creating build/lib.linux-x86_64-2.7/jnpr/junos/utils

copying lib/jnpr/junos/utils/scp.py -> build/lib.linux-x86_64-2.7/jnpr/junos/utils

copying lib/jnpr/junos/utils/fs.py -> build/lib.linux-x86_64-2.7/jnpr/junos/utils

copying lib/jnpr/junos/utils/util.py -> build/lib.linux-x86_64-2.7/jnpr/junos/utils

copying lib/jnpr/junos/utils/sw.py -> build/lib.linux-x86_64-2.7/jnpr/junos/utils

copying lib/jnpr/junos/utils/start_shell.py -> build/lib.linux-x86_64-2.7/jnpr/junos/utils

copying lib/jnpr/junos/utils/config.py -> build/lib.linux-x86_64-2.7/jnpr/junos/utils

copying lib/jnpr/junos/utils/ftp.py -> build/lib.linux-x86_64-2.7/jnpr/junos/utils

copying lib/jnpr/junos/utils/__init__.py -> build/lib.linux-x86_64-2.7/jnpr/junos/utils

creating build/lib.linux-x86_64-2.7/jnpr/junos/cfgro

copying lib/jnpr/junos/cfgro/__init__.py -> build/lib.linux-x86_64-2.7/jnpr/junos/cfgro

creating build/lib.linux-x86_64-2.7/jnpr/junos/cfg/phyport

copying lib/jnpr/junos/cfg/phyport/switch.py -> build/lib.linux-x86_64-2.7/jnpr/junos/cfg/phyport

copying lib/jnpr/junos/cfg/phyport/classic.py -> build/lib.linux-x86_64-2.7/jnpr/junos/cfg/phyport

copying lib/jnpr/junos/cfg/phyport/base.py -> build/lib.linux-x86_64-2.7/jnpr/junos/cfg/phyport

copying lib/jnpr/junos/cfg/phyport/__init__.py -> build/lib.linux-x86_64-2.7/jnpr/junos/cfg/phyport

copying lib/jnpr/junos/op/nd.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/isis.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/ethport.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/vlan.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/xcvr.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/lacp.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/arp.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/ccc.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/l2circuit.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/intopticdiag.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/ethernetswitchingtable.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/bfd.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/phyport.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/idpattacks.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/routes.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/fpc.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/lldp.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/ldp.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/ospf.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/op/teddb.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/op

copying lib/jnpr/junos/resources/bgp.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/resources

copying lib/jnpr/junos/resources/syslog.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/resources

copying lib/jnpr/junos/resources/staticroutes.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/resources

copying lib/jnpr/junos/resources/autosys.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/resources

copying lib/jnpr/junos/resources/user.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/resources

copying lib/jnpr/junos/resources/interface.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/resources

copying lib/jnpr/junos/cfgro/srx.yml -> build/lib.linux-x86_64-2.7/jnpr/junos/cfgro

running install_lib

Skipping installation of /usr/local/lib/python2.7/dist-packages/jnpr/__init__.py (namespace package)

copying jnpr/junos/exception.py -> /usr/local/lib/python2.7/dist-packages/jnpr/junos

error: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/jnpr'

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_webubuntu-admin/junos-eznc/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-UfyrwE-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_webubuntu-admin/junos-eznc
Storing debug log for failure in /tmp/tmpYeZId4
webubuntu-admin@webubuntu:~$ 

Any help appreciable, thank you

**Comment by 15ramky** [comment]
Please close the issue
it was the proxy problem

Solution:
http://stackoverflow.com/questions/14149422/using-pip-behind-a-proxy

Under Ubuntu:
I could not get the proxy option to work as advertised - so following command did not work:
    sudo pip --proxy http://web-proxy.mydomain.com install somepackage
But exporting the https_proxy env variable (note its https_proxy not http_proxy) did the trick:
    export https_proxy=http://web-proxy.mydomain.com
then
    sudo -E pip install somepackage

**Comment by stacywsmith** [comment]
@15ramky I'm glad to hear you were able to figure out your problem!
