### ISSUE TITLE
Force a fileformat when using 'strange' fileextensions

### ISSUE THREAD

**Issue by job** [Juniper/py-junos-eznc#618]
All our configs (NTT Communications) end with the suffix `.confg` - this has historic internal reasons.

It would be cool if py-junos-eznc doesn't reject config files when it doesn't recognise the extension, but instead we can signal to the software through some way (some argument?) what the intended config file format interpretation should be.

A super ugly hack that you'll not want to merge, but serves solely to illustrate where the issue lays can be found here: https://github.com/job/py-junos-eznc/commit/6ef163103965b5ce99b37c3145b91736ea0f9853

**Comment by stacywsmith** [comment]
Doesn't the [`format`](https://github.com/Juniper/py-junos-eznc/blob/master/lib/jnpr/junos/utils/config.py#L246) argument already provide the needed functionality?

i.e.
```
cu.load(path='myfile.confg', format='text')
```

**Comment by bdreisbach** [comment]
thanks stacy. that indeed does solve our problem.

**Comment by stacywsmith** [comment]
@bdreisbach Thanks for confirming. Closing this issue.

**Comment by job** [comment]
I will verify tomorrow. Thanks for the pointer.
