### ISSUE TITLE
PyEZ bgp rpc

### ISSUE THREAD

**Issue by erich-kuehn** [Juniper/py-junos-eznc#620]
Having trouble getting this to work. Command is 'show route receive-protocol bgp <neighbor_addr> active-path'

Here is the RPC is get

print dev.display_xml_rpc('show route receive-protocol bgp 10.17.0.4 active-path', format='text')
<get-route-information>
    <active-path/>
    <bgp/>
    <peer>10.17.0.4</peer>
</get-route-information>

This is the error I'm seeing.

>>> sw = dev.rpc.get_route_information(active_path=True, bgp=True, peer='10.17.0.4')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/jnpr/junos/rpcmeta.py", line 156, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/Library/Python/2.7/site-packages/jnpr/junos/decorators.py", line 71, in wrapper
    return function(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/jnpr/junos/decorators.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/jnpr/junos/device.py", line 529, in execute
    raise e(cmd=rpc_cmd_e, rsp=rsp, errs=err)
jnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: bgp, message: syntax error, expecting <invoke-on>)

show version 
fpc0:
--------------------------------------------------------------------------
Hostname: XXXXXXXXX
Model: qfx5100-48s-6q
Junos: 14.1X53-D35.3

Here is the YAML I'm using.

cat bgp-rec-route.yml 
---

bgpNeighborTable:
 rpc: get-route-information
 args:
  extensive: True
  receive-protocol-name: bgp
 args_key: neighbor
 item: route-table/rt
 key: rt-destination
 view: bgpView

bgpView:
 fields:
  as-path: rt-entry/as-path
  rt_destination: rt-destination
  rt_prefix_length: rt-prefix-length
  preference: rt-entry/preference
  community: communities/community

**Comment by stacywsmith** [comment]
Unfortunately, the `show route receive-protocol` command has an inconsistency between the CLI and XML. This causes `| display xml rpc` to display an incomplete RPC for this command.

The correct RPC is:
```
<rpc>
      <get-route-information>
          <receive-protocol-name>bgp</receive-protocol-name>
          <peer>10.0.0.1</peer>
          <active-path/>
      </get-route-information>
</rpc>
```

Therefore, the correct PyEZ rpc call would be:
```
resp = dev.rpc.get_route_information(active_path=True,receive_protocol_name='bgp',peer='10.0.0.1')
```

FYI, this particular anomaly is discussed in more detail on pages 66 to 67 of [Automating Junos Administration](http://shop.oreilly.com/product/0636920041498.do). If you need additional help defining the PyEZ table/view, the PyEZ chapter of the book also covers that feature in detail.

**Comment by erich-kuehn** [comment]
Thank you.
