### ISSUE TITLE
RPC request-package-add - bad XML <output>

### ISSUE THREAD

**Issue by mtucker502** [Juniper/py-junos-eznc#626]
on SRX (cluster or single member) does not return good XML from <request-package-add> PyEZ does not handle this well.

**Example output from pyez:**
>>> ok = node1.rpc.request_package_add(no_copy=True, no_validate=True, reboot=True, package_name='/var/tmp/junos-srx5000-15.1X49-D50.3-domestic.tgz')
>>> from lxml import etree
>>> etree.dump(ok)
<pipe>
<more-no-more/>
</pipe>
 
>>> 

**Example output from ncclient:**
>>> ok = node1._conn.rpc('<request-package-add><reboot/><no-copy/><no-validate/><package-name>/var/tmp/junos-srx5000-15.1X49-D50.3-domestic.tgz</package-name></request-package-add>')
>>> ok
<ncclient.xml_.NCElement object at 0x7f3294182518>
>>> ok.tostring
b'<rpc-reply message-id="urn:uuid:b323fb31-92f8-4992-9960-0c7e2bc8a1d3">\n  <pipe>\n    <more-no-more/>\n  </pipe>\n  <cli>\n    <ignore-signals>\nhup\n</ignore-signals>\n  </cli>\n  <output>\nInstalling package \'/var/tmp/junos-srx5000-15.1X49-D50.3-domestic.tgz\' ... \nVerified junos-boot-srx5000-15.1X49-D50.3.tgz signed by PackageProductionEc_2016 method ECDSA256+unknown\nVerified junos-srx5000-15.1X49-D50.3-domestic signed by PackageProductionEc_2016 method ECDSA256+unknown\nVerified junos-boot-srx5000-15.1X49-D50.3.tgz signed by PackageProductionEc_2016 method ECDSA256+unknown\nVerified junos-srx5000-15.1X49-D50.3-domestic signed by PackageProductionEc_2016 method ECDSA256+unknown\nAvailable space: 2420566 require: 573634\nSaving boot file package in /var/sw/pkg/junos-boot-srx5000-15.1X49-D50.3.tgz\nJUNOS 15.1X49-D50.3 will become active at next reboot\nSaving state for rollback ... \nRebooting ...\nshutdown: [pid 6816]\nShutdown NOW!\n</output>\n  <package-result>\n0\n</package-result>\n</rpc-reply>\n'

**Comment by vnitinv** [comment]
@mtucker502 Can you please test with latest code from github.

**Comment by stacywsmith** [comment]
This appears to be an issue with the device returning invalid XML. @mtucker502 If that's not the case, please retest with latest PyEZ code from GitHub and provide additional details on the exact XML being returned by the device.
