### ISSUE TITLE
junos:comment XML namespace not supported

### ISSUE THREAD

**Issue by dorkmatt** [Juniper/py-junos-eznc#633]
XML configuration files which include the `<junos:comment>` tag fail to load. The initial error was found using the [ansible-junos-stdlib](https://github.com/Juniper/ansible-junos-stdlib), where `junos-eznc` is the underlay library. These would error out as:

    TASK [juniper : Deploy configuration] ******************************************
    fatal: [router01]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to load config: Namespace prefix junos on comment is not defined, line 193, column 19"}

The same error is present when using eznc itself, outside of the Ansible abstraction land. The current version of config.py in master would be line [387](https://github.com/Juniper/py-junos-eznc/blob/master/lib/jnpr/junos/utils/config.py#L387).

    >>> from jnpr.junos import Device
    >>> from jnpr.junos.utils.config import Config
    >>> dev = Device(host='router01', user='user', password='password', gather_facts=False)
    >>> dev.open()
    Device(router01)
    >>> cu = Config(dev)
    >>> data = """<configuration>
    ... <junos:comment>/* test */</junos:comment>
    ... </configuration>"""
    >>> cu.load(data)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Library/Python/2.7/site-packages/jnpr/junos/utils/config.py", line 381, in load
        rpc_contents = etree.XML(rpc_contents)
      File "src/lxml/lxml.etree.pyx", line 3192, in lxml.etree.XML (src/lxml/lxml.etree.c:77490)
      File "src/lxml/parser.pxi", line 1830, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:116674)
      File "src/lxml/parser.pxi", line 1718, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:115324)
      File "src/lxml/parser.pxi", line 1090, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:109723)
      File "src/lxml/parser.pxi", line 584, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:103584)
      File "src/lxml/parser.pxi", line 694, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:105238)
      File "src/lxml/parser.pxi", line 624, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:104147)
    lxml.etree.XMLSyntaxError: Namespace prefix junos on comment is not defined, line 2, column 15

It seems a bit odd that one can pull down configurations with eznc, which include annotated comments - but can't use the same eznc library to upload them back up.

My understanding is JunOS hasn't been most respectful of namespace scoping, see https://www.mail-archive.com/juniper-nsp@puck.nether.net/msg21530.html

**Comment by stacywsmith** [comment]
> It seems a bit odd that one can pull down configurations with eznc, which include annotated comments - but can't use the same eznc library to upload them back up.

How did you retrieve this configuration from the Junos device?

If you use `dev.rpc.get_config()`, then the `junos` namespace will be stripped from all XML tags and attributes and you won't see this problem when trying to load a config that's been downloaded using `dev.rpc.get_config()`.

The alternative is to include a namespace definition in your configuration fragment, like this:
```
<configuration xmlns:junos="junos">
    <junos:comment>/* test */</junos:comment>
</configuration>
```

While I agree that simply stripping XML namespaces is somewhat bad form, it's difficult to deal with them in PyEZ because of the way Junos uses them.

We will definitely investigate a formal fix to this issue, but I wanted to go ahead and provide you with a workaround for now.

**Comment by dorkmatt** [comment]
I'm fetching the configs with the [ansible-junos-stdlib](https://github.com/Juniper/ansible-junos-stdlib)'s [junos_get_config](https://github.com/Juniper/ansible-junos-stdlib/blob/master/library/junos_get_config).  The resulting configs dump out as:

    <configuration changed-seconds="1481279138" changed-localtime="2016-12-09 10:25:38 UTC">
        <version>13.3R9.13</version>
        <system>
            <junos:comment>/* test */</junos:comment>
            <host-name>router</host-name>

I don't see an obvious way with the `junos_install_config` to pass this alternative namespace option?

**Comment by dorkmatt** [comment]
Ah, re-reading this a third time - so if I change my `<configuration operation="replace">` to `<configuration operation="replace" xmlns:junos="junos">` - I should be good?

**Comment by dorkmatt** [comment]
Following on this, as expected adding `... xmlns:junos="junos">` resolved my issue.
