### ISSUE TITLE
Unable to load config on an EX4300 VC new out of box.

### ISSUE THREAD

**Issue by andyjsharp** [Juniper/py-junos-eznc#650]
```
fatal: [cswj-rbo1-1002]: FAILED! => {"changed": false, "failed": true, "module_stderr": "/tmp/ansible_NiqyLL/ansible_module_junos_install_config.py:198:
SyntaxWarning: import * only allowed at module level\n  
def _load_via_netconf(module):\n
/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py:533: 
RuntimeWarning: An unknown exception occured - please report.\n  
RuntimeWarning)\n
Traceback (most recent call last):\n  
File \"/tmp/ansible_NiqyLL/ansible_module_junos_install_config.py\", line 454, in <module>\n    
main()\n  
File \"/tmp/ansible_NiqyLL/ansible_module_junos_install_config.py\", line 451, in main\n    
_ldr(module)\n  
File \"/tmp/ansible_NiqyLL/ansible_module_junos_install_config.py\", line 316, in _load_via_netconf\n    
cu.commit_check()\n  
File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/config.py\", line 172, in commit_check\n    
return JXML.rpc_error(err.xml)\nAttributeError: 'XMLSyntaxError' object has no attribute 'xml'\n",
"module_stdout": "", "msg": "MODULE FAILURE"}
```

Ansible playbook is as follows:
```
- name: "Upload configuration using terminal server"
  register: config_noob_results
  ignore_errors: False
  junos_install_config:
    host={{ console }}
    user=root
    mode='telnet'
    port={{ vc_details[0].Port }}
    file={{ junos_conf }}
    overwrite=yes
    logfile={{ log }}
    check_commit_wait=4
    timeout=300
```
junos-eznc 2.0.1
Ansible 2.2.0.0
Juniper.junos 1.4.0

**Comment by derfUrban** [comment]
Hi @andyjsharp, did you ever find a fix for this issue you were seeing. I'm experiencing it and unable to rundown a specific cause or workaround for using a text config. Please advise.

**Comment by andyjsharp** [comment]
Yes, the issue was with a vanilla EX4300, it’s factory default configuration sends messages every 16secs or thereabouts in relation to the chassis configuration auto-image-upgrade. Unfortunately, these messages have a tendency to appear within the XML replies that are being sent, in effect corrupting the XML reply and breaking the process. My work-around at the time was to create another script to configure via the shell ‘cli -c “configure; delete chassis auto-image-upgrade; set system root-authentication plain-text-password-value juniper123;commit and-quit;exit”.  This approach let me delete the stop config that was messing the process up, and then run my normal process.

**Comment by rahkumar651991** [comment]
Looks to be a device specific issue, due to inactivity closing this issue. 
In case of related issue, you may re-open or raise a new issue.
