### ISSUE TITLE
PyEZ doesn't identify version information for NFX250.

### ISSUE THREAD

**Issue by andyjsharp** [Juniper/py-junos-eznc#652]
15.1X53-D40.3 or 15.1X53-D45.3 fail to work with PyEz as it is unable to identify the software version.
Note: NFX doesn't use "show version" but instead uses "show version local".
```
RPC:  
<get-software-information>
    <local/>
</get-software-information>
``` 
does not produce any version information with 15.1X53-D40.3, and therefore 
```
<get-software-information>
    <local/>
    <detail/>
</get-software-information>
``` 
might be an option.

This issue has a knock-on-effect with any tools that rely on the version information, e.g. Ansible modules for junos_install_os etc.

**Comment by stacywsmith** [comment]
Addressed by #659
