### ISSUE TITLE
device.open() crashes python with illegal hardware instruction

### ISSUE THREAD

**Issue by dfex** [Juniper/py-junos-eznc#654]
Fresh install of Python 3 and py-junos-eznc on a pretty fresh install of OSX 10.12.2
```
Darwin imax.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64

Python 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from jnpr.junos import Device
>>> print (jnpr.junos.__version__)
2.0.1
>>> mysrx = Device(host='172.16.10.254', user='bdale', password='password01')
>>> mysrx.open()
[1]    4738 illegal hardware instruction  python3
```

**Comment by stacywsmith** [comment]
I'm not sure how you installed Python 3, but this looks like a problem with the Python installation on your machine.

**Comment by stacywsmith** [comment]
@dfex If you verify your Python 3 installation and are still having problems, please let us know by reopening this issue.

**Comment by dfex** [comment]
No problem - yes, I'm still trying to re-create the issue using a non pyez library.

There is some vague reference to this error message being architecture-related, but I don't see how that could be my issue - it's 64-bit Mac OS X installer on a 64-bit Mac OS X machine..
