### ISSUE TITLE
with latest fact changes, pprint is not printing facts in pretty print manner

### ISSUE THREAD

**Issue by vnitinv** [Juniper/py-junos-eznc#660]
```python
from pprint import pprint

with Device('xx.xx.xx.xx', user='xxxx') as dev:
    pprint(dev.facts)
```

{'2RE': True, 'HOME': '/var/home/regress', 'RE0': {'status': 'OK', 'last_reboot_reason': 'Router rebooted after a normal shutdown.', 'model': 'RE-VMX', 'up_time': '37 minutes, 8 seconds', 'mastership_state': 'master'}, 'RE1': {'status': 'OK', 'last_reboot_reason': 'Router rebooted after a .......

**Comment by stacywsmith** [comment]
Fixed via #661.
