### ISSUE TITLE
UnlockError exception typeNoneType

### ISSUE THREAD

**Issue by cvicente** [Juniper/py-junos-eznc#667]
Using something like:

```
        try:
           # some code that includes cu.unlock()
        except UnlockError as err:
            print "Unable to unlock config: {0}".format(err)
            sys.exit(1)
```

I'm getting:

```
Traceback (most recent call last):
  File "./my_script", line 74, in <module>
    main()
  File "./my_script", line 53, in main
    print "Unable to unlock config: {0}".format(err)
TypeError: __str__ returned non-string (type NoneType)
```

Also, the contents of `err.message` are empty, so there's no way to get a description of the problem.

**Comment by stacywsmith** [comment]
I will work on this. I'll probably combine the fix for this one and #597 into the same pull request.

**Comment by vnitinv** [comment]
@cvicente I would suggest you to use context manager when dealing with lock and unlock config.
exclusive mode does lock and unlock.

for example:
```python
with Config(dev, mode='exclusive') as cu:
    cu.load(.....)
    cu.commit()
```

**Comment by cvicente** [comment]
@vnitinv That sounds like a good idea. I will give it a try. Thank you.

**Comment by rahkumar651991** [comment]
Based on the comments, context manager should handle the lock and unlock during config change. 
Marking it as inactive.
