### ISSUE TITLE
PyEz Logo

### ISSUE THREAD

**Issue by cg-cnu** [Juniper/py-junos-eznc#684]
Hi guys,
I am interested in designing a logo for this project.
I have done a few sketches and finalized this one. 
![image](https://cloud.githubusercontent.com/assets/2767425/24075084/02690bf4-0c3b-11e7-87d7-f2c28c66b1c4.png)
The colors of ```Py``` represents python and the ```EZ``` colors represents juniper.
Would like to hear your comments.

**Comment by vnitinv** [comment]
@cg-cnu please do send a pull request

**Comment by rahkumar651991** [comment]
Based on the end comments on #235, closing this issue.
