### ISSUE TITLE
Feature request: connect via SSH jump proxy

### ISSUE THREAD

**Issue by spidercensus** [Juniper/py-junos-eznc#696]
I'd love to see a feature whereby the device connection could be made via a SSH proxy.  This would allow users to connect to devices on the other side of a jump host.

**Comment by vnitinv** [comment]
@spidercensus Check if this helps https://github.com/Juniper/py-junos-eznc/issues/153

**Comment by dhanakane** [comment]
Another vote for this feature. Leaving this comment here in case someone else runs into the same problem.

#153 details a workaround where you forward a local proxy to a jumphost, but then need to run a shell command to open up a tunnel to the jumphost before running the command made available by the junos-eznc library.

**Comment by rahkumar651991** [comment]
closing this as fixed in latest release.
