### ISSUE TITLE
EthernetSwitchingTable broken?

### ISSUE THREAD

**Issue by stiltzkin10** [Juniper/py-junos-eznc#699]
Trying to get MACs out of some Juniper boxes. Different models EX4200, EX4300, QFX5100. Both in VC and non VC configuration. 

Example below is from a EX4200 running 12.2R4.5.

```
#!/usr/bin/python -tt

from jnpr.junos.op.ethernetswitchingtable import EthernetSwitchingTable
from jnpr.junos import Device

device = Device('172.16.0.16', username='XX', password='XX')

device.open()

macs = EthernetSwitchingTable(device)
macs.get()

print macs

device.close()
```

```
$ ./test3.py 
<class 'jnpr.junos.factory.OpTable.EthernetSwitchingTable'>
EthernetSwitchingTable:172.16.0.16: 0 items
```

$ pip show junos-eznc
Name: junos-eznc
Version: 2.1.1

**Comment by stacywsmith** [comment]
@sadig It appears you contributed `EthernetSwitchingTable`. Can you provide an example of it being used successfully?

Since there's no `key` attribute in `EthernetSwitchingTable`, it will default to using `name` as the key into each `ethernet-switching-table` item.

```
EthernetSwitchingTable:
    rpc: get-ethernet-switching-table-information
    args:
        detail: True
    item: ethernet-switching-table
    view: EthernetSwitchingView
```

However, the output doesn't contain a `<name>` element within the `<ethernet-switching-table>` element, so I'm not sure how this ever worked.

```
<rpc-reply>
    <ethernet-switching-table-information style="extensive">
        <ethernet-switching-table style="extensive">
            <mac-table-count>6</mac-table-count>
            <mac-table-learned>4</mac-table-learned>
            <mac-table-entry style="extensive">
                <mac-vlan>home</mac-vlan>
                <mac-vlan-tag>100</mac-vlan-tag>
                <mac-address>*</mac-address>
                <mac-interface>All-members</mac-interface>
                <mac-interfaces-list junos:style="flood-list">
                    <mac-interfaces>ae0.0</mac-interfaces>
                    <mac-interfaces>ge-0/0/10.0</mac-interfaces>
                    <mac-interfaces>ge-0/0/2.0</mac-interfaces>
                    <mac-interfaces>ge-0/0/0.0</mac-interfaces>
                </mac-interfaces-list>
                <mac-type>Flood</mac-type>
                <mac-nexthop>1329</mac-nexthop>
            </mac-table-entry>
            ...
        </ethernet-switching-table>
    </ethernet-switching-table-information>
</rpc-reply>
```

**Comment by vnitinv** [comment]
@stiltzkin10

If key is not provided in the Table, by default "name" is looked for. In your xml, name is not there hence key need to be explicitly provided. 

please refer:
https://www.juniper.net/documentation/en_US/junos-pyez1.2/topics/task/program/junos-pyez-tables-op-defining.html

Table item key
key
(Optional) One or more XPath expressions selecting the tag or tags whose values uniquely identify the Table item for items that do not use the <name> element as an identifier or for cases where composite keys are required.
If the item uses the <name> element for the identifier, you can omit this property.

Closing the issue, do open if required.

**Comment by stiltzkin10** [comment]
Hm, I'm not sure I follow here. I'm using EthernetSwitchingTable from jnpr.junos.op. 

Seems like EthernetSwitchingTable needs to be updated with a key?

**Comment by denysaleksandrov** [comment]
Bumped into this issue while trying to get MACs from ex4550 device with 14.1X53.
Per Nitin's comment fixed it by moving some fields into keys:

```
EthernetSwitchingTable:
    rpc: get-ethernet-switching-table-information
    args:
        detail: True
    item: ethernet-switching-table
    key:
        - mac-table-count
        - mac-table-learned
        - mac-table-persistent
    view: EthernetSwitchingView

EthernetSwitchingView:
    fields:
        entries: _MacTableEntriesTable
```


With the new table, I am to get mac table entries:
```
'''
>>> eth = EthernetSwitchingTable(dev).get()
>>> eth
EthernetSwitchingTable:172.30.189.77: 1 items
>>> eth.keys()
[('3', '0', '0')]
>>> eth.items()
[(('3', '0', '0'), [('entries', _MacTableEntriesTable:172.30.189.77: 3 items)])]
>>> for k,v in (eth.values()[0][0][1]).items():
...   print(k, v)
...
vlan4 [('vlan', 'vlan4'), ('vlan_tag', '4'), ('mac_address', '3c:94:d5:97:69:81'), ('type', 'Static'), ('age', None), ('learned_time', None), ('action', 'Forward'), ('next_hop', '0'), ('interface', 'Router'), ('interface-list', _MacTableInterfacesTable:172.30.189.77: 1 items)]
vlan5 [('vlan', 'vlan5'), ('vlan_tag', '5'), ('mac_address', '3c:94:d5:97:69:81'), ('type', 'Static'), ('age', None), ('learned_time', None), ('action', 'Forward'), ('next_hop', '0'), ('interface', 'Router'), ('interface-list', _MacTableInterfacesTable:172.30.189.77: 1 items)]
vlan6 [('vlan', 'vlan6'), ('vlan_tag', '6'), ('mac_address', '3c:94:d5:97:69:81'), ('type', 'Static'), ('age', None), ('learned_time', None), ('action', 'Forward'), ('next_hop', '0'), ('interface', 'Router'), ('interface-list', _MacTableInterfacesTable:172.30.189.77: 1 items)]
'''
```

**Comment by braincork** [comment]
I just tested this for an ex4300 with ELS...took some trial and error but works great:

yml = '''
---
EtherSwTable:
  rpc: get-ethernet-switching-table-information
  item: l2ng-l2ald-mac-entry-vlan/l2ng-mac-entry
  key:
      - l2ng-l2-mac-address
      - mac-count-global
      - learnt-mac-count
      - l2ng-l2-mac-routing-instance
      - l2ng-l2-vlan-id
      - l2ng-mac-entry
  view: EtherSwView

EtherSwView:
  fields:
    vlan_name: l2ng-l2-vlan-name
    mac: l2ng-l2-mac-address
    interface: l2ng-l2-mac-logical-interface
'''

**Comment by mcpat1993** [comment]
braincork, I found your yml to be very useful for the following:
- l2ng-l2-mac-address
- l2ng-l2-mac-logical-interface
- l2ng-l2-mac-flags

I was not successful, however, with l2ng-l2-vlan-id

Here's what my yaml looks like:
`EthernetSwitchingTable:
    rpc: get-ethernet-switching-table-information
    item: l2ng-l2ald-mac-entry-vlan/l2ng-mac-entry
    key:
      - l2ng-l2-mac-address
      - l2ng-l2-mac-logical-interface
      - l2ng-l2-mac-flags
      - l2ng-l2-vlan-id
    view: EthernetSwitchingView

EthernetSwitchingView:
    fields:
      -mac_address: l2ng-l2-mac-address
      -interface: l2ng-l2-mac-logical-interface
      -type: l2ng-l2-mac-flags
      -id: l2ng-l2-vlan-id`

I appreciate any help!
