### ISSUE TITLE
unexpected output - device.rpc.get_config(options={'format': 'xml'}).text

### ISSUE THREAD

**Issue by CMeza99** [Juniper/py-junos-eznc#702]
Not sure why this just produces a newline. This is unexpected behavior to me.
```python
>>> dev.rpc.get_config(options={'format': 'xml'}).text
'\n    '
```
This works If the format is json. It is not clear to me why this is required:
```python
etree.tostring(dev.rpc.get_config(options={'format': 'xml'}))
```
seems like `.text` should convert it to a string. Maybe feature request?

**Comment by vnitinv** [comment]
This is expected behaviour. text only gives the content string of given node (not all subsequent child nodes)

```python
>>> x = """<html>
<body>
Hello
<br/>
World
</body>
</html>"""
>>> op  = etree.fromstring(x)
>>> op.text
'\n'
>>> etree.tostring(op)
'<html>\n<body>\nHello\n<br/>\nWorld\n</body>\n</html>'
```
refer similar discussion on stackoverflow: http://stackoverflow.com/questions/4770191/lxml-etree-element-text-doesnt-return-the-entire-text-from-an-element
