### ISSUE TITLE
ConnectClosedError: ConnectClosedError

### ISSUE THREAD

**Issue by thupatigk** [Juniper/py-junos-eznc#703]
seen the below error while sending an rpc using 
KEYWORD ${response} = device . Execute Rpc Command On Device device=${r0}, command=<rpc><edit-config><target><candidate/></target><config><configuration><protocols><ospf><traceoptions><file><filename>test1_ospf</filename></file><flag><name>all</name></flag></traceoptions></ospf></protocols></configuration></config></edit-config></rpc>
Documentation:	
Execute rpc command on device
Start / End / Elapsed:	20170412 17:25:15.412 / 20170412 17:25:15.418 / 00:00:00.006
17:25:15.413	INFO	[avro] Executing rpc :	
17:25:15.418	FAIL	ConnectClosedError: ConnectClosedError(10.209.14.109)

Requirement is i have to open the ephemeral instance using netconf and need to push the config via rpc. when i sent first rpc it worked fine with Execute Rpc Command On Device  and while sending edit-config rpc facing above issue. Manual steps for reference

regress@avro> netconf 
mgd: error: schema: init: could not resolve function 'mgd_orch_package'

<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file</capability>
    <capability>urn:ietf:params:xml:ns:netconf:base:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:confirmed-commit:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:url:1.0?protocol=http,ftp,file</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring</capability>
    <capability>http://xml.juniper.net/netconf/junos/1.0</capability>
    <capability>http://xml.juniper.net/dmi/system/1.0</capability>
  </capabilities>
  <session-id>27166</session-id>
</hello>
]]>]]>

<rpc><open-configuration><ephemeral-instance>test1</ephemeral-instance></open-configuration></rpc>    >>>>>>>>>>>>>>>>>>>>>>>>opening the ephemeral instance test1
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/17.3D0/junos">
</rpc-reply>
]]>]]>

<rpc><edit-config><target><candidate/></target>    >>>>>>>>>>>>>>configuring using rpc
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/17.3D0/junos">
<config><configuration>  
            <protocols>
                <ospf>
                    <traceoptions>
                        <file>
                            <filename>test1_ospf</filename>
                        </file>
                        <flag>
                            <name>all</name>
                        </flag>
                    </traceoptions>
                </ospf>
            </protocols>
    </configuration></config>
<ok/>
</edit-config></rpc>
</rpc-reply>
]]>]]>

<rpc><commit><synchronize/></commit></rpc>    >>>>>>>>>>>>>>commit sync rpc
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/17.3D0/junos">
<ok/>
<commit-synchronize-server-success>
<current-job-id>1</current-job-id>
<number-of-jobs>1</number-of-jobs>
<estimated-time>60</estimated-time>
</commit-synchronize-server-success>
</rpc-reply>
]]>]]>

0$* bash                                                      

And is there a way to check how much time taken to execute one rpc ?

**Comment by vnitinv** [comment]
The issue was due to the way RPC where being called. With proper calls, APIs are working fine. Hence closing the issue.
