### ISSUE TITLE
Cannot pack pyez-script into .exe file by Pyinstaller

### ISSUE THREAD

**Issue by tongorz** [Juniper/py-junos-eznc#723]
The error output from pyinstaller is like:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIRsuH58/jnpr/junos/facts'

Same issue page under pyinstaller:
[https://github.com/pyinstaller/pyinstaller/issues/2438](url)

Answer given by pyinstaller is that:

Please ask the vendor of that package to fix this issue in their code. Proper solutions would be:
1. name all sub-modules in jnpr/junos/facts/__init__.py (this is the easiest one)
2. when running setup.py write existing sub-module's names into a text file and read it using pkg_resources (flexible, but most complicated to implement), or
3. use the pkg_resources' plugin-in mechanism.

**Comment by vnitinv** [comment]
Thanks for your suggestion @tongorz . Fixed via #731
