### ISSUE TITLE
jnpr.junos.utils.config.Config Won't Load Comments/Annotations from Text

### ISSUE THREAD

**Issue by britai** [Juniper/py-junos-eznc#727]
Trying to load configs from format="text" with annotations/comments in them. The rest of the config loads fine, but annotations/comments are never pushed over. 

For example

    prefix-list ntp_servers {
        /* ntp.sea */
        1.2.3.4/32;
        /* ntp.ord */
        4.3.2.1/32;
    }

 Loaded becomes

    prefix-list ntp_servers {
        1.2.3.4/32;
        4.3.2.1/32;
    }

**Comment by stacywsmith** [comment]
@britai I'm not seeing this problem on a vMX running Junos 16.1R4.7.

I have the following script:
```
import sys
import getpass

from jnpr.junos.device import Device
from jnpr.junos.version import VERSION, DATE
from jnpr.junos.utils.config import Config

# Python3 is input(), Python2 is raw_input()
try:
    input = raw_input
except:
    pass

username = input('Device Username: ')
passwd = getpass.getpass('Device Password: ')

print("Version: %s, Date: %s" % (VERSION, DATE))

config = '''
policy-options {
    prefix-list ntp_servers {
        /* ntp.sea */
        1.2.3.4/32;
        /* ntp.ord */
        4.3.2.1/32;
    }
}
'''

for hostname in sys.argv[1:]:
    print ("Connecting to %s..." % (hostname))
    dev = Device(host=hostname, user=username, passwd=passwd, port=22)
    dev.open()
    cu = Config(dev)
    cu.lock()
    cu.load(config)
    diff = cu.diff()
    cu.commit()
    cu.unlock()
    print('Diff is: %s' % (diff))
    dev.close()
```

Before running the script, there is no configuration at `[edit policy-options]`:
```
user@r0> show configuration policy-options    

user@r0>
```

I run the script:
```
user@h0:~/Automation/Projects/PyEZ/Sample Code$ python ./text_comments.py r0
Device Username: user
Device Password: 
Version: 2.1.4.dev0, Date: 2017-May-30
Connecting to r0...
Diff is: 
[edit]
+  policy-options {
+      prefix-list ntp_servers {
+          /* ntp.sea */
+          1.2.3.4/32;
+          /* ntp.ord */
+          4.3.2.1/32;
+      }
+  }

user@h0:~/Automation/Projects/PyEZ/Sample Code$
```

and now I look at the committed configuration on r0:
```
user@r0> show configuration policy-options    
prefix-list ntp_servers {
    /* ntp.sea */
    1.2.3.4/32;
    /* ntp.ord */
    4.3.2.1/32;
}

user@r0>
```

If you are still seeing problems, please provide the device model, Junos version, and the content of the script you are running.

**Comment by stacywsmith** [comment]
Please reopen if you still believe this is a PyEZ issue.

**Comment by britai** [comment]
The issue turned out to be how I was loading the config. Initially I was using a with open to load the config from a file, and then passing that to config.load. This was stripping out the comments.

When I switched specifying path=, the problem went away.

Thanks for your help. Your example showed me pretty clearly it wasn't a PyEZ issue which got me thinking it must be how I loaded.

**Comment by stacywsmith** [comment]
@britai Glad to hear you were able to resolve the issue.
