### ISSUE TITLE
reboot throws error or hangs due to missing rpc-reply tag

### ISSUE THREAD

**Issue by vnitinv** [Juniper/py-junos-eznc#733]
When a device is connected through console IP, <request-reboot> RPC request tag is not generating the closing rpc-reply tag. 
Due to which, reboot functionality in automation frameworks like- PyEZ, Ansible and Salt are affected.

1. Telnet to a device using console IP.

Thu Nov 03 15:16:33 [vijayshet@ttbg-shell13: ~] #telnet andrina-con
Trying 10.221.43.127...
Connected to andrina-con.
Escape character is '^]'.

Type the hot key to suspend the connection: <CTRL>Z

-------------------------------------------------------
Multi Session Menu
-------------------------------------------------------
  0 - Quit 
  1 - Initiate a regular session 
  2 - Initiate a sniff session 
  5 - List shared session(s) 

Enter your option: 1

Type the hot key to suspend the connection: <CTRL>Z

FreeBSD/i386 (andrina) (ttyu0)

login: regress
Password:
Last login: Thu Nov  3 02:38:30 from jets.englab.juniper.net

--- JUNOS 16.2-20161019_ib_16_2.1 Kernel 32-bit  JNPR-10.3-20160919.110159_fbsd-
At least one package installed on this device has limited support.
Run 'file show /etc/notices/unsupported.txt' for details.
% 

2. Type the below command to pass the Netconf RPC tag.

% xml-mode netconf need-trailer

<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file</capability>
    <capability>urn:ietf:params:xml:ns:netconf:base:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:confirmed-commit:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:url:1.0?protocol=http,ftp,file</capability>
    <capability>http://xml.juniper.net/netconf/junos/1.0</capability>
    <capability>http://xml.juniper.net/dmi/system/1.0</capability>
  </capabilities>
  <session-id>10457</session-id>
</hello>
]]>]]>

3. Paste the below RPC tag under the prompt.
<rpc><request-reboot><in>0</in></request-reboot></rpc>

% xml-mode netconf need-trailer

<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file</capability>
    <capability>urn:ietf:params:xml:ns:netconf:base:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:confirmed-commit:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:url:1.0?protocol=http,ftp,file</capability>
    <capability>http://xml.juniper.net/netconf/junos/1.0</capability>
    <capability>http://xml.juniper.net/dmi/system/1.0</capability>
  </capabilities>
  <session-id>10457</session-id>
</hello>
]]>]]>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/16.2D0/junos">
<request-reboot-results>
<request-reboot-status reboot-time="0">
Shutdown NOW!
[pid 10559]
</request-reboot-status>
</request-reboot-results>
                                                                               
*** FINAL System shutdown message from regress@andrina ***                   

System going down IMMEDIATELY                                                  

                                               >>>>>>>>>>>>>>>>   </rpc-reply> tag is missing  

reference number: 1220777

**Comment by rahkumar651991** [comment]
Closing the issue as this was raised to track the PR-1220777 and it has been closed.
