### ISSUE TITLE
Upgrade Docker image to python to 3

### ISSUE THREAD

**Issue by ntwrkguru** [Juniper/py-junos-eznc#745]
Should the python version in the Docker image be upgraded to 3 or spur a branch for python3? @vnitinv @stacywsmith

**Comment by stacywsmith** [comment]
@ntwrkguru Sorry, I'm not familiar enough with Docker to know exactly what our options are... In general, I think Docker users should have the option of using PyEZ with either python 2 or python 3, so I'd like to see us support both in some fashion.

**Comment by ntwrkguru** [comment]
@stacywsmith We'd have to have a branch for python2 and python 3 then. My only reservation with that is maintenance; how difficult will it be to maintain 2 current branches in the long run?

**Comment by ntwrkguru** [comment]
Python 3.x support is planned for Ansible 2.4 or 2.5. Once that released, I think moving the container to Python 3.x makes sense.

Closing for now.
