### ISSUE TITLE
 jnpr.junos.utils.sw import SW

### ISSUE THREAD

**Issue by ejmmanning** [Juniper/py-junos-eznc#768]
I am using the program example from Juniper on upgrading SRX. I have change the program a little but I am get the following errors when it try to install the software.

 Unable to install software, [Errno 111] Connection refused
Unable to install software, False.

I am using version  junos-eznc (2.1.1)  junos-netconify (1.0.2).

Below is the code.

import os, sys, logging
from jnpr.junos import Device
from jnpr.junos.utils.sw import SW
from jnpr.junos.exception import ConnectError

host = raw_input('\nEnter host ipaddress for primary firewall ')
package = '/home/tftpboot/junos-srxsme-12.1X46-D30.2-domestic.tgz'
remote_path = '/var/tmp'
validate = True
logfile = 'install.log'

def update_progress(dev, report):
    # log the progress of the installing process
    logging.info(report)

def main():

    # initialize logging
    logging.basicConfig(filename=logfile, level=logging.INFO,
                        format='%(asctime)s:%(name)s: %(message)s')
    logging.getLogger().name = host
    logging.getLogger().addHandler(logging.StreamHandler())
    logging.info('Information logged in {0}'.format(logfile))

    # verify package exists
    if not (os.path.isfile(package)):
        msg = 'Software package does not exist: {0}. '.format(package)
        logging.error(msg)
        sys.exit()

    dev = Device(host=host, user="removed", passwd="removed", port="removed", mode="telnet")
    try:
        dev.open()
    except ConnectError as err:
        logging.error('Cannot connect to device: {0}\n'.format(err))
        return

    # Create an instance of SW
    sw = SW(dev)

    try:
        logging.info('Starting the software upgrade process: {0}' \
            .format(package))
        ok = sw.install(package=package, remote_path=remote_path,
             progress=update_progress, validate=False, no_copy=False )
    except Exception as err:
        msg = 'Unable to install software, {0}'.format(err)
        logging.error(msg)
        ok = False

    if ok is True:
        logging.info('Software installation complete. Rebooting')
        rsp = sw.reboot()
        logging.info('Upgrade pending reboot cycle, please be patient.')
        logging.info(rsp)
    else:
        msg = 'Unable to install software, {0}'.format(ok)
        logging.error(msg)

    # End the NETCONF session and close the connection
    dev.close()

if __name__ == "__main__":
    main()

**Comment by vnitinv** [comment]
@ejmmanning Can you change the logging level to DEBUG (level=logging.DEBUG) and share full trace. If you have netconf log, do share that too.

**Comment by ejmmanning** [comment]
vnitinv Thank you for the quick response I figure it out. I needed to use the ssh and not telnet thank you

**Comment by ejmmanning** [comment]
Thank you for the help
