### ISSUE TITLE
software install 

### ISSUE THREAD

**Issue by ejmmanning** [Juniper/py-junos-eznc#769]
I am getting this error when I am trying to use the jnpr.junos.utils.sw install() Method. 
Does it not support SRX210-POE/

Thank you very much 

Unable to install software, RpcError(severity: error, bad_element: None, message: command is not valid on the srx210he2-poe)
Unable to install software, False

**Comment by stacywsmith** [comment]
@ejmmanning Please provide the exact line from your script where you're calling the `install()` method.

Also, please provide the current version of Junos running on your SRX210-POE.

This generally looks like you've provide some option to the `install()` method which is not understood by your particular platform.

**Comment by ejmmanning** [comment]
Hello Stacy 


Here is the info 

ry:
    logging.info <http://logging.info/>('Starting the software upgrade process: {0}' \
        .format(package))
    ok = sw.install(package=package, remote_path=remote_path,
         progress=update_progress, validate=False, no_copy=False )
 
 
The  code junos-srxsme-12.1X46-D30.2-domestic.tgz



Thank you

**Comment by stacywsmith** [comment]
@ejmmanning Is `junos-srxsme-12.1X46-D30.2-domestic.tgz` the code that's running on the device at the time the script is executed?

If so, what's the value of the `package` and `remote_path` variables?

**Comment by stacywsmith** [comment]
It would be great if you could provide NETCONF traceoptions.
```
set system services netconf traceoptions flag all
set system services netconf traceoptions file netconf.log
```

Re-execute you script and then provide the resulting netconf.log file.

**Comment by ejmmanning** [comment]
Stacy

Any Idea why its having a problem

**Comment by stacywsmith** [comment]
@ejmanning As I said earlier, there seems to be something about the NETCONF RPC that PyEZ is generating that your device doesn't like. In general, you're code looks fine, so it may be an issue specific to the to or from version of Junos. Having the details on the exact to and from versions of Junos and the NETCONF traceoptions should help answer the question.

**Comment by vnitinv** [comment]
@ejmmanning I dont see the netconf trace being provided. Closing the issue. If still facing issue, please re-open with data.
