### ISSUE TITLE
Linked documentation has SSL error

### ISSUE THREAD

**Issue by ckozler** [Juniper/py-junos-eznc#781]
https://techwiki.juniper.net/Projects/Junos_PyEZ

Reports:

This server could not prove that it is techwiki.juniper.net; its security certificate is from origin-www.juniper.net

**Comment by vnitinv** [comment]
@ckozler From where you got the reference for above link?

**Comment by ckozler** [comment]
On the readme under documentation on main page of the project 

Junos PyEZ wiki page, here.

"Here" brings you to the techwiki page I linked

**Comment by vnitinv** [comment]
@ckozler Thanks for noticing this. Will get this fixed.
