### ISSUE TITLE
configure private issue 

### ISSUE THREAD

**Issue by s2105** [Juniper/py-junos-eznc#784]
Hello, 

I am trying to put the following configuration to my script having an issue.

>>> from pprint import pprint
>>> from jnpr.junos import Device
>>> from jnpr.junos.utils.config import Config
>>> dev = Device(host='192.168.1.1, user=‘admin’, password=‘password’ )
>>> dev.open()
Device(192.168.1.1)
>>> cu = Config(dev, mode='private')
>>> cu.load('set system services netconf traceoptions file test.log', format='set', merge=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jnpr/junos/utils/config.py", line 533, in load
    ignore_warning=ignore_warning)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jnpr/junos/utils/config.py", line 454, in try_load
    raise ConfigLoadError(cmd=err.cmd, rsp=err.rsp, errs=err.errs)
jnpr.junos.exception.ConfigLoadError: ConfigLoadError(severity: error, bad_element: None, message: error: private edits in use. Try 'configure private' or 'configure exclusive'

Thank you in advance for help.

**Comment by stacywsmith** [comment]
It looks like there are probably a couple of issues here.

1) Your code is not actually using private configuration mode. It's attempting to use the default shared configuration mode. See [this comment](https://github.com/Juniper/py-junos-eznc/blob/master/lib/jnpr/junos/utils/config.py#L729-L730). In order to use the `mode` argument, you must use the `Config()` instance as a context manager.

2) I suspect that the device has a CLI session which is (or was) in "configure private" mode. If this is the case, and you try to enter shared configuration mode, you will see the `error: private edits in use. Try 'configure private' or 'configure exclusive'` message you are reporting.

To truly use private configuration mode try this:
```
from pprint import pprint
from jnpr.junos import Device
from jnpr.junos.utils.config import Config

dev = Device(host='192.168.1.1, user=‘admin’, password=‘password’ )
dev.open()
with Config(dev, mode='private') as cu:
    cu.load('set system services netconf traceoptions file test.log', format='set', merge=True)
    cu.commit()
dev.close()
```

**Comment by s2105** [comment]
Hello Stacy,

Yes, you are right about the device has a CLI session which is in "configure private" and we would like to implement that way. But your advice and code here work us, thank you very much for that and here my part of code, I have to modify to work 

def deployConfig(my_device_list_dict, my_username, my_password, my_config_template_file):
	my_hostname=""
	try:
		my_hostname=my_device_list_dict["mgmtip"]
		printProgress("INFO",my_hostname,"Connecting to device through netconf")
		dev=Device(my_hostname,user=my_username,password=my_password)
		dev.open()
		dev.timeout=3*60
		cu = Config(dev, mode='private') 
		printProgress("INFO",my_hostname,"Going to load template the config now.")
		rsp=cu.load(template_path=my_config_template_file,template_vars=my_device_list_dict,format='set', merge=True)
		printProgress("INFO",my_hostname,"Performing diff between active and candidate config.")
		cu.pdiff()
		printProgress("INFO",my_hostname,"Performing commit check. ")
		if cu.commit_check():
				printProgress("INFO",my_hostname,"commit check was successful.")
				printProgress("INFO",my_hostname,"performing commit now.")
				commit_status=cu.commit()
				printProgress("INFO",my_hostname,"disconnecting from device.")
				dev.close()
				return commit_status
		else:
			return False
	except Exception,err:
		printProgress("ERROR",my_hostname,"Encountered exception while deploying config.")
		printProgress("ERROR",my_hostname,str(err))
		return False


Again thank you for your help.
