### ISSUE TITLE
TypeError: with python 3.4 and savexml

### ISSUE THREAD

**Issue by wilmington** [Juniper/py-junos-eznc#794]
I'm seeing an issue with python 3.4.3 on OSX that I don't see using python 2.7.6

I'm a bit of a nimrod python scripture but perhaps related to the mode in which "savexml" opens files to save to?

> def log_xcvr_data(dev):
>     xcvrs = XcvrTable(dev)
>     xcvrs.get()
>     # this seems to barf on Python 3
>     xcvrs.savexml(path='/tmp/xcvr.xml', hostname=True, timestamp=True)

results in

> connecting to XXXX... Traceback (most recent call last):
>   File "bug.py", line 39, in <module>
>     log_xcvr_data(dev)
>   File "bug.py", line 17, in log_xcvr_data
>     xcvrs.savexml(path='/tmp/xcvr.xml', hostname=True, timestamp=True)
>   File "XXXX/textfsm/lib/python3.4/site-packages/jnpr/junos/factory/table.py", line 232, in savexml
>     return etree.ElementTree(self.xml).write(open(path, 'w'))
>   File "src/lxml/etree.pyx", line 2050, in lxml.etree._ElementTree.write (src/lxml/etree.c:67074)
>   File "src/lxml/serializer.pxi", line 731, in lxml.etree._tofilelike (src/lxml/etree.c:141736)
>   File "src/lxml/etree.pyx", line 326, in lxml.etree._ExceptionContext._raise_if_stored (src/lxml/etree.c:13259)
>   File "src/lxml/serializer.pxi", line 648, in lxml.etree._FilelikeWriter.write (src/lxml/etree.c:140363)
> TypeError: must be str, not bytes
>

**Comment by wilmington** [comment]
Fixed, many thanks - even better my hunch was right, should have trusted myself to fix it ;)

**Comment by vnitinv** [comment]
@wilmington we should always trust ourself :) 
Please do send a pull request anytime if you feel that going to add value.
