### ISSUE TITLE
SW._parse_pkgadd_response() does not correctly parse output from MX80 with nonexistent package.

### ISSUE THREAD

**Issue by stacywsmith** [Juniper/py-junos-eznc#801]
It appears this is a Junos issue specific to the MX80 platform. If I attempt to install a package which doesn't exist, then this platform produces:
```
user@mx80> request system software add /var/tmp/nonexistent.tgz | display xml 
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/17.3R1/junos">
    <cli>
        <ignore-signals>
            hup
        </ignore-signals>
    </cli>
    <output>
        ERROR: package: /var/tmp/nonexistent.tgz is not found or empty
    </output>
    <cli>
        <banner></banner>
    </cli>
</rpc-reply>
```

Notice that the error message produced is NOT an RPC error, but just a text string in an `<output>` element which happens to contain the string `ERROR`. There's also no `<package-result>` element.

On a VMX running the same version of Junos, I see:
```
user@vmx> request system software add /var/tmp/nonexistent.tgz | display xml 
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/17.3R1/junos">
    <cli>
        <ignore-signals>
            hup
        </ignore-signals>
    </cli>
    <output>
        /usr/libexec/ui/package: /var/tmp/nonexistent.tgz: no such file
        ERROR: No packages added
    </output>
    <package-result>1</package-result>
    <cli>
        <banner></banner>
    </cli>
</rpc-reply>
```
This platform correctly indicates a problem by the non-zero value for the `<package-result>` element.

There are other platforms which produce an RPC error upon error, and don't include a `<package-result>` element upon success. For this reason, PyEZ considers the MX80 output shown above to indicate that the package was successfully installed.

Instead, this MX80 output shown above should cause SW._parse_pkgadd_response() to return a non-zero return code indicating an error.

**Comment by rahkumar651991** [comment]
Closing the issue as the code changes seems to have been made for it.
