### ISSUE TITLE
Software installation utilities fails if the progress is a callback function within the class

### ISSUE THREAD

**Issue by darKnight18** [Juniper/py-junos-eznc#803]
[jsnapy_V2.txt](https://github.com/Juniper/py-junos-eznc/files/1627541/jsnapy_V2.txt)
Software installation utilities

If the progress parameter in the install method within the software utility is a callback function defined inside a class fails with an error.
TypeError: update_progress() takes exactly 3 arguments (4 given)

     `class ConnectDevice():
           def __init__(self):
                self.dev = Device(‘x.x.x.x',passwd=‘yy', user=‘zz')

           def update_progress(self, dev, report):
                print dev,report

           def software_update(self):
                 self.dev.open()
                 sw = SW(self.dev)
                 rsp = sw.install(package="/home/regress/junos-install-mx-x86-32-17.2-20170601.0.tgz", validate=True, progress=self.update_progress)
                            
 `

**Comment by stacywsmith** [comment]
Analysis...

I am able to reproduce this problem with the following code:
```
from jnpr.junos.device import Device
from jnpr.junos.utils.sw import SW

class Foo(object):
    def __init__(self, hostname, user, passwd):
        self.dev = Device(host=hostname, user=user, passwd=passwd)

    def update_progress(self, dev, report):
        print("My progress for %s is: %s" % (dev, report))

    def install(self):
        self.dev.open()
        print("%s has been opened." % (self.dev))
        sw = SW(self.dev)
        print("Beginning install on %s." % (self.dev))
        rsp = sw.install(package="./junos-install-mx-x86-64-16.1R4.7.tgz",
                         validate=True,
                         progress=self.update_progress)
        print("Response from sw.install() is: %s" % (rsp))

def main():
    f = Foo('r0', 'user', 'user123')
    f.install()

if __name__ == '__main__':
    main()
```

When executed, I get the following output and traceback:
```
user@h0:~$ python ./class_example.py 
Device(r0) has been opened.
Beginning install on Device(r0).
My progress for Device(r0) is: computing checksum on local package: ./junos-install-mx-x86-64-16.1R4.7.tgz
My progress for Device(r0) is: cleaning filesystem ...
My progress for Device(r0) is: before copy, computing checksum on remote package: /var/tmp/junos-install-mx-x86-64-16.1R4.7.tgz
Traceback (most recent call last):
  File "./class_example.py", line 26, in <module>
    main()
  File "./class_example.py", line 23, in main
    f.install()
  File "./class_example.py", line 18, in install
    progress=self.update_progress)
  File "/media/sf_Automation/Projects/PyEZ/Repos/stacywsmith/py-junos-eznc/lib/jnpr/junos/utils/sw.py", line 842, in install
    force_copy=force_copy)
  File "/media/sf_Automation/Projects/PyEZ/Repos/stacywsmith/py-junos-eznc/lib/jnpr/junos/utils/sw.py", line 611, in safe_copy
    self.put(package, remote_path=remote_path, progress=progress)
  File "/media/sf_Automation/Projects/PyEZ/Repos/stacywsmith/py-junos-eznc/lib/jnpr/junos/utils/sw.py", line 194, in put
    scp.put(package, remote_path)
  File "/usr/local/lib/python2.7/dist-packages/scp.py", line 154, in put
    self._send_files(files)
  File "/usr/local/lib/python2.7/dist-packages/scp.py", line 245, in _send_files
    self._progress(basename, size, 0)
TypeError: update_progress() takes exactly 3 arguments (4 given)
```

The issue is [here](https://github.com/Juniper/py-junos-eznc/blob/master/lib/jnpr/junos/utils/scp.py#L40-L52).

This code attempts to determine if the value of `progress` is a callable which takes 3 arguments in the format expected by the scp library, or if it takes arguments 2 arguments as is expected by the `SW.install()` progress argument. When the value of `progress` is a bound method rather than a function, then it is incorrectly treated as a callable in the format that the scp library expects. However, when it's actually invoked, the bound method doesn't actually take the expected number of arguments.
