### ISSUE TITLE
python3.6 ImportError: cannot import name 'config'

### ISSUE THREAD

**Issue by jigs2636** [Juniper/py-junos-eznc#808]
Hello,

I'm getting following error. 

[root@localhost Router_Test]# python3.6 test4.py 
Traceback (most recent call last):
  File "test4.py", line 4, in <module>
    from jnpr.junos.utils.config import config
ImportError: cannot import name 'config'

**Here is the code** 

#!usr/bin/python

from jnpr.junos import Device
from jnpr.junos.utils.config import config
import time

if __name__ == '__main__':
        dev = Device(host='10.233.255.57', user='python-guru')
        dev.open()
        config_chang = Config(dev)
        config_chang.load(path='config.set', merge=True)
        config_chang.commit(confirm=2)
        time.sleep(10)
        config_chang.commit()
        dev.close()

**Comment by stacywsmith** [comment]
> from jnpr.junos.utils.config import config

should be:
```
from jnpr.junos.utils.config import Config
```
that is `Config` not `config`

**Comment by jigs2636** [comment]
Thank you. That worked but got another error that i can't figured out since i just started playing with Python. Excuse me if its silly question.

I have config file in same directory as i'm running python.

root@localhost Router_Test]# ls
delete.set  test1.py  test2.py  test3.py  test4.py
[root@localhost Router_Test]# pwd
/home/Router_Test
[root@localhost Router_Test]# 

[root@localhost Router_Test]# python3.6 test4.py 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/jnpr/junos/device.py", line 770, in execute
    ignore_warning=ignore_warning)
  File "/usr/lib/python3.6/site-packages/jnpr/junos/decorators.py", line 169, in wrapper
    raise ex
  File "/usr/lib/python3.6/site-packages/jnpr/junos/decorators.py", line 116, in wrapper
    rsp = function(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jnpr/junos/device.py", line 1321, in _rpc_reply
    return self._conn.rpc(rpc_cmd_e)._NCElement__doc
  File "/usr/lib/python3.6/site-packages/ncclient/manager.py", line 172, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/usr/lib/python3.6/site-packages/ncclient/manager.py", line 232, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/usr/lib/python3.6/site-packages/ncclient/operations/third_party/juniper/rpc.py", line 44, in request
    return self._request(rpc)
  File "/usr/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 335, in _request
    raise RPCError(to_ele(self._reply._raw), errs=errors)
ncclient.operations.rpc.RPCError: error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/jnpr/junos/utils/config.py", line 450, in try_load
    **rpc_xattrs)
  File "/usr/lib/python3.6/site-packages/jnpr/junos/rpcmeta.py", line 277, in load_config
    return self._junos.execute(rpc, ignore_warning=ignore_warning)
  File "/usr/lib/python3.6/site-packages/jnpr/junos/decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jnpr/junos/decorators.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jnpr/junos/device.py", line 790, in execute
    errs=ex)
jnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: protocols, message: error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test4.py", line 11, in <module>
    config_chang.load(path='delete.set', merge=True)
  File "/usr/lib/python3.6/site-packages/jnpr/junos/utils/config.py", line 533, in load
    ignore_warning=ignore_warning)
  File "/usr/lib/python3.6/site-packages/jnpr/junos/utils/config.py", line 454, in try_load
    raise ConfigLoadError(cmd=err.cmd, rsp=err.rsp, errs=err.errs)
jnpr.junos.exception.ConfigLoadError: ConfigLoadError(severity: error, bad_element: protocols, message: error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command
error: unknown command)

**Comment by jigs2636** [comment]
Config files looks like this

protocols {
        bgp {
                group PYTHON-DEPLOY {
                        type internal;
                        local-address 10.0.0.1;
                        log-updown;
                        family inet {
                                unicast;
                        }

                }
        }
}

**Comment by stacywsmith** [comment]
> config_chang.load(path='config.set', merge=True)

See the documentation [here](http://junos-pyez.readthedocs.io/en/stable/jnpr.junos.utils.html#jnpr.junos.utils.config.Config.load).

By default, the extension of the filename used as the `path` argument defines the format of the configuration being loaded. Since your path ends with `.set`, it's expecting the configuration to be in `set` syntax.

There are two options:
1) Rename the config file from `config.set` to `config.txt` and change the line to:
```
config_chang.load(path='config.txt', merge=True)
```

2) Change the line to explicitly state the format is text:
```
config_chang.load(path='config.set', format='text', merge=True)
```

**Comment by jigs2636** [comment]
I'm still get the below error. it seems like permission issue according the juniper docs but i'm sure that python-guru is configured as super-user. so doesn't seems permission issue to me. 

https://www.juniper.net/documentation/en_US/junos-pyez/topics/task/troubleshooting/junos-pyez-configuration-errors-troubleshooting.html


[root@localhost Router_Test]# python3.6 test4.py 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/jnpr/junos/device.py", line 770, in execute
    ignore_warning=ignore_warning)
  File "/usr/lib/python3.6/site-packages/jnpr/junos/decorators.py", line 169, in wrapper
    raise ex
  File "/usr/lib/python3.6/site-packages/jnpr/junos/decorators.py", line 116, in wrapper
    rsp = function(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jnpr/junos/device.py", line 1321, in _rpc_reply
    return self._conn.rpc(rpc_cmd_e)._NCElement__doc
  File "/usr/lib/python3.6/site-packages/ncclient/manager.py", line 172, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/usr/lib/python3.6/site-packages/ncclient/manager.py", line 232, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/usr/lib/python3.6/site-packages/ncclient/operations/third_party/juniper/rpc.py", line 44, in request
    return self._request(rpc)
  File "/usr/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 337, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/jnpr/junos/utils/config.py", line 450, in try_load
    **rpc_xattrs)
  File "/usr/lib/python3.6/site-packages/jnpr/junos/rpcmeta.py", line 277, in load_config
    return self._junos.execute(rpc, ignore_warning=ignore_warning)
  File "/usr/lib/python3.6/site-packages/jnpr/junos/decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jnpr/junos/decorators.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jnpr/junos/device.py", line 790, in execute
    errs=ex)
jnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: ~, message: syntax error)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test4.py", line 11, in <module>
    config_chang.load(path='config.txt', format='text',  merge=True)
  File "/usr/lib/python3.6/site-packages/jnpr/junos/utils/config.py", line 533, in load
    ignore_warning=ignore_warning)
  File "/usr/lib/python3.6/site-packages/jnpr/junos/utils/config.py", line 454, in try_load
    raise ConfigLoadError(cmd=err.cmd, rsp=err.rsp, errs=err.errs)
jnpr.junos.exception.ConfigLoadError: ConfigLoadError(severity: error, bad_element: ~, message: error: syntax error)

**Comment by stacywsmith** [comment]
> jnpr.junos.exception.ConfigLoadError: ConfigLoadError(severity: error, bad_element: ~, message: error: syntax error)

This seems to indicate that the configuration you are trying to load has a syntax error and is therefore not a valid configuration. The error is near the character `~`. Since that character isn't in the config snippet you provided, I can't really help more.

**Comment by jigs2636** [comment]
Thanks Stacy. It got resolved. Since i was using vi editor to write config file, it by default used tilde (~) at the end and that's what causing the issue.

Thank you again and much appreciate your help!!
