### ISSUE TITLE
Compare configuration

### ISSUE THREAD

**Issue by ric79** [Juniper/py-junos-eznc#814]
Hello, 
I'm able to create, using ansible jinja2 templates, the config of a QFX node running in production environment. IE:

```
system {
    host-name zzzz;
    domain-name xxxx;
    services {
        ftp;
        ssh {
            root-login deny;
            protocol-version v2;
        }
        netconf {
            ssh;
        }
    }
    time-zone Europe/Rome;
}
```

I would compare it with the "show configuration" executed on the production node:
```
system {
    host-name zzzz;
    domain-name xxxx;
    time-zone Europe/Rome;
    services {
        ftp;
        netconf {
            ssh;
        }
        ssh {
            root-login deny;
            protocol-version v2;
        }
    }
}
```

Is there a way using pyez to compare the two configurations? 
Unix diff is not really helping...

Rr

**Comment by vnitinv** [comment]
@ric79  As such in PyEZ we don't have a way to compare two such files. Thanks

**Comment by ydnath** [comment]
Do you want to try https://github.com/Juniper/jsnapy
