### ISSUE TITLE
Fail to get some data from PhyPortErrorTable

### ISSUE THREAD

**Issue by joaonetto** [Juniper/py-junos-eznc#817]
Hello,

I'm trying to collect some data from PhyPortErrorTable and add them into a dict () variable, but all fields containing "-" return errors.

In the sample bellow, i'm try to get the the value from key rx_err_l2-channel

```
Traceback (most recent call last):
  File "interfaceext.py", line 127, in <module>
    'rx_err_l2-channel': errorPhy.rx_err_l2-channel,
  File "/usr/local/lib/python3.6/site-packages/jnpr/junos/factory/view.py", line 215, in __getattr__
    raise ValueError("Unknown field: '%s'" % name)
ValueError: Unknown field: 'rx_err_l2'
```

This issue happened in all cases below:

```
rx_err_l2-mismatch
rx_err_l3-incompletes
tx_err_carrier-transitions
tx_err_hs-crc
```

Like we can see, all fails have a "-" in a key.

All the best,

JNetto

**Comment by vnitinv** [comment]
@joaonetto Thanks for reporting this. It should be the underscore ( _ ) and not hyphen ( - ). Python rule.
Will get this fixed. By that time you can use the same table by customizing it. Check this example:
https://github.com/vnitinv/pyez-examples/blob/master/9_user_defined_table.py

**Comment by joaonetto** [comment]
Thank you @vnitinv for your answer and help, your example helped me to fix my issue.

In your last post you mentioned about Python Rules, so, Could you please share with me links, PEPs or anything else to help me to understand this rules ?

All the best and thank you again

**Comment by vnitinv** [comment]
pep8/pep20 are just python coding style guideline. You can search it easily.
Closing this issue as you can define table/view. Would suggest you to copy your user-defined table/view in the comment section, so that others can reference.
