### ISSUE TITLE
Can't get all lane info for et- interfaces

### ISSUE THREAD

**Issue by anudeep26** [Juniper/py-junos-eznc#820]
```
optic_yaml = '''
---
PhyPortDiagTable:
  rpc: get-interface-optics-diagnostics-information
#  args:
#    interface_name: '[efgx][et]-*'
#  args_key: interface_name
  item: physical-interface
  view: PhyPortDiagView

PhyPortDiagView:
  groups:
    diag: optics-diagnostics/optics-diagnostics-lane-values
  fields_diag:
    lane : lane-index
    tx_power : laser-output-power
    rx_power : laser-rx-optical-power
'''
```

globals().update(FactoryLoader().load(yaml.load(optic_yaml))

diag_info = PhyPortDiagTable(device)
diag_info.get()

def optic_diag():
    for i in diag_info:
        print(" if_name : {}, Lane : {}, tx : {}, rx : {}".format(i.name, i.lane,i.tx_power, i.rx_power))

prints the following:

if_name : et-0/0/19, Lane : 0, tx : 0.976, rx : 0.725
 if_name : xe-6/0/0:0, Lane : 0, tx : 0.546, rx : 0.000
 if_name : xe-6/0/0:1, Lane : 0, tx : 0.546, rx : 0.000
 if_name : xe-6/0/0:2, Lane : 0, tx : 0.546, rx : 0.000
 if_name : xe-6/0/0:3, Lane : 0, tx : 0.546, rx : 0.000
 if_name : xe-6/0/1:0, Lane : 0, tx : 0.878, rx : 0.000
 if_name : xe-6/0/1:1, Lane : 0, tx : 0.878, rx : 0.000
 if_name : xe-6/0/1:2, Lane : 0, tx : 0.878, rx : 0.000
 if_name : xe-6/0/1:3, Lane : 0, tx : 0.878, rx : 0.000
 if_name : xe-6/0/2:0, Lane : 0, tx : 0.618, rx : 0.000
 if_name : xe-6/0/2:1, Lane : 0, tx : 0.618, rx : 0.000
 if_name : xe-6/0/2:2, Lane : 0, tx : 0.618, rx : 0.000
 if_name : xe-6/0/2:3, Lane : 0, tx : 0.618, rx : 0.000
 if_name : xe-6/0/3:0, Lane : 0, tx : 1.049, rx : 0.544
 if_name : xe-6/0/3:1, Lane : 0, tx : 1.049, rx : 0.544
 if_name : xe-6/0/3:2, Lane : 0, tx : 1.049, rx : 0.544
 if_name : xe-6/0/3:3, Lane : 0, tx : 1.049, rx : 0.544
 if_name : et-6/0/35, Lane : 0, tx : 1.164, rx : 0.294
 if_name : xe-7/0/0:0, Lane : 0, tx : 0.534, rx : 0.564
 if_name : xe-7/0/0:1, Lane : 0, tx : 0.534, rx : 0.564
 if_name : xe-7/0/0:2, Lane : 0, tx : 0.534, rx : 0.564
 if_name : xe-7/0/0:3, Lane : 0, tx : 0.534, rx : 0.564
 if_name : xe-7/0/1:0, Lane : 0, tx : 0.000, rx : 0.000
 if_name : xe-7/0/1:1, Lane : 0, tx : 0.000, rx : 0.000
 if_name : xe-7/0/1:2, Lane : 0, tx : 0.000, rx : 0.000
 if_name : xe-7/0/1:3, Lane : 0, tx : 0.000, rx : 0.000
 if_name : xe-7/0/2:0, Lane : 0, tx : 1.141, rx : 0.000
 if_name : xe-7/0/2:1, Lane : 0, tx : 1.141, rx : 0.000
 if_name : xe-7/0/2:2, Lane : 0, tx : 1.141, rx : 0.000
 if_name : xe-7/0/2:3, Lane : 0, tx : 1.141, rx : 0.000
 if_name : xe-7/0/3:0, Lane : 0, tx : 1.068, rx : 0.655
 if_name : xe-7/0/3:1, Lane : 0, tx : 1.068, rx : 0.655
 if_name : xe-7/0/3:2, Lane : 0, tx : 1.068, rx : 0.655
 if_name : xe-7/0/3:3, Lane : 0, tx : 1.068, rx : 0.655
 if_name : et-7/0/18, Lane : 0, tx : 1.318, rx : 0.312
 if_name : et-7/0/19, Lane : 0, tx : 1.112, rx : 0.000

How do I make it print all 4 Lane info?

**Comment by dineshbaburam91** [comment]
Hi @anudeep26 , I would need xml output for the given command to help. Can you please share the xml for below command

`show interfaces diagnostics optics | display xml`

You can unicast us at jnpr-community-netdev@juniper.net

**Comment by anudeep26** [comment]
@dineshbaburam91 
[diag_info.txt](https://github.com/Juniper/py-junos-eznc/files/1986003/diag_info.txt)

**Comment by dineshbaburam91** [comment]
Kindly use below table/view config to get lane-index detail:
```
---
PhyPortDiagTable:
  rpc: get-interface-optics-diagnostics-information
  item: physical-interface/optics-diagnostics/optics-diagnostics-lane-values
  key: lane-index
  view: PhyPortDiagView

PhyPortDiagView:
  fields:
    tx_power : laser-output-power
    rx_power : laser-rx-optical-power
```

```python
globals().update(FactoryLoader().load(yaml.load(yaml_data)))
optics = PhyPortDiagTable(dev)
optics.get()

x = json.loads(optics.to_json())
for key,value in x.iteritems():
    print("Lane : {}, tx : {}, rx : {}".format(key, value["tx_power"],value["rx_power"]))
```

```
Output:

Lane : 0, tx : 0.414, rx : 0.450
Lane : 1, tx : 0.398, rx : 0.465
Lane : 2, tx : 0.421, rx : 0.408
Lane : 3, tx : 0.422, rx : 0.372
```

**Comment by vnitinv** [comment]
@anudeep26 Please use the Table provided above.
