### ISSUE TITLE
Software Utility class Juniper.junos.utils-sw : Reboot fails for WR Based Linux Hardware 

### ISSUE THREAD

**Issue by mamathac** [Juniper/py-junos-eznc#842]
This is a hardware with single RE, hence the module "reboot" fails as it runs a "show version invoke-on all-routing-engines" resulting in syntax error.

from jnpr.junos.console import Console
import logging
from jnpr.junos.utils.sw import SW

with Console(host='host', user='user', password='passwd', mode='telnet', port='', gather_facts=False) as dev:
    sft= SW(dev)
    print (sft.reboot())
>>>>>>>>>
Result:
>>>>>>>>>

********* Successfully logged in *********
INFO:jnpr.junos.tty_netconf:Calling rpc: b'<rpc><command>show version invoke-on all-routing-engines</command></rpc>'
DEBUG:jnpr.junos.tty_telnet:rawwrite: b'<rpc><command>show version invoke-on all-routing-engines</command></rpc>'
DEBUG:jnpr.junos.tty_netconf:Received:
b'<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/16.2I0/junos">\n<rpc-error>\n<error-type>protocol</error-type>\n<error-tag>operation-failed</error-tag>\n<error-severity>error</error-severity>\n<error-message>syntax error, expecting &lt;command&gt;</error-message>\n<error-info>\n<bad-element>invoke-on</bad-element>\n</error-info>\n</rpc-error>\n</rpc-reply>'
INFO:jnpr.junos.tty_netconf:Calling rpc: b'<rpc><get-virtual-chassis-information/></rpc>'
DEBUG:jnpr.junos.tty_telnet:rawwrite: b'<rpc><get-virtual-chassis-information/></rpc>'
DEBUG:jnpr.junos.tty_netconf:Received:
b'<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/16.2I0/junos">\n<rpc-error>\n<error-type>protocol</error-type>\n<error-tag>operation-failed</error-tag>\n<error-severity>error</error-severity>\n<error-message>syntax error</error-message>\n<error-info>\n<bad-element>get-virtual-chassis-information</bad-element>\n</error-info>\n</rpc-error>\n</rpc-reply>'
INFO:jnpr.junos.tty_netconf:Calling rpc: b'<rpc><get-software-information><format>xml</format><all-servers/></get-software-information></rpc>'
DEBUG:jnpr.junos.tty_telnet:rawwrite: b'<rpc><get-software-information><format>xml</format><all-servers/></get-software-information></rpc>'
DEBUG:jnpr.junos.tty_netconf:Received:
b'<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/16.2I0/junos">\n<rpc-error>\n<error-type>protocol</error-type>\n<error-tag>operation-failed</error-tag>\n<error-severity>error</error-severity>\n<error-message>syntax error, expecting &lt;invoke-on&gt;</error-message>\n<error-info>\n<bad-element>format</bad-element>\n</error-info>\n</rpc-error>\n<rpc-error>\n<error-type>protocol</error-type>\n<error-tag>operation-failed</error-tag>\n<error-severity>error</error-severity>\n<error-message>syntax error</error-message>\n<error-info>\n<bad-element>format</bad-element>\n</error-info>\n</rpc-error>\n</rpc-reply>'
INFO:jnpr.junos.tty_netconf:Calling rpc: b'<rpc><get-software-information/></rpc>'
DEBUG:jnpr.junos.tty_telnet:rawwrite: b'<rpc><get-software-information/></rpc>'
DEBUG:jnpr.junos.tty_netconf:Received:
b'<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/16.2I0/junos">\n<software-information>\n<product-model>qfx5200-32c-32q</product-model>\n<product-name>qfx5200-32c-32q</product-name>\n<junos-version>16.2I20180618103614_evo-builder</junos-version>\n<junos-package>junos-linux-install-qfx-x86-64-16.2I20180618103614_evo-builder.iso</junos-package>\n<yocto-version>2.2.1</yocto-version>\n<kernel-version>4.8.24-WR2.2.1_standard</kernel-version>\n</software-information>\n</rpc-reply>'
INFO:jnpr.junos.tty_netconf:Calling rpc: b'<rpc><get-interface-information><routing-instance>__juniper_private1__</routing-instance><terse/></get-interface-information></rpc>'
DEBUG:jnpr.junos.tty_telnet:rawwrite: b'<rpc><get-interface-information><routing-instance>__juniper_private1__</routing-instance><terse/></get-interface-information></rpc>'
DEBUG:jnpr.junos.tty_netconf:Received:
b'<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/16.2I0/junos">\n<interface-information junos:style="terse">\n</interface-information>\n</rpc-reply>'
INFO:jnpr.junos.tty_netconf:Calling rpc: b'<rpc><get-route-engine-information/></rpc>'
DEBUG:jnpr.junos.tty_telnet:rawwrite: b'<rpc><get-route-engine-information/></rpc>'
DEBUG:jnpr.junos.tty_netconf:Received:
b'<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/16.2I0/junos">\n<route-engine-information xmlns="http://xml.juniper.net/junos/16.2I20180618103614_evo-builder/junos-chassis">\n<route-engine>\n<slot>0</slot>\n<mastership-state>Master</mastership-state>\n<mastership-priority>Master (default)</mastership-priority>\n<status>OK</status>\n<temperature junos:celsius="41">41 degrees C / 105 degrees F</temperature>\n<cpu-temperature junos:celsius="41">41 degrees C / 105 degrees F</cpu-temperature>\n<memory-dram-size>15891 MB</memory-dram-size>\n<memory-buffer-utilization>3</memory-buffer-utilization>\n<cpu-user>2</cpu-user>\n<cpu-background>0</cpu-background>\n<cpu-system>1</cpu-system>\n<cpu-interrupt>0</cpu-interrupt>\n<cpu-idle>96</cpu-idle>\n<cpu-user1>1</cpu-user1>\n<cpu-background1>0</cpu-background1>\n<cpu-system1>1</cpu-system1>\n<cpu-interrupt1>0</cpu-interrupt1>\n<cpu-idle1>97</cpu-idle1>\n<cpu-user2>1</cpu-user2>\n<cpu-background2>0</cpu-background2>\n<cpu-system2>1</cpu-system2>\n<cpu-interrupt2>0</cpu-interrupt2>\n<cpu-idle2>97</cpu-idle2>\n<cpu-user3>1</cpu-user3>\n<cpu-background3>0</cpu-background3>\n<cpu-system3>1</cpu-system3>\n<cpu-interrupt3>0</cpu-interrupt3>\n<cpu-idle3>97</cpu-idle3>\n<model>RE-QFX5200-32C</model>\n<serial-number>BUILTIN</serial-number>\n<start-time junos:seconds="1529658663">2018-06-22 02:11:03 PDT</start-time>\n<up-time>4 days, 3 hours, 29 minutes, 30 seconds</up-time>\n<load-average-one>0.27</load-average-one>\n<load-average-five>0.17</load-average-five>\n<load-average-fifteen>0.16</load-average-fifteen>\n<last-reboot-reason>Unknown</last-reboot-reason>\n</route-engine>\n</route-engine-information>\n</rpc-reply>'
INFO:jnpr.junos.tty:logout: logging out.....
INFO:jnpr.junos.tty_netconf:Calling rpc: b'<rpc><close-session/></rpc>'
DEBUG:jnpr.junos.tty_telnet:rawwrite: b'<rpc><close-session/></rpc>'
DEBUG:jnpr.junos.tty_netconf:Received:
b'<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/16.2I0/junos">\n<ok/>\n</rpc-reply>'
DEBUG:jnpr.junos.tty_telnet:Got: b'\r\n\r\n'
DEBUG:jnpr.junos.tty_telnet:Got: b'root@nautilus-a-re0:~# '
DEBUG:jnpr.junos.tty_telnet:Write: exit
DEBUG:jnpr.junos.tty_telnet:Got: b'exit\r\nlogout\r\n\r\r\nJuniper Linux Distribution 2.2.1 nautilus-a-re0 ttyS0\r\n\r\nnautilus-a-re0 login: '
Traceback (most recent call last):
  File "/root/TC37.py", line 9, in <module>
    sft= SW(dev)
  File "/usr/local/lib/python3.4/dist-packages/jnpr/junos/utils/sw.py", line 92, in __init__
    'localre' in dev.facts['current_re'])
TypeError: argument of type 'NoneType' is not iterable

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

Hardware details:

Date:		Mon Jun 18 16:16:00 UTC 2018
Workspace:	/evobuilds1/daily/evo/pub-20180618.2/qfx-re64/obj-re-64b/build
Server:		svl-linux-infra-002
User:		evo-builder

Model: qfx5200-32c-32q
Junos: 16.2I20180618103614_evo-builder
Junos Package: junos-linux-install-qfx-x86-64-16.2I20180618103614_evo-builder.iso
Yocto: 2.2.1
Linux Kernel: 4.8.24-WR2.2.1_standard

Routing Engine status:
  Slot 0:
    Current state                  Master
    Election priority              Master (default)
    Temperature                 39 degrees C / 102 degrees F
    CPU temperature             39 degrees C / 102 degrees F
    DRAM                      15891 MB
    Memory utilization           3 percent
    5 sec CPU utilization:
      User                       1 percent
      Background                 0 percent
      Kernel                     1 percent
      Interrupt                  0 percent
      Idle                      97 percent
    1 min CPU utilization:
      User                       1 percent
      Background                 0 percent
      Kernel                     1 percent
      Interrupt                  0 percent
      Idle                      97 percent
    5 min CPU utilization:
      User                       1 percent
      Background                 0 percent
      Kernel                     1 percent
      Interrupt                  0 percent
      Idle                      97 percent
    15 min CPU utilization:
      User                       1 percent
      Background                 0 percent
      Kernel                     1 percent
      Interrupt                  0 percent
      Idle                      97 percent
    Model                          RE-QFX5200-32C
    Serial ID                      BUILTIN
    Start time                     2018-06-22 02:11:03 PDT
    Uptime                         4 days, 3 hours, 25 minutes, 19 seconds
    Load averages:                 1 minute   5 minute  15 minute
                                       0.07       0.10       0.15
    Last reboot reason             Unknown

**Comment by mamathac** [comment]
# python2.7 -c 'import jnpr.junos; print jnpr.junos.__version__'
2.1.9.dev0

**Comment by vnitinv** [comment]
Fixed via https://github.com/Juniper/py-junos-eznc/pull/862

to install code form github
pip install git+https://github.com/Juniper/py-junos-eznc.git
Please verify and close.

**Comment by ydnath** [comment]
Verified to be working, as per an offline discussion
