### ISSUE TITLE
Juniper Junos Utils : Config module.DB lock is not released in case of an exception(RPC error)

### ISSUE THREAD

**Issue by mamathac** [Juniper/py-junos-eznc#843]
In this case, suppose an RPC fails due to syntax error, the 'diff' still remains on the router.
Incase the RPC fails, rollback should happen and the device lock should be released.

`from jnpr.junos import Device
from jnpr.junos.factory.factory_loader import FactoryLoader

dev = Device(sys.argv[1],user=sys.argv[2],password=sys.argv[3],gather_facts=False, port=22)
dev.open()

yaml_data = \
    """---
  InterfaceTable:
    set: interfaces/interface
    key-field:
      - name
      - unit_name
    view: InterfaceView

  InterfaceView:
    groups:
      unit: unit
      bridge: unit/family/bridge
    fields:
      name: name
      enc : encapsulation
      native_vlan: native-vlan-id
    fields_unit:
      unit_name  : name
      desc       : description
    fields_bridge:
      mode: interface-mode
      vlan_list: vlan-id-list
   """

globals().update(FactoryLoader().load(yaml.load(yaml_data)))

intf = InterfaceTable(dev)

intf.name = "ge-0/0/1"
intf.unit_name = 0
intf.mode = "trunk"
intf.vlan_list = [510, 520, 530]
intf.native_vlan = 510
intf.desc = "l2-interface created"
intf.append()

intf.load()
print intf.pdiff()`

Since this RPC fails on WR based Linux, script returns:

> jnpr.junos.exception.ConfigLoadError: ConfigLoadError(severity: error, bad_element: bridge, message: error: syntax error
error: syntax error) 

On running a working config and do a set operation, db lock error comes.

Script using set():

from jnpr.junos import Device
from jnpr.junos.factory.factory_loader import FactoryLoader
from passlib.hash import md5_crypt
import yaml
import sys

# Connect to device.
dev = Device(sys.argv[1],user=sys.argv[2],password=sys.argv[3],gather_facts=False, port=22)
dev.open()

# Yml table for configuration.
yaml_data = \
    """---
    UserTable:
      set: system/login/user
      key-field: user
      view: userView

    userView:
      groups:
        auth: authentication
      fields:
        user: name
        uid: uid
        class_name: class
        uidgroup: uid
        fullgroup: full-name
      fields_auth:
        password: encrypted-password
      """
globals().update(FactoryLoader().load(yaml.load(yaml_data)))

# Create object of UserTable
gt = UserTable(dev)

# Set field values
gt.user = 'TestUser1'
gt.uid = 1234
gt.class_name = 'super-user'
p1 = 'abc123'
hashpwd = md5_crypt.encrypt(p1)
gt.password = hashpwd
gt.append()

# load configuration to running db
gt.set()

# Read data from device (using existing get() method)
gt.get()

for item in gt:
    print ('name:', item.user)
    print ('uid:', item.uid)
    print ('class:', item.class_name)
    print ('encrypted-password:', item.password)

# Connect to device with new user.
dev = Device(sys.argv[1],user=sys.argv[2],password=sys.argv[3],gather_facts=False, port=22)
dev.open()

# Yml table for interface configuration with new user.
yaml_data = \
    """
InterfaceTable:
  set: interfaces/interface
  key-field:
    - name
    - unit_name
  view: InterfaceView

InterfaceView:
  fields:
    name: { 'name' : { 'default' : 0 } }
    unit_name: { 'unit/name' : {'default' : 0}}
    ip_address: unit/family/inet/address
    desc: description

   """
globals().update(FactoryLoader().load(yaml.load(yaml_data)))

intf = InterfaceTable(dev)
intf.name = "et-0/0/1"
intf.desc = "Some Random"
#intf.unit_name = 0
intf.ip_address = "100.1.1.1/24"

# append record
intf.append()

#intf.lock()
intf.load()

if intf.commit_check():
   intf.commit()
else:
   intf.rollback()

#intf.unlock()

int = intf.get()
for item in int:
    print 'name: ', item.name
    print 'description: ', item.desc

dev.close()

>  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/config.py", line 563, in lock
    raise LockError(rsp=err.rsp)
jnpr.junos.exception.LockError: LockError(severity: error, bad_element: None, message: configuration database modified)

**Comment by vnitinv** [comment]
@mamathac we are not able to replicate this.

**Comment by mamathac** [comment]
Issue happens post running a failure case. Suppose there is a syntax error and then the script exits with Syntax error, subsequent test will fail due to DB lock.

error: configuration database locked by:
  regress terminal  (pid 7527) on since 2018-08-27 01:35:08 PDT, idle 00:25:52
      exclusive

With netconf Enabled:

Run a python file with config YAML having syntax error:
Traceback (most recent call last):
  File "testcase14.py", line 49, in <module>
    intf.load()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/factory/cfgtable.py", line 705, in load
    **kvargs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/config.py", line 539, in load
    ignore_warning=ignore_warning)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/config.py", line 460, in try_load
    raise ConfigLoadError(cmd=err.cmd, rsp=err.rsp, errs=err.errs)
jnpr.junos.exception.ConfigLoadError: ConfigLoadError(severity: error, bad_element: name, message: error: syntax error
error: syntax error)

>> COMMIT STUCK in Exclusive DB mode.

user@HOSTNAME# exit
The configuration has been changed but not committed
eExiting configuration mode

user@HOSTNAME> exit

In conf mode:
Entering configuration mode
Users currently editing the configuration:
  regress (pid 11779) on since 2018-08-27 02:04:22 PDT, idle 00:01:37
      exclusive
The configuration has been changed but not committed

Aug 27 02:04:22 [NETCONF] - [11779] Incoming: <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:db4ae806-39f2-437f-93b6-036a60d8a002"><load-configuration action="replace" format="xml"><configuration><interfaces><interface><name><name>ge-0/0/1</name><native-vlan-id>510</native-vlan-id><unit><name>0</name><family><bridge><interface-mode>trunk</interface-mode><vlan-id-list>510</vlan-id-list><vlan-id-list>520</vlan-id-list><vlan-id-list>530</
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/18.4I0/junos" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:db4ae806-39f2-437f-93b6-036a60d8a002">
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: <load-configuration-results>
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: <rpc-error>
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: <error-type>protocol</error-type>
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: <error-tag>operation-failed</error-tag>
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: <error-severity>error</error-severity>
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: <error-message>syntax error</error-message>
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: <error-info>
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: <bad-element>name</bad-element>
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: </error-info>
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: </rpc-error>
Aug 27 02:04:22 [NETCONF] - [11779] Debug: The last token parsed by mgd [11779] was [name] and gram data current token [name]
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: <rpc-error>
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: <error-type>protocol</error-type>
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: <error-tag>operation-failed</error-tag>
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: <error-severity>error</error-severity>
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: <error-message>syntax error</error-message>
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: <error-info>
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: <bad-element>name</bad-element>
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: </error-info>
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: </rpc-error>
Aug 27 02:04:22 [NETCONF] - [11779] Debug: The last token parsed by mgd [11779] was [name] and gram data current token [name]
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: <load-error-count>2</load-error-count>
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: </load-configuration-results>
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: </rpc-reply>
Aug 27 02:04:22 [NETCONF] - [11779] Outgoing: ]]>]]>

**Comment by rsmekala** [comment]
@mamathac If the user decides to lock the configuration before committing, then the user should gracefully handle the case of ConfigLoadError. 

An example case would be:
```
intf.lock()
try:
    intf.load()
except (ConfigLoadError, Exception) as err:
    intf.unlock()
```

@vnitinv Any comments or can we close the issue ??

**Comment by vnitinv** [comment]
@mamathac @rsmekala use context manager. for example:

```python
with Config(dev, mode='exclusive') as cnf:
    cnf.load(...)
    cnf.commit()
```

Closing this issue. Please re-open is still facing the issue.
