### ISSUE TITLE
PYEZ ISSU on Dviata

### ISSUE THREAD

**Issue by ramyaraju12** [Juniper/py-junos-eznc#844]
When we run ISSU using PyEZ, the pre validation checks if the version on both RE’s  is same.
 
In case of Dviata, when PyEZ gathers details of  versions on the box , it takes  version details of both master and backup RE of GNF and BSYS and selects  the BSYS version as main RE0 and RE1 version.
 
So if the GNF RE0 and RE1 have the same version also , PyEZ ISSU fails which is an issue.
 
FACTS
=====
 
{'2RE': True,
'HOME': '/var/home/regress',
'RE0': {'last_reboot_reason': 'Router rebooted after a normal shutdown.',
         'mastership_state': 'master',
         'model': 'RE-GNF-2594x2',
         'status': 'OK',
         'up_time': '4 hours, 5 minutes, 21 seconds'},
'RE1': {'last_reboot_reason': 'Router rebooted after a normal shutdown.',
         'mastership_state': 'backup',
         'model': 'RE-GNF-2594x2',
         'status': 'OK',
         'up_time': '23 hours, 8 minutes, 19 seconds'},
'RE_hw_mi': True,
'current_re': ['gnf7-master', 'gnf7-re0'],
'domain': 'englab.juniper.net',
'fqdn': 'mgb-gnf-a.englab.juniper.net',
'hostname': 'mgb-gnf-a',
'hostname_info': {'bsys-re0': 'mgb-dvaita-mx960-a',
                   'bsys-re1': 'mgb-dvaita-mx960-a1',
                   'gnf7-re0': 'mgb-gnf-a',
                   'gnf7-re1': 'mgb-gnf-a1'},
'ifd_style': 'CLASSIC',
'junos_info': {'bsys-re0': {'object': junos.version_info(major=(18, 3), type=I, minor=20180615_dev_common, build=1),
                             'text': '18.3-20180615_dev_common.1'},
                'bsys-re1': {'object': junos.version_info(major=(18, 3), type=I, minor=20180614_dev_common, build=0),
                             'text': '18.3-20180614_dev_common.0'},
                'gnf7-re0': {'object': junos.version_info(major=(18, 3), type=I, minor=20180622_dev_common, build=0),
                             'text': '18.3-20180622_dev_common.0'},
                'gnf7-re1': {'object': junos.version_info(major=(18, 3), type=I, minor=20180622_dev_common, build=0),
                             'text': '18.3-20180622_dev_common.0'}},
'master': 'RE0',
'model': 'MX960',
'model_info': {'bsys-re0': 'MX960',
                'bsys-re1': 'MX960',
                'gnf7-re0': 'MX960',
                'gnf7-re1': 'MX960'},
'personality': 'MX-GNF',
're_info': {'default': {'0': {'last_reboot_reason': 'Router rebooted after a '
                                                     'normal shutdown.',
                               'mastership_state': 'master',
                               'model': 'RE-GNF-2594x2',
                               'status': 'OK'},
                         '1': {'last_reboot_reason': 'Router rebooted after a '
                                                     'normal shutdown.',
                               'mastership_state': 'backup',
                               'model': 'RE-GNF-2594x2',
                               'status': 'OK'},
                         'default': {'last_reboot_reason': 'Router rebooted '
                                                           'after a normal '
                                                           'shutdown.',
                                     'mastership_state': 'master',
                                     'model': 'RE-GNF-2594x2',
                                     'status': 'OK'}}},
're_master': {'default': '0'},
'serialnumber': 'JN1259491AFA',
'srx_cluster': None,
'srx_cluster_id': None,
'srx_cluster_redundancy_group': None,
'switch_style': 'BRIDGE_DOMAIN',
'vc_capable': False,
'vc_fabric': None,
'vc_master': None,
'vc_mode': None,
'version': '18.3-20180622_dev_common.0',
'version_RE0': '18.3-20180615_dev_common.1',
'version_RE1': '18.3-20180614_dev_common.0',
'version_info': junos.version_info(major=(18, 3), type=I, minor=20180622_dev_common, build=0),
'virtual': True}

**Comment by vnitinv** [comment]
Fixed via #862 

to install code form github
pip install git+https://github.com/Juniper/py-junos-eznc.git
Please verify and close.

**Comment by vnitinv** [comment]
@ramyaraju12 Closing this issue. Please re-open is still facing the issue.
