### ISSUE TITLE
Login state machine can incorrectly match cli prompt over console connection

### ISSUE THREAD

**Issue by jnpr-bowen** [Juniper/py-junos-eznc#847]
The login state machine pattern for cli prompt will match an xml tag like "<simple-tag/>" as being the cli prompt. This can effect a program that, using a console connection, has executed an RPC that will result in a reboot and disconnects from the device. It then periodically checks to see if the reboot has finished, but the RPC response streaming back over the console can result in the cli prompt being matched 'prematurely'.

**Comment by rahkumar651991** [comment]
As per the comment on https://github.com/Juniper/py-junos-eznc/pull/848 . 
closing this.
