### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required

### ISSUE THREAD

**Issue by Erdix** [Juniper/py-junos-eznc#851]
Hi All,
When 
H:\>pip -V
pip 10.0.1 from c:\users\vicv9if\appdata\local\programs\python\python37\lib\site-packages\pip (python 3.7)

H:\>pip install junos-eznc  ------------>It is downloading and collecting a number of packets. But end of the the line, there are errors as following:

error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "c:\users\vicv9if\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\vicv9if\\AppData\\Local\\Temp\\pip-install-y2ogfpvu\\lxml\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\vicv9if\AppData\Local\Temp\pip-record-j8hc1ts3\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\vicv9if\AppData\Local\Temp\pip-install-y2ogfpvu\lxml\

Can you please help on how to figure out these issues on Python 3.7 on Win10?

H:\>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

Thanks
Erdim

**Comment by stacywsmith** [comment]
You might check [this post](https://stackoverflow.com/questions/51118394/pip-install-lxml-fails-on-python-3-7-on-windows)

**Comment by vnitinv** [comment]
@Erdix Was the post shared by @stacywsmith helpful to you?

**Comment by vnitinv** [comment]
@Erdix I am closing this issue. re-open if above comment was not helpful
