### ISSUE TITLE
Route policy?

### ISSUE THREAD

**Issue by peng0208** [Juniper/py-junos-eznc#857]
How to show configuration about route policy?

**Comment by yevgeniy-voloshin** [comment]
Did you already check this article:
https://www.juniper.net/documentation/en_US/junos-pyez/topics/task/program/junos-pyez-program-configuration-retrieving.html

**Comment by peng0208** [comment]
need i read all configuration information and check the  policy ?

**Comment by yevgeniy-voloshin** [comment]
Yep, I think this is one of many options to get a piece of configuration about routing policy
You mean "show configuration policy-options " isn't it?

Or this one:
    juiper-router> show policy | display xml rpc 
     <rpc-reply xmlns:junos="http://xml.juniper.net/junos/16.1R6/junos">
         <message>
             xml rpc equivalent of this command is not available.
         </message>
         <cli>
             <banner></banner>
         </cli>
     </rpc-reply>

**Comment by peng0208** [comment]
good, this command maybe what i need , thanks for your reply
