### ISSUE TITLE
Add $ shell prompt for Bourne-style shell to StartShell()

### ISSUE THREAD

**Issue by mmellin** [Juniper/py-junos-eznc#863]
Hi,

This may be a corner case, but I have an MX with the following configuration for the user:

    set system login user <user> shell sh

This drops an SSH'd user directly into the Bourne-style shell.  There are some scripting purposes behind this.  Using the `StartShell().open()` class method within PyEz does not take this shell's prompt `$` into account and the function `self.wait_for()` must timeout (defaults to 30secs I believe).

I believe adding `$` in a few places such as in the following place within `open()` (and other areas) would help speed things up:

jnpr.junos.utils.start_shell
```
 got = self.wait_for(r'(%|>|#)')      <<<< Add $ HERE
        if got[-1].endswith(_JUNOS_PROMPT):
            self.send('start shell')
            self.wait_for(_SHELL_PROMPT)
```

Thanks

**Comment by mmellin** [comment]
Looks like the `/bin/sh` shell behaves a bit differently than the others.  While adding `$` to the the `start_shell.py` prompt variables is a start, the output of some commands (like those issued via `cprod -A <linecard> -c "<command>"` are truncated and cause invalid output.  I'm trying to understand why this is.

**Comment by mmellin** [comment]
It seems like there are two unrelated issues I was seeing.

1. $ prompt is not supported.  This is an easy fix by adding `|\$` in two spots where the code looks for static prompt values.

2. Truncated output - this is related to another issue I will open a bug for.  I have a potential fix as well. #868 #

**Comment by rahkumar651991** [comment]
closing this as https://github.com/Juniper/py-junos-eznc/pull/868 is merged.
