### ISSUE TITLE
Many filedescriptors never closed

### ISSUE THREAD

**Issue by Anthony25** [Juniper/py-junos-eznc#872]
Hi,
I use this module through napalm, to target a several hundreds of devices. After 200 devices, I had an issue of too many file descriptors opened.

Even with the `device` object closed (both the napalm `device` and this module's one), for > 200 devices, I can see that it consumes around 70K non closed file descriptors. The only way to reduce this number is to force the garbage collection of the `device` objects.
I don't have this issue with other napalm drivers (nxos and ios for example).

I will send you some `lsof` output and try to dig on my side ASAP.
Thanks

**Comment by vnitinv** [comment]
@Anthony25 waiting to hear from you.

**Comment by Anthony25** [comment]
Hi @vnitinv,
Sorry for the delay. I've looked at which FD are kept opened after doing `device.close()`, and it seems that the issue is in the `ncclient` module, not this one. The SSH session object seems to open some pipes that are never closed.

I don't know if you prefer to close this issue or keep it opened to track the bug, so do as you prefer ;)

**Comment by Anthony25** [comment]
FYI, I fixed the issue here: https://github.com/ncclient/ncclient/pull/287

**Comment by Anthony25** [comment]
Merged in [ncclient](https://github.com/ncclient/ncclient/commit/d647a9ee3f600d027d7396ac181b4d7df41191fd)
