### ISSUE TITLE
Pyez open() with Unauthorized user terminates with error.

### ISSUE THREAD

**Issue by mamathac** [Juniper/py-junos-eznc#878]
While connecting to a device using Device.open() for an user who has permission to login and unauthorised to run show commands (Restricted User sessions), PyEZ returns below error.

Netconf is successful with unauthorised meaningful warning:

root@host:/home/regress# ssh user@<hostname> -s netconf
Password:
warning: user "un1" does not have access privileges. >>>> WARNING MESSAGE 

error: Restricted user session.

<rpc-reply>
<rpc-error>
<error-severity>warning</error-severity>
<error-message>
user "un1" does not have access privileges.
</error-message>
</rpc-error>
</rpc-reply>
<rpc-reply>
<rpc-error>
<error-type>protocol</error-type>
<error-tag>operation-failed</error-tag>
<error-severity>error</error-severity>
<error-message>
Restricted user session.
</error-message>
</rpc-error>
</rpc-reply>

<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file</capability>
    <capability>urn:ietf:params:xml:ns:netconf:base:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:confirmed-commit:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:url:1.0?protocol=http,ftp,file</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring</capability>
    <capability>http://xml.juniper.net/netconf/junos/1.0</capability>
    <capability>http://xml.juniper.net/dmi/system/1.0</capability>
  </capabilities>
  <session-id>24686</session-id>
</hello>
]]>]]>

>>>>
PYEZ is showing this error:
('Unable to connect to Unauthorized:', ConnectError(host: <hostname>, msg: Extra content at the end of the document, line 6, column 13)) >>>>ERROR

**Comment by stacywsmith** [comment]
What do you expect to happen? This is a Junos bug. It's outputting non-XML/NETCONF over a NETCONF session.

**Comment by mamathac** [comment]
The output of this has been same on Working and Non working JUNOS image.
For e.g.:
[mamathac@ttbg-shell02 regressd_pkgs]$ ssh pyez-un@router_name -s netconf
Password:
**warning: user "pyez-un" does not have access privileges.**

**error: Restricted user session.**

<rpc-reply>
<rpc-error>
<error-severity>warning</error-severity>
<error-message>
**user "pyez-un" does not have access privileges.**
</error-message>
</rpc-error>
</rpc-reply>
<rpc-reply>
<rpc-error>
<error-type>protocol</error-type>
<error-tag>operation-failed</error-tag>
<error-severity>error</error-severity>
<error-message>
**Restricted user session.**

On a working PyEZ version from pass logs we have got the same error printed while doing **print facts**

On a working junos-eznc (Old) version :
(Unable to connect to Unauthorized: ConnectError(host: <router_name>, msg: warning: user "pyez-ua" does not have access privileges. error: Restricted user session.)

Current Version shows error with some line number:
('Unable to connect to Unauthorized:', ConnectError(host: , msg: Extra content at the end of the document, line 6, column 13)) >>>>ERROR

**Comment by mamathac** [comment]
This is same as https://github.com/Juniper/py-junos-eznc/issues/874 .. Hence closing this one
