### ISSUE TITLE
jnpr.junos.utils.fs :   fs.storage_usage returns null for WR Linux Based device.

### ISSUE THREAD

**Issue by mamathac** [Juniper/py-junos-eznc#880]
Needs check for fs.storage_usage for WR Linux Based Os.
Running <get-system-storage> RPC over netconf on box returns values on router.

But when run using fs.storage_usage, returns null.
Works fine on a JUNOS Device.

Result on Junos Device:

> Return storage usage: {'tmpfs': {'used_pct': '0', 'used_blocks': 1496, 'total_blocks': 1382800, 'avail': '674M', 'mount': '/.mount/mfs', 'used': '748K', 'total': '675M', 'avail_block': 1381304}, '/dev/gpt/junos': {'used_pct': '23', 'used_blocks': 8933268, 'total_blocks': 41803892, 'avail': '14G', 'mount': '/.mount', 'used': '4.3G', 'total': '20G', 'avail_block': 29526314}}

On a WR Linux Based device:

> Return storage usage: {}

**Comment by mamathac** [comment]
Also check fs.storage_cleanup_check and fs.storage_cleanup.
Returns RPC error , while the command is supported and working on WR Linux Based device

> request system storage cleanup dry-run
> -------------------------------
> node: re0
> -------------------------------
> ........
> === Other candidate logs, traces, core files which would be removed  ===
> List of core files to be cleared
> List of log files from FPCs
> List of log files from logical-systems
> Clears/Rotates all App logs/traces under: /var/log/*
> Clears all App traces under: /var/log/traces/*
> Clears all App SI traces under: /var/log/si_traces/*
> === Removes any ISO files in /data partition ===
> === Current list of software versions installed ===
> === Software versions except current and rollback would be removed ===
> Active boot device is primary: /dev/sda
> List of installed version(s) :
> 

[1] -> XXXXXXImage  - [2018-09-05 10:12:30]

    '-' running version
    '>' next boot version
    '<' rollback boot version

PyEZ returns:

>     print ("\nReturns a list of files to remove at cleanup:", fs.storage_cleanup_check())
>   File "/usr/local/lib/python3.4/dist-packages/jnpr/junos/utils/fs.py", line 343, in storage_cleanup_check
>     rsp = self._dev.rpc.request_system_storage_cleanup(dry_run=True)
>   File "/usr/local/lib/python3.4/dist-packages/jnpr/junos/rpcmeta.py", line 345, in _exec_rpc
>     return self._junos.execute(rpc, **dec_args)
>   File "/usr/local/lib/python3.4/dist-packages/jnpr/junos/decorators.py", line 76, in wrapper
>     return function(*args, **kwargs)
>   File "/usr/local/lib/python3.4/dist-packages/jnpr/junos/decorators.py", line 31, in wrapper
>     return function(*args, **kwargs)
>   File "/usr/local/lib/python3.4/dist-packages/jnpr/junos/device.py", line 794, in execute
>     errs=ex)
> jnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: dry-run, message: syntax error)

**Comment by stacywsmith** [comment]
What's the `| display xml` output for both commands?

**Comment by vnitinv** [comment]
@mamathac Can you please verify if #883 resolved the issue or not.

**Comment by mamathac** [comment]
fs.storage_cleanup_check Still fails: RPC responsible - <request-system-storage-cleanup><dry-run/>

    print ("\nReturns a list of files to remove at cleanup:", fs.storage_cleanup_check())
  File "/Users/mamathac/WORK/UI-AUTOMATION/ansible-junos-stdlib/playbooks/ANS/lib/python2.7/site-packages/jnpr/junos/utils/fs.py", line 343, in storage_cleanup_check
    rsp = self._dev.rpc.request_system_storage_cleanup(dry_run=True)
  File "/Users/mamathac/WORK/UI-AUTOMATION/ansible-junos-stdlib/playbooks/ANS/lib/python2.7/site-packages/jnpr/junos/rpcmeta.py", line 345, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/Users/mamathac/WORK/UI-AUTOMATION/ansible-junos-stdlib/playbooks/ANS/lib/python2.7/site-packages/jnpr/junos/decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "/Users/mamathac/WORK/UI-AUTOMATION/ansible-junos-stdlib/playbooks/ANS/lib/python2.7/site-packages/jnpr/junos/decorators.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "/Users/mamathac/WORK/UI-AUTOMATION/ansible-junos-stdlib/playbooks/ANS/lib/python2.7/site-packages/jnpr/junos/device.py", line 794, in execute
    errs=ex)
jnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: dry-run, message: syntax error)

<nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:ffb913e4-da44-4f36-8b3e-4330b640152b"><request-system-storage-cleanup><dry-run/></request-system-storage-cleanup></nc:rpc>]]>]]>

**Comment by vnitinv** [comment]
@mamathac Can you please verify this again?

**Comment by ntwrkguru** [comment]
@vnitinv This is also not working on EX2200C. I'll file another issue for the same.

**Comment by rsmekala** [comment]
Closing this issue. Please reopen if required ✌️
