### ISSUE TITLE
Error on upgrading NFX 250's JDM via PYez 2.2.0

### ISSUE THREAD

**Issue by mohit311** [Juniper/py-junos-eznc#887]
Hi, on upgrading the NFX250 JDM to 15.1X53-D471.1 via sw.install method, getting the below error 

File "/usr/lib/python2.7/site-packages/jnpr/junos/utils/sw.py", line 92, in __init__ 
    'localre' in dev.facts['current_re']) 
TypeError: argument of type 'NoneType' is not iterable 

$ pip list | grep ez
junos-eznc                       2.2.0

Let me know if you need any other info.

Regards
Mohit

**Comment by vnitinv** [comment]
@mohit311  Will check on NFX device if this is broken. Can you please share the o/p of dev.facts?

**Comment by rahkumar651991** [comment]
Closing the issue due to inactivity.
