### ISSUE TITLE
"with Device()" is not idiomatic and is error prone

### ISSUE THREAD

**Issue by attila123** [Juniper/py-junos-eznc#890]
A common example for using the "with + as" language element in python is something like
```
with open('file.txt', 'wt') as f:
    f.write('hello')
```
If you would like to do it without "with + as" then it would look something like:
```
f = open('file.txt', 'wt')
f.write('hello')
f.close()
```
(I did not try these examples. Error handling e.g. try + finally is omitted for simplicity.)
The bottom line: in both cases you call open(). Nice, clean, logical, we got used to it.  

But what happens in pyez: without the "with + as" you need to use Device.open(), e.g.
```
dev = Device(host=host)
dev.open()
# do something with dev
dev.close()
```
So far so good. But without "with + as" you must not use Device.open()!
Example I found at https://www.juniper.net/documentation/en_US/junos-pyez/topics/task/program/junos-pyez-rpcs-executing.html
Note that this does not use open():
```
with Device(host='dc1a.example.com') as dev:   
   print (dev.display_xml_rpc('show route', format='text'))
```
I think this is very confusing and is not idiomatic / logical. So this one does not work correctly:
```
# Does not work correctly, open() will be called twice:
with Device(host='example.com').open() as dev:
    # do something with dev
    pass
```
What happens in this case? Device.open() will be first called explicitly, then `Device.__enter__()` will be called, which will call the Device.open() again (naughty hidden side effect in my opinion).
An ssh connection will be leaked and the open file handles will increase in the Juniper device! Then time is wasted to debug the problem... 
Device.open() does not check whether the connection was already open. I guess for backward compatibility reasons the only reasonable fix is now to insert a check to Device.open() and if the connection is already open, do not open it again.

Please also see `Manager.__enter__()` at https://github.com/ncclient/ncclient/blob/master/ncclient/manager.py#L194
It does not call connect(), so it's OK.

**Comment by vnitinv** [comment]
Hi @attila123 , you are taking an example of open where the name itself does the job, hence even in context manager or using with it we have to use open itself

The most common (and important) use of context managers is to properly manage resources. In PyEZ's case, the resource to be managed is an "Open connection to the device", not the Device() object returned by the constructor.

When a class contains __init__, __enter__ and __exit__, with should serve __init__ and __enter__ first and then at the end should leave using __exit__, which we do.

We should not compare custom defined context manager directly to open. 

You can point me to any reference documents which conflicts this use case.

**Comment by rsmekala** [comment]
Closing the issue. Please do reopen if necessary.

**Comment by attila123** [comment]
@vnitinv OK, I accept your answer, I did not code too much in Python yet, so I did not use many context managers.
But in any case I think guarding against doing Device.open() twice could be a useful check (for the reasons given above). It should raise some error even. For clarity I am going to create a new ticket for that.
