### ISSUE TITLE
DeprecationWarning: 'U' mode is deprecated

### ISSUE THREAD

**Issue by nskalis** [Juniper/py-junos-eznc#891]
Hi,

In Python3 the following is deprecated. This is causing `pyez` to give warnings when running in any CI environment.

```
/usr/lib/python3.6/site-packages/jnpr/junos/utils/config.py:501: DeprecationWarning: 'U' mode is deprecated
  rpc_contents = open(kvargs['path'], 'rU').read()
```

**Comment by stacywsmith** [comment]
Suggest replacing current `/usr/lib/python3.6/site-packages/jnpr/junos/utils/config.py:501`:
```
    rpc_contents = open(kvargs['path'], 'rU').read()
```

with:
```
    try:
        # Explicitly request Python 3.x universal newline 
        rpc_contents = open(kvargs['path'], 'r', newline=None).read()
    except TypeError:
        # Fallback to Python 2.x universal newline 
        rpc_contents = open(kvargs['path'], 'rU').read()
```
See [this question and answer](https://softwareengineering.stackexchange.com/questions/298677/why-is-universal-newlines-mode-deprecated-in-python).
