### ISSUE TITLE
Unknown exception when sending an RPC

### ISSUE THREAD

**Issue by Jitter00** [Juniper/py-junos-eznc#893]
Hello, 

I've encountered an unknown exception when running  a script which sends an RPC to a Juniper device. 

Python 2.7.15rc1
junos-eznc (2.2.0)

The device is a qfx5100-48s-6q running Junos: 17.3R3-S1.5.

This is the script:

`from jnpr.junos import Device
from jnpr.junos.utils.config import Config

router = "192.168.1.1"
dev = Device(router, user="admin", gather_facts=False, normalize=True)
dev.open()
xmlparser = jxmlease.Parser()
var1=dev.rpc.cli("ping overlay tunnel-type vxlan vni 101 tunnel-src 172.16.1.1 tunnel-dst 172.16.1.2 count 1", format="xml")
var1_parse = jxmlease.parse(var1)

print(var1_parse)
`
This is the error:

-> var1=dev.rpc.cli("ping overlay tunnel-type vxlan vni 101 tunnel-src 172.16.1.1 tunnel-dst 172.16.1.2 count 1", format="xml")
(Pdb) n
/home/cristian/.local/lib/python2.7/site-packages/jnpr/junos/device.py:798: RuntimeWarning: An unknown exception occured - please report.
  RuntimeWarning)
XMLSyntaxError: XMLSynta...umn 10',)

The command returns valid output when I run it from the CLI on the Juniper device. 

Can someone please look into it?

Thanks!

**Comment by stacywsmith** [comment]
Please paste the output from executing `ping overlay tunnel-type vxlan vni 101 tunnel-src 172.16.1.1 tunnel-dst 172.16.1.2 count 1 | display xml` at the CLI. 

Based on the error message, it appears the Junos device is emitting invalid XML.

It is possible to execute the `ping` RPC rather than the `ping` CLI command, and that may avoid the problem in your case.

**Comment by Jitter00** [comment]
Hi Stacy, 

This is the CLI output:

`<rpc-reply xmlns:junos="http://xml.juniper.net/junos/17.3R3/junos">
    <run-command>
        <command>/usr/sbin/ping-overlay</command>
        <argument>-p</argument>
        <argument>vxlan</argument>
        <argument>-v</argument>
        <argument>101</argument>
        <argument>-s</argument>
        <argument>172.16.1.1</argument>
        <argument>-d</argument>
        <argument>172.16.1.2</argument>
        <argument>-o</argument>
        <argument>127.0.0.1</argument>
        <argument>-c</argument>
        <argument>1</argument>
        <argument>-t</argument>
        <argument>255</argument>
    </run-command>
    <cli>
        <banner>{master:0}</banner>
    </cli>
</rpc-reply>`

**Comment by Jitter00** [comment]
Hi Stacy, 

This is the ''display xml rpc" output:
```

<rpc-reply xmlns:junos="http://xml.juniper.net/junos/17.3R3/junos">
    <rpc>
        <request-ping-overlay>
                <tunnel-type>vxlan</tunnel-type>
                <vni>101</vni>
                <tunnel-src>172.16.1.1</tunnel-src>
                <tunnel-dst>172.16.1.2</tunnel-dst>
                <count>1</count>
        </request-ping-overlay>
    </rpc>
    <cli>
        <banner>{master:0}</banner>
    </cli>
</rpc-reply>
```

However, I'm get the same error when I try to use the RPC command, as below:

```
> /home/cristian/projects/reg_tests/code/test.py(14)<module>()
-> ping_test = lxml.etree.tostring(dev.rpc.request_ping_overlay(tunnel_type='vxlan', vni='100', tunnel_src='172.16.1.1', tunnel_dst='172.16.1.2', count='1'))
(Pdb) n
/home/cristian/.local/lib/python2.7/site-packages/jnpr/junos/device.py:798: RuntimeWarning: An unknown exception occured - please report.
  RuntimeWarning)
XMLSyntaxError: XMLSynta...umn 10',)
```

There are workarounds indeed (for instance starting a shell session), but I still believe this issue is still worth reporting/fixing.

**Comment by vnitinv** [comment]
@dineshbaburam91  Please file a PR

**Comment by rahkumar651991** [comment]
Based on last comments, looks to be a device issue. Closing the issue due to inactivity. Incase of similar or related issue, you may re-open it or raise a new issue.
