### ISSUE TITLE
Interface name not returned in ethport table/view

### ISSUE THREAD

**Issue by ymitsos** [Juniper/py-junos-eznc#895]
Hi,

Any particular reason why the interface name "name" is not returned in the fields view "EthPortView"?
https://github.com/Juniper/py-junos-eznc/blob/master/lib/jnpr/junos/op/ethport.yml

**Comment by vnitinv** [comment]
@ymitsos If you need name in fields, you need to define the name in View explicitly. As name is used as key in Table and name value comes in the object iteration as key.

**Comment by vnitinv** [comment]
Closing this issue. Please do reopen if you still face any issue.
