### ISSUE TITLE
rpc.get_config filter_xml - xpath expression not being evaluated correctly

### ISSUE THREAD

**Issue by Whiterat-8607** [Juniper/py-junos-eznc#899]
Hi,

When trying to use xpath functions/expressions such as contains/starts-with within filter_xml they fail to work.
The xpath statement is valid when evaluated independently.

Is this expected behaviour? 

```python
        data = dev.rpc.get_config(filter_xml="system/services/dynamic-dns/apply-macro[starts-with(name, 'cf-ddns-')]", options={'format': 'json'})
```

```xml
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/18.1R2/junos">
    <configuration junos:commit-seconds="1543507174" junos:commit-localtime="2018-11-29 15:59:34 GMT" junos:commit-user="root">
            <system>
                <services>
                    <dynamic-dns>
                        <apply-macro>
                            <name>cf-ddns-client1</name>
                            <data>
                                <name>aaa</name>
                                <value>bbb...</value>
                            </data>
                        </apply-macro>
                    </dynamic-dns>
                </services>
            </system>
    </configuration>
    <cli>
        <banner></banner>
    </cli>
</rpc-reply>
```

**Comment by vnitinv** [comment]
@Whiterat-8607 Junos support subtree (and not xpath) as filter. Please refer

https://www.juniper.net/documentation/en_US/junos/topics/reference/tag-summary/netconf-get-config.html
```the only acceptable value is subtree.```
For working examples, please check https://github.com/Juniper/py-junos-eznc/pull/672

You can use filter (subtree) to fetch all apply-macro and then locally apply xpath.

Let me know if that helps!!

**Comment by Whiterat-8607** [comment]
Hi @vnitinv,

The documentation is very misleading and points otherwise:

> https://www.juniper.net/documentation/en_US/junos-pyez/topics/task/program/junos-pyez-program-configuration-retrieving.html

The example from the above page clearly states "XPath expression":

'''python
from jnpr.junos import Device
from lxml import etree

with Device(host='router1.example.net') as dev:

    # Junos XML elements
    data = dev.rpc.get_config(filter_xml='<system><services/></system>')
    print(etree.tostring(data, encoding='unicode'))

    # XPath expression 
    data = dev.rpc.get_config(filter_xml='system/services')
    print(etree.tostring(data, encoding='unicode'))

    # lxml.etree._Element
    filter = etree.XML('<system><services/></system>')
    data = dev.rpc.get_config(filter_xml=filter)  
    print(etree.tostring(data, encoding='unicode'))
```

**Comment by vnitinv** [comment]
@Whiterat-8607 Thanks for pointing out this. We will get this fixed.

**Comment by Whiterat-8607** [comment]
Thank you @vnitinv
