### ISSUE TITLE
poor performance of rpc calls

### ISSUE THREAD

**Issue by yusong0926** [Juniper/py-junos-eznc#903]
I just found some of the rpc calls take more than 20 seconds to finish. I am thinking if that's the problem of netconf and xml.
when you run netconf over ssh in command line, in the response of a rpc call, each xml tag is output on it's own line there is very poor buffering happing and it's flushing and delivering the stream to the client every new line.
not sure if that's the problem for the poor performance  I got.

**Comment by vnitinv** [comment]
hi @yusong0926 . Can you please share the RPC in use. RPC reply file size (using cli-> <command> | save <file>).
If the file size is huge, did you try python 3.x as this will give you huge performance improvement (better sleep handling in python 3.x threading).

**Comment by rsmekala** [comment]
Closing this issue. Please reopen if required ✌️
