### ISSUE TITLE
Op Table with NameSpace problem on SRx1500 with HA

### ISSUE THREAD

**Issue by kokasha** [Juniper/py-junos-eznc#912]
I am trying to parse the security zones on a SRX1500 in an HA cluster and i am using the default SecurityZoneTable definition part of the op Tables shipped with Pyez.

**The script is shown below**

from jnpr.junos import Device
from jnpr.junos.op.securityzone import SecurityZoneTable
from pprint import pprint

#Create Device Instance
dev = Device(host='x.x.x.x',user='xxx',passwd='xxx')
dev.open()
zones = SecurityZoneTable(dev).get()

print(zones)

And the output is as shown below

SecurityZoneTable:10.74.33.65: 0 items

and it failed to parse any element

Below is the table definition from the Yaml File

SecurityZoneTable:
  rpc: get-zones-information
  item: zones-security
  key: zones-security-zonename
  view: SecurityZoneView

The XML Output from the SRX is as shown below

<rpc-reply xmlns:junos="http://xml.juniper.net/junos/15.1X49/junos">
    <multi-routing-engine-results>
        
        <multi-routing-engine-item>
            
            <re-name>node0</re-name>
            
            <zones-information xmlns="http://xml.juniper.net/junos/15.1X49/junos-zones" junos:style="detail">
                <zones-security>
                    <zones-security-zonename>prod</zones-security-zonename>
                    <zones-security-send-reset>Off</zones-security-send-reset>
                    <zones-security-policy-configurable>Yes</zones-security-policy-configurable>
                    <zones-security-interfaces-bound>1</zones-security-interfaces-bound>
                    <zones-security-interfaces>
                        <zones-security-interface-name>reth0.1004</zones-security-interface-name>
                    </zones-security-interfaces>
                </zones-security>
                <zones-security>
                    <zones-security-zonename>nonprod</zones-security-zonename>
                    <zones-security-send-reset>Off</zones-security-send-reset>
                    <zones-security-policy-configurable>Yes</zones-security-policy-configurable>
                    <zones-security-interfaces-bound>1</zones-security-interfaces-bound>
                    <zones-security-interfaces>
                        <zones-security-interface-name>reth0.1005</zones-security-interface-name>
                    </zones-security-interfaces>
                </zones-security>
                <zones-security>
                    <zones-security-zonename>vpn</zones-security-zonename>
                    <zones-security-send-reset>Off</zones-security-send-reset>
                    <zones-security-policy-configurable>Yes</zones-security-policy-configurable>
                    <zones-security-interfaces-bound>3</zones-security-interfaces-bound>
                    <zones-security-interfaces>
                        <zones-security-interface-name>st0.1</zones-security-interface-name>
                        <zones-security-interface-name>st0.10</zones-security-interface-name>
                        <zones-security-interface-name>st0.100</zones-security-interface-name>
                    </zones-security-interfaces>
                </zones-security>
                <zones-security>
                    <zones-security-zonename>junos-host</zones-security-zonename>
                    <zones-security-send-reset>Off</zones-security-send-reset>
                    <zones-security-policy-configurable>Yes</zones-security-policy-configurable>
                    <zones-security-interfaces-bound>0</zones-security-interfaces-bound>
                    <zones-security-interfaces></zones-security-interfaces>
                </zones-security>
            </zones-information>
        </multi-routing-engine-item>
        
    </multi-routing-engine-results>
    <cli>
        <banner>{primary:node0}</banner>
    </cli>
</rpc-reply>

I think that the problem is in the extra NameSpace in the "zones-information" element however i am unable to find a way to remove orhandle this namespace.

Is there any way to solve this problem.

**Comment by stacywsmith** [comment]
I don't think the namespace is the issue. PyEZ strips namespaces by default.

I think the issue is with the `<multi-routing-engine-results>` and `<multi-routing-engine-item>` tags which are not present on single RE platforms.
   
[This line](https://github.com/Juniper/py-junos-eznc/blob/master/lib/jnpr/junos/op/securityzone.yml#L4).
should be changed to:
```
  item: .//zones-security
```

Hopefully @vnitinv or @rsmekala can confirm my suspicion.

**Comment by kokasha** [comment]
@stacywsmith Thank you so much

I have tried it and it worked :)

However, how can we handle the cases where we have the cases of Single RE vs Dual RE.

Having two separate definition files is not a pretty solution, What do you think?

**Comment by stacywsmith** [comment]
My change should work with both single RE and dual RE. No need for separate files.

**Comment by varshap22** [comment]
once u enable netconf over ssh.maybe it works
