### ISSUE TITLE
Fix for PyEZ corrupting configurations upon extraction

### ISSUE THREAD

**Issue by sawu-juniper** [Juniper/py-junos-eznc#913]
One of the customer reported issue to update the Juniper PyEZ information - 

******************
Here is the missing information from the Juniper PyEZ documentation on gathering configurations from JUNOS.
 
etree's tostring method leaves the "<", "&", and ">" escaped as "&lt;", "&amp;", and "&gt;" respectively.  Unfortunately in configurations using apply-path statements such as "apply-path "interfaces lo0 unit 0 family inet address <*>";", these lines are corrupted.
 
The fix is to "unescape" the special characters using the below function:
 
From: https://wiki.python.org/moin/EscapingXml
Unescaping XML

The xml.sax.saxutils module provides an unescape() function as well. This function converts the &amp;, &gt;, and &lt; entity references back to the corresponding characters: 

 
Toggle line numbers
   1 >>> from xml.sax.saxutils import unescape
   2 >>>
   3 >>> unescape("&lt; &amp; &gt;")
   4 '< & >'
Note that the predefined entities &apos; and &quot; are not supported by default. Like the escape() and quoteattr() functions, unescape() can be provided with an additional mapping of replacements that should be performed. This can be used to add support for the additional predefined entities: 

 
Toggle line numbers
   1 >>> unescape("&apos; &quot;", {"&apos;": "'", "&quot;": '"'})
   2 '\' "'
 
Previous code to get a text format configuration (per documentation on Juniper's site):
    data = dev.rpc.get_config(options={'format':'text'})
    config = etree.tostring(data)
    configStr = str(config)
 
New code that fixes the output:
    data = dev.rpc.get_config(options={'format':'text'})
    config = etree.tostring(data)
    configStr = unescape(str(config))

**Comment by vnitinv** [comment]
This is expected behaviour and should be like this. Its upto the user to use `unescape` module is really requied.
