### ISSUE TITLE
Get information of the auto generate interface like pp0.3344324

### ISSUE THREAD

**Issue by saymonaraujo** [Juniper/py-junos-eznc#919]
Hello, 

Theres anything that i can use and receive the return of traffic like the PhyPortStatsTable() for the dynamic interface create with auto provision(using dynamic profiles) ?

**Comment by saymonaraujo** [comment]
Can anyone help me ?
I want to grab the interface status using netconf, otherwise I will use snmp.

**Comment by rsmekala** [comment]
@saymonaraujo Let me look into this.

**Comment by vnitinv** [comment]
yes @saymonaraujo you can do this. interface_name can be provided as argument.
For example
```python
tbl = PhyPortStatsTable()
tbl.get(interface_name='pp0.3344324')
```

check this doc for more details
https://www.juniper.net/documentation/en_US/junos-pyez/topics/task/program/junos-pyez-tables-op-defining.html#task-op-table-optional-arg

**Comment by saymonaraujo** [comment]
Hello,

@vnitinv . Sorry for bother you guys.
Thanks for the help.

**Comment by saymonaraujo** [comment]
Hello, 

I tried, using any physical interface works well. But using any pp0. interface doesn't work.
Follow my function:

def get_interface_attributes(junosip_or_hostname, interface):
    login_to_device = get_junos_attributes(junosip_or_hostname)
    dev = Device(host=login_to_device[0], user=login_to_device[1], passwd=login_to_device[2])
    dev.open()
    pst = PhyPortStatsTable(dev)
    pst.get(interface_name=interface)
    return pst.to_json()

Using this:

print(junosexec.get_interface_attributes(hostname_prp, 'ge-0/0/0'))

The return its:
{"ge-0/0/0": {"rx_bytes": 0, "rx_packets": 0, "tx_bytes": 0, "tx_packets": 0, "rx_err_input": 0, "rx_err_drops": 0}}


But, using a pp0.3221290511 as exemple:

print(junosexec.get_interface_attributes(hostname_prp, 'pp0.3221290511'))

The return is:
{}


And yes, the interface pp0.3221290511 exists:

show interfaces pp0.3221290511 
  Logical interface pp0.3221290511 (Index 536935966) (SNMP ifIndex 200065054)
    Flags: Up Point-To-Point Encapsulation: PPPoE
    PPPoE:
      State: SessionUp, Session ID: 23584,
      Session AC name: netion, Remote MAC address: 5c:1a:6f:fc:c9:f1,
      Underlying interface: demux0.3221225473 (Index 536870924)
      Ignore End-Of-List tag: Disable 
    Input packets : 32288576
    Output packets: 43361782
.
.
.

**Comment by rsmekala** [comment]
@saymonaraujo This is not an actual physical interface, it is a logical interface. So, it is not best suited for your use-case. You can use a custom TableView, below is a basic case for the same.

```
table_view = """
---
intfStats:
  rpc: get-interface-information
  args:
    interface_name: 'pp0'
  item: physical-interface/logical-interface
  view: intfStatsView

intfStatsView:
  groups:
    ts: traffic-statistics
  fields:
    interface_name: name
  fields_ts:
    rx_packets: { input-packets: int }
    tx_packets: { output-packets: int }
"""


def get_interface_attributes(junosip_or_hostname):
    login_to_device = get_junos_attributes(junosip_or_hostname)
    with Device(host=login_to_device[0], user=login_to_device[1], passwd=login_to_device[2]) as dev:
        pst = intfStats(dev)
        pst.get()
    return pst.to_json()


globals().update(FactoryLoader().load(yaml.load(table_view)))
print(get_interface_attributes('xx.xx.xx.xx'))
```

I have hardcoded the interface to `pp0`, please change it as per your need. 

Please let me know if you need any additional help.

**Comment by saymonaraujo** [comment]
Hello, 

Thanks @rsmekala. Sorry for bother you guys.

**Comment by rsmekala** [comment]
@saymonaraujo Does the above example accomplish your use-case ??

**Comment by saymonaraujo** [comment]
Hello, 

Yes, now a understand the concept. Will do some coding fot testing and return if needed. For now, thank you for the help and again sorry if a cause any problem.
