### ISSUE TITLE
Improvement: Device.open() should be protected from called twice

### ISSUE THREAD

**Issue by attila123** [Juniper/py-junos-eznc#921]
Hi, based on my experience with https://github.com/Juniper/py-junos-eznc/issues/890 I think Device.open() should have a built-in sanity check / guard so that Device.open() should raise some error if it is attempted to be called when the connection is already open.
Why: if there is a bug in the user's application and Device.open() is called twice then it is best to be revealed right when it happens.
What happens currently if Device.open() is called 2 times (without closing between):
The ssh connection to the Juniper device is leaked and the open file handles increase in the Juniper device! It may be time consuming to debug the problem! (it was for me, although I wrote unit + other tests for my code)

**Comment by rahkumar651991** [comment]
Based on different scenario, people might need to open device again(refer saltstack,junos-proxy). So we will not be supporting this as it might impact customer use-case.
