### ISSUE TITLE
Facts collection not correct for some new Juniper products

### ISSUE THREAD

**Issue by raghurampai** [Juniper/py-junos-eznc#926]
Regarding the facts collection, I see the product info (including the personality and platform info) is not correct for some platforms/products-
1) The “product” for SRX1500, SRX4100, SRX4200, SRX4600 platforms are returned as SRX_HIGHEND. But these are actually SRX Branch/mid-range.
Below is the correct classification of SRX-
SRX_BRANCH - SRX300, SRX550
SRX_MIDRANGE - SRX1500, SRX4100, SRX4200, SRX4600
SRX_HIGHEND -  SRX5400, SRX5600, SRX5800
(Reference - https://www.juniper.net/us/en/products-services/security/srx-series/ )

2) Facts details of some products as mentioned are not retrieved correctly in facts collection - ACX, BTI, VSRX.

Can please consider updating PyEZ as per new products of Juniper ... thanks

**Comment by rsmekala** [comment]
@raghurampai I have raised the pull request that solves the first issue.

Will try and verify the second issue on a vSRX.
