### ISSUE TITLE
IO Exception Over Serial On Windows

### ISSUE THREAD

**Issue by philippetrepanier** [Juniper/py-junos-eznc#943]
I cannot get PyEZ to connect to my juniper switch on Windows using the serial port. For my application I cannot use SSH/telnet and I need it to work over the serial port.

On login I get an error in `tty_netconf._receive()` with the usage of select. 

According to the official python docs the select operation is not supported on Windows for file objects (https://docs.python.org/3/library/select.html?highlight=select#select.select).

Is there something else than the select than can be used to wait on the IO under Windows ?

Thanks

Here is the command and the output with the error.

Using Windows 10 1809
Python 3.6.8
junos-eznc  2.2.1

### To Replicate
```
import sys
import logging
import time
from jnpr.junos import Device
from jnpr.junos.utils.config import Config

logging.basicConfig(level=logging.DEBUG)

dev = Device(mode='serial', port='COM4', user='root', passwd=None)
dev.open()
```

### Output
```
INFO:jnpr.junos.tty:TTY: connecting to TTY:COM4 ...
INFO:jnpr.junos.tty:TTY: OK.....starting NETCONF
WRITExml-mode netconf need-trailer
ERROR:jnpr.junos.console:Exception occurred: login:fileno

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\jnpr\junos\console.py", line 221, in open
    raise ex
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\jnpr\junos\console.py", line 211, in open
    self._tty_login()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\jnpr\junos\console.py", line 316, in _tty_login
    self._tty.login()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\jnpr\junos\transport\tty.py", line 115, in login
    self.nc.open(at_shell=self.at_shell)
  File "C:\Users\uesr\AppData\Local\Programs\Python\Python36\lib\site-packages\jnpr\junos\transport\tty_netconf.py", line 68, in open
    self.hello = self._receive()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\jnpr\junos\transport\tty_netconf.py", line 142, in _receive
    raise err
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\jnpr\junos\transport\tty_netconf.py", line 140, in _receive
    rd, wt, err = select.select([self._tty._rx], [], [], 0.1)
io.UnsupportedOperation: fileno
```

**Comment by rsmekala** [comment]
@philippetrepanier I have read the reference you mentioned about select not working on windows. 

### Issue as quoted in Python docs
```
File objects on Windows are not acceptable, but sockets are. On Windows, the underlying select() function is provided by the WinSock library and does not handle file descriptors that don’t originate from WinSock.
```

### Proposed solution
It is mentioned that you are currently running Windows 10, which supports running Linux containers. Refer https://tutorials.ubuntu.com/tutorial/tutorial-windows-ubuntu-hyperv-containers#0

You can run the PyEZ container( Linux based ), and provide container access to the serial port.
Command: `docker run -it --rm --name pyez --device <port_name> juniper/pyez sh`

For attaching serial ports to a container, refer https://stackoverflow.com/questions/24225647/docker-a-way-to-give-access-to-a-host-usb-or-serial-device

P.S: I didn't test the solution, just adding my 2 cents on the topic. Give me thumbs up if it works, will be glad to know.

### Some of the other solutions mentioned on the web using:
- Converting filehandles into streaming sockets, and using the select calls on the sockets instead of the file objects could work. A little harder to work on, in my personal opinion.

**Comment by moophat** [comment]
> 
> 
> @philippetrepanier I have read the reference you mentioned about select not working on windows.
> ### Issue as quoted in Python docs
> 
> ```
> File objects on Windows are not acceptable, but sockets are. On Windows, the underlying select() function is provided by the WinSock library and does not handle file descriptors that don’t originate from WinSock.
> ```
> 
> ### Proposed solution
> 
> It is mentioned that you are currently running Windows 10, which supports running Linux containers. Refer https://tutorials.ubuntu.com/tutorial/tutorial-windows-ubuntu-hyperv-containers#0
> 
> You can run the PyEZ container( Linux based ), and provide container access to the serial port.
> Command: `docker run -it --rm --name pyez --device <port_name> juniper/pyez sh`
> 
> For attaching serial ports to a container, refer https://stackoverflow.com/questions/24225647/docker-a-way-to-give-access-to-a-host-usb-or-serial-device
> 
> P.S: I didn't test the solution, just adding my 2 cents on the topic. Give me thumbs up if it works, will be glad to know.
> ### Some of the other solutions mentioned on the web:
> 
>     * Converting filehandles into streaming sockets, and using the select calls on the sockets instead of the file objects could work. A little harder to work on, in my personal opinion.

Hi  Rsmekala, is there any updated plan for this. Script that use serial console connection -in our experience - is more useful for cases that the running machine would be on-site with minimal setup. Using a Linux container and attach the serial port to it might would but is not really applicable in production.

**Comment by shivintwrk** [comment]
@philippetrepanier : I am having the same issue. Could you find any workaround/solution for it?

**Comment by philippetrepanier** [comment]
@shivintwrk Haven't had time to work on this project lately but the best solution would be to convert the filehandles into streaming sockets as proposed earlier.
In my use case running in WSL is not an option as moophat pointed out.

**Comment by shivintwrk** [comment]
@philippetrepanier Running in WSL gives the same errors :(

**Comment by vnitinv** [comment]
@shivintwrk I can provide a fix, but I dont have system to test. If you can help me with this, we can work together and get the fix in mainline sooner.

**Comment by vnitinv** [comment]
@philippetrepanier @shivintwrk would you be interested in testing the change as I don't have windows setup

**Comment by shivintwrk** [comment]
@vnitinv I have a JunOS device connected via console and Windows env. I will try to test it.

**Comment by shivintwrk** [comment]
@vnitinv Here's what I did:
I installed the repo again using pip. Used read() instead of open() and just tried to print the facts (wasn't sure if it would let me make config changes such as setting up a password) .
It gave me the same error.
Can you please give an eg. of using read()?

**Comment by vnitinv** [comment]
@shivintwrk install using below command

`pip install git+https://github.com/vnitinv/py-junos-eznc.git@win-serial-com`

you dont have to other about read() changes, thats in PyEZ, you just run your script and share error if any.

just make sure you have these 2 lines in your script for proper debug log
```python
import logging
logging.basicConfig(level=logging.DEBUG)

**Comment by shivintwrk** [comment]
@vnitinv Did the install again using _'pip install git+https://github.com/vnitinv/py-junos-eznc.git@win-serial-com'_ 
I tried in two ways and got two different exceptions:

Case 1: Without open()
```
logging.basicConfig(level=logging.DEBUG)
dev = Device(host='testdevice', user='root', passwd='********', mode='serial', port='COM4', gather_facts = True)
cu = Config(dev)
cu.load('set system host-name test', format='set', ignore_warning=True)
cu.commit()
```

Exception:
```
Traceback (most recent call last):
  File "c:/Users/##########", line 23, in <module>
    cu.load('set system host-name test', format='set', ignore_warning=True)
  File "C:\Python37\lib\site-packages\jnpr\junos\utils\config.py", line 539, in load
    ignore_warning=ignore_warning)
  File "C:\Python37\lib\site-packages\jnpr\junos\utils\config.py", line 456, in try_load
    **rpc_xattrs)
  File "C:\Python37\lib\site-packages\jnpr\junos\rpcmeta.py", line 277, in load_config
    return self._junos.execute(rpc, ignore_warning=ignore_warning)
  File "C:\Python37\lib\site-packages\jnpr\junos\decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "C:\Python37\lib\site-packages\jnpr\junos\decorators.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "C:\Python37\lib\site-packages\jnpr\junos\device.py", line 782, in execute
    raise EzErrors.ConnectClosedError(self)
jnpr.junos.exception.ConnectClosedError: ConnectClosedError(testdevice)
```

Case 2 : With open()

```
logging.basicConfig(level=logging.DEBUG)
dev = Device(host='testdevice', user='root', passwd='********', mode='serial', port='COM4', gather_facts = True)
conn = dev.open()
cu = Config(conn)
cu.load('set system host-name test', format='set', ignore_warning=True)
cu.pdiff()
print ("commit result: "), cu.commit(ignore_warning=True)
dev.close()
```
Exception:
```
INFO:jnpr.junos.tty:TTY: connecting to TTY:COM4 ...
INFO:jnpr.junos.tty:TTY: logging in......
INFO:jnpr.junos.tty:TTY: OK.....starting NETCONF
ERROR:jnpr.junos.console:Exception occurred: login:fileno

Traceback (most recent call last):
  File "c:/Users/#############", line 15, in <module>
    conn = dev.open()
  File "C:\Python37\lib\site-packages\jnpr\junos\console.py", line 222, in open
    raise ex
  File "C:\Python37\lib\site-packages\jnpr\junos\console.py", line 212, in open
    self._tty_login()
  File "C:\Python37\lib\site-packages\jnpr\junos\console.py", line 319, in _tty_login
    self._tty.login()
  File "C:\Python37\lib\site-packages\jnpr\junos\transport\tty.py", line 116, in login
    self.nc.open(at_shell=self.at_shell)
  File "C:\Python37\lib\site-packages\jnpr\junos\transport\tty_netconf.py", line 68, in open
    self.hello = self._receive()
  File "C:\Python37\lib\site-packages\jnpr\junos\transport\tty_netconf.py", line 142, in _receive
    raise err
  File "C:\Python37\lib\site-packages\jnpr\junos\transport\tty_netconf.py", line 140, in _receive
    rd, wt, err = select.select([self._tty._rx], [], [], 0.1)
io.UnsupportedOperation: fileno
```

**Comment by vnitinv** [comment]
Its not picking up latest code. The log shows error from old library itself. We can sync to debug this. Let me know if you are OK. We can get on ZOOM or something similar. You can unicast me at nitinkr at juniper dot net

**Comment by moophat** [comment]
Hi guys,
Just a reminder: we have a lot of hardware dedicated for lab testing and this is something that would be very useful for a lot of our upcoming project(s). 

So I would be happy to help in troubleshooting/providing debug log or even providing direct VPN access to a testing environment for anyone who can fix this. The goal is for the fix to be merged as soon as possible. 

Give me a heads up if you are interested.

**Comment by moophat** [comment]
> 
> 
> @shivintwrk Its not picking up latest code. The log shows error from old library itself. We can sync to debug this. Let me know if you are OK. We can get on ZOOM or something similar. You can unicast me at nitinkr at juniper dot net
> 
> you should also you with context manager which takes care of open and close (this helps in proper cleaning at exit/close) We can discuss more on call

Hi guys,
Just a reminder: we have a lot of hardware dedicated for lab testing and this is something that would be very useful for a lot of our upcoming project(s).

So I would be happy to help in troubleshooting/providing debug log or even providing direct VPN access to a testing environment for anyone who can fix this. The goal is for the fix to be merged as soon as possible.

Give me a heads up if you are interested.

**Comment by vnitinv** [comment]
@moophat Would you help us in testing this patch?

**Comment by moophat** [comment]
Hi @vnitinv , sure I will do that. Let me know how you want to do it: 
1. I clone the code from your and upload the debug log(s) to your repo
2. Provide you remote access to one of our Windows machine consoled to ACX/MX ?

**Comment by vnitinv** [comment]
@moophat How about going from 1 to 2. If 1 doesn't work, I can work with remote access.

**Comment by moophat** [comment]
> 
> 
> @moophat How about going from 1 to 2. If 1 doesn't work, I can work with remote access.

Ok, I will update you with the logs as soon as I have time to access our lab.

**Comment by shivintwrk** [comment]
@vnitinv : I have tried with the context manager but it gives me the the same "io.UnsupportedOperation: fileno" exception. 
I used --upgrade this time to install the package hoping that it would resolve the issue of not picking up latest code. It did uninstall and reinstall the package.

```
Successfully built junos-eznc
Installing collected packages: junos-eznc
  Attempting uninstall: junos-eznc
    Found existing installation: junos-eznc 2.3.2.dev0
    Uninstalling junos-eznc-2.3.2.dev0:
      Successfully uninstalled junos-eznc-2.3.2.dev0
Successfully installed junos-eznc-2.3.2.dev0
```

I tried with context manager this time and got a different exception:

```
INFO:jnpr.junos.tty:TTY: connecting to TTY:COM4 ...
INFO:jnpr.junos.tty:TTY: logging in......
WARNING:jnpr.junos.tty:login_warn: waiting on TTY.....
INFO:jnpr.junos.tty:TTY: OK.....starting NETCONF
DEBUG:jnpr.junos.tty_netconf:Received:
b''
INFO:jnpr.junos.console:facts: retrieving device facts...
INFO:jnpr.junos.tty_netconf:Calling rpc: b'<rpc><load-configuration format="text" action="set"><configuration-set>set system host-name test</configuration-set></load-configuration></rpc>'
DEBUG:jnpr.junos.tty_netconf:Received:
b''
C:\Python37\lib\site-packages\jnpr\junos\device.py:825: RuntimeWarning: An unknown exception occured - please report.
  RuntimeWarning)
INFO:jnpr.junos.tty:logout: logging out.....
INFO:jnpr.junos.tty_netconf:Calling rpc: b'<rpc><close-session/></rpc>'
DEBUG:jnpr.junos.tty_netconf:Received:
b''
Traceback (most recent call last):
  File "c:/Users/###", line 208, in <module>
    main()
  File "c:/Users/###", line 181, in main
    cu.load('set system host-name test', format='set', ignore_warning=True)
  File "C:\Python37\lib\site-packages\jnpr\junos\utils\config.py", line 539, in load
    ignore_warning=ignore_warning)
  File "C:\Python37\lib\site-packages\jnpr\junos\utils\config.py", line 456, in try_load
    **rpc_xattrs)
  File "C:\Python37\lib\site-packages\jnpr\junos\rpcmeta.py", line 277, in load_config
    return self._junos.execute(rpc, ignore_warning=ignore_warning)
  File "C:\Python37\lib\site-packages\jnpr\junos\decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "C:\Python37\lib\site-packages\jnpr\junos\decorators.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "C:\Python37\lib\site-packages\jnpr\junos\device.py", line 801, in execute
    'filter_xml'))
  File "C:\Python37\lib\site-packages\jnpr\junos\decorators.py", line 116, in wrapper
    rsp = function(self, *args, **kwargs)
  File "C:\Python37\lib\site-packages\jnpr\junos\console.py", line 280, in _rpc_reply
    self._huge_tree
  File "C:\Python37\lib\site-packages\ncclient\xml_.py", line 174, in __init__
    self.__doc = self.remove_namespaces(self.__result)
  File "C:\Python37\lib\site-packages\ncclient\xml_.py", line 222, in remove_namespaces
    parser=self.__parser))),
  File "src\lxml\etree.pyx", line 3435, in lxml.etree.parse
  File "src\lxml\parser.pxi", line 1857, in lxml.etree._parseDocument
  File "src\lxml\parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
  File "src\lxml\parser.pxi", line 1758, in lxml.etree._parseDoc
  File "src\lxml\parser.pxi", line 1068, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src\lxml\parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Specification mandates value for attribute error-in-receive, line 1, column 27
```

**Comment by moophat** [comment]
> 
> 
> @moophat How about going from 1 to 2. If 1 doesn't work, I can work with remote access.

Hi @vnitinv , apolozies for the late reply, there was an power issue with our lab so I have to turn off some device during the weekends.

But good new is that the updated code seem to work, even when the console session was currently in a logged in prompt, which is great. 
I'll need to test further functionality with the tableview retrieval and setting new configuration before confirming that everything work as expected. But for now thank you for the update
