### ISSUE TITLE
continious errors while pyez installation

### ISSUE THREAD

**Issue by samascience** [Juniper/py-junos-eznc#946]
slc-scratch scp3]# sudo pip install pip --upgrade
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already up-to-date: pip in /usr/lib/python2.7/site-packages (19.1.1)
[root@slc-scratch scp3]# sudo /usr/local/bin/pip install junos-eznc
sudo: /usr/local/bin/pip: command not found
[root@slc-scratch scp3]# pip install -U junos-eznc
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting junos-eznc
  Using cached https://files.pythonhosted.org/packages/da/6c/6a9c839f2d7bef53381c84a7e49620b44a87633306832bc5e3bf7b68fe00/junos_eznc-2.2.1-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: lxml>=3.2.4 in /usr/lib64/python2.7/site-packages (from junos-eznc) (4.3.4)
Requirement already satisfied, skipping upgrade: netaddr in /usr/lib/python2.7/site-packages (from junos-eznc) (0.7.19)
Collecting PyYAML>=5.1 (from junos-eznc)
  Using cached https://files.pythonhosted.org/packages/a3/65/837fefac7475963d1eccf4aa684c23b95aa6c1d033a2c5965ccb11e22623/PyYAML-5.1.1.tar.gz
Collecting pyserial (from junos-eznc)
  Using cached https://files.pythonhosted.org/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl
Collecting scp>=0.7.0 (from junos-eznc)
  Using cached https://files.pythonhosted.org/packages/4d/7a/3d76dc5ad8deea79642f50a572e1c057cb27e8b427f83781a2c05ce4e5b6/scp-0.13.2-py2.py3-none-any.whl
Collecting jinja2>=2.7.1 (from junos-eznc)
  Using cached https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: six in /usr/lib/python2.7/site-packages (from junos-eznc) (1.9.0)
Collecting paramiko>=1.15.2 (from junos-eznc)
  Using cached https://files.pythonhosted.org/packages/4b/80/74dace9e48b0ef923633dfb5e48798f58a168e4734bca8ecfaf839ba051a/paramiko-2.6.0-py2.py3-none-any.whl
Collecting ncclient>=0.5.4 (from junos-eznc)
  Using cached https://files.pythonhosted.org/packages/36/b1/1f909193588dfd35726e8ae35e01463386bbcf670b90ed61c4930ce447db/ncclient-0.6.6.tar.gz
Collecting MarkupSafe>=0.23 (from jinja2>=2.7.1->junos-eznc)
  Using cached https://files.pythonhosted.org/packages/fb/40/f3adb7cf24a8012813c5edb20329eb22d5d8e2a0ecf73d21d6b85865da11/MarkupSafe-1.1.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting cryptography>=2.5 (from paramiko>=1.15.2->junos-eznc)
  Using cached https://files.pythonhosted.org/packages/e6/68/50698ce24c61db7d44d93a5043c621a0ca7839d4ef9dff913e6ab465fc92/cryptography-2.7-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pynacl>=1.0.1 (from paramiko>=1.15.2->junos-eznc)
  Using cached https://files.pythonhosted.org/packages/b3/25/e605574f24948a8a53b497744e93f061eb1dbe7c44b6465fc1c172d591aa/PyNaCl-1.3.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting bcrypt>=3.1.3 (from paramiko>=1.15.2->junos-eznc)
  Using cached https://files.pythonhosted.org/packages/ad/36/9a0227d048e98409f012570f7bef8a8c2373b9c9c5dfbf82963cbae05ede/bcrypt-3.1.7-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied, skipping upgrade: setuptools>0.6 in /usr/lib/python2.7/site-packages (from ncclient>=0.5.4->junos-eznc) (41.0.1)
Collecting selectors2>=2.0.1 (from ncclient>=0.5.4->junos-eznc)
  Using cached https://files.pythonhosted.org/packages/c9/89/8a07d6d6c78422c5151f68453e9741af4cd82bebcfa73923f73b3bdbef0d/selectors2-2.0.1-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: enum34; python_version < "3" in /usr/lib/python2.7/site-packages (from cryptography>=2.5->paramiko>=1.15.2->junos-eznc) (1.0.4)
Collecting asn1crypto>=0.21.0 (from cryptography>=2.5->paramiko>=1.15.2->junos-eznc)
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography>=2.5->paramiko>=1.15.2->junos-eznc)
  Using cached https://files.pythonhosted.org/packages/8d/e9/0c8afd1579e5cf7bc0f06fbcd7cdb954cbc0baadd505973949a99337da1c/cffi-1.12.3-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied, skipping upgrade: ipaddress; python_version < "3" in /usr/lib/python2.7/site-packages (from cryptography>=2.5->paramiko>=1.15.2->junos-eznc) (1.0.16)
Requirement already satisfied, skipping upgrade: pycparser in /usr/lib/python2.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.5->paramiko>=1.15.2->junos-eznc) (2.14)
Installing collected packages: PyYAML, pyserial, asn1crypto, cffi, cryptography, pynacl, bcrypt, paramiko, scp, MarkupSafe, jinja2, selectors2, ncclient, junos-eznc
  Found existing installation: PyYAML 3.10
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
[root@slc-scratch scp3]# sudo python upgrade_junQFX5100_1.py
Traceback (most recent call last):
  File "upgrade_junQFX5100_1.py", line 1, in <module>
    from jnpr.junos import Device
ImportError: No module named jnpr.junos
[root@slc-scratch scp3]#

**Comment by ntwrkguru** [comment]
Need more info. What OS, what version of Python, what version of PIP. I would expect it not to work as it’s obvious that PyEZ didn’t install properly.

**Comment by holaleeyan** [comment]
Hi,

I have the same problem during installing on my Ubuntu. Pls find my logs. Thanks.

[pyez install.txt.txt](https://github.com/Juniper/py-junos-eznc/files/3777828/pyez.install.txt.txt)

Cheers,
Thomas

**Comment by ntwrkguru** [comment]
Typo?

`ImportError: No module named 'jupr'`

**Comment by holaleeyan** [comment]
Oops...yes u're correct. I tried "--ignore-installed PyYAML" and thought that it still failed due to the typo mistake. But actually it works. Thanks a lot.
 
sudo -H pip install junos-eznc --ignore-installed PyYAML
