### ISSUE TITLE
ER - add a check for pending Junos OS or package install

### ISSUE THREAD

**Issue by jnpr453nz** [Juniper/py-junos-eznc#961]
Would it be possible to add check for pending or unfinished installs prior to copying a Junos image and kicking off the install?
Currently, there is no such check available.  Being able to make an upload and/or install dependant on such a successful check could save a lot of time.
Thank you

**Comment by vnitinv** [comment]
Code changes done via https://github.com/vnitinv/py-junos-eznc/commit/00b36ec5f9d8631230fd478ff6e7481fb7783cdc. pending UT.
