### ISSUE TITLE
Exception: Error in get_rpc_equivalent

### ISSUE THREAD

**Issue by meghajb** [Juniper/py-junos-eznc#964]
I tried the following to get display_xml return value. It is returning the output as follows.
```
from jnpr.junos import Device
from xml.etree import ElementTree as ET
dev = Device('x.x.x.x', user='XXX', password='XXX', port=22)
cmd = dev.display_xml_rpc('show services application-identification version')
print (cmd)
```

###  Output (In case the RPC doesn't exist for a valid command)
```
invalid command: show services application-identification version| display xml rpc
```

Kindly return the proper exception message

**Comment by rsmekala** [comment]
@meghajb I agree the message can be worded better in case we are not able to find the RPC. 

It is doable, let me gather some more info internally and raise the pull request.

Kudos for pointing it out.

**Comment by rahkumar651991** [comment]
Closing issue, as code changes merged.
