### ISSUE TITLE
commit_check() timing out 

### ISSUE THREAD

**Issue by lumi-pwhitney** [Juniper/py-junos-eznc#970]
It would be convenient if commit_check() could also accept a timeout argument as commit() does.

**Comment by chidanandpujar** [comment]
Hi @lumi-pwhitney 

This request is fixed in Release 2.4.0 , so closing the issue .

Release 2.4.0 - 1 APRIL 2020
Features Added


    Added timeout support for commit_check() #998

Thanks & Regards
Chidanand
