### ISSUE TITLE
Yaml Fullloader in jnpr/junos/factory/__init_

### ISSUE THREAD

**Issue by mc** [Juniper/py-junos-eznc#987]
Hi,

https://github.com/Juniper/py-junos-eznc/blob/e9e6dc1f2decfb163ac68803245a9de19c5d726c/lib/jnpr/junos/factory/__init__.py#L33 uses **Loader=...FullLoader** as arg.

This seems to be python 3 only; it would be helpful to either check for py2/py3 and omit the fulloader version for py3 OR throw a more meaningful error if the intention is to support py3 only.

-u

**Comment by vnitinv** [comment]
@mc We should fix this. How about a pull request.

**Comment by vnitinv** [comment]
@mc Which Python 2.x you are using? try upgrading YAML. That should fix the issue.

```python
Python 2.7.16 (default, Jan 26 2020, 23:50:38)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> yaml.load
<function load at 0x108b45c08>
>>> help(yaml.load)
load(stream, Loader=None)
    Parse the first YAML document in a stream
    and produce the corresponding Python object.
```
```
