### ISSUE TITLE
get-route-information excessively slow

### ISSUE THREAD

**Issue by nzjc** [Juniper/py-junos-eznc#988]
Hi 

I am using PyEZ 2.3.1 with Python 3.6.1 and MX204's with Junos 18.4R2-S3. 

I am trying to "pull down" a full route table from a VRF, something in the order of 1.7M routes (900k active). Using 'show route table X.inet.0 | display xml' on the box takes about 3 minutes to finish. The PyEZ equivalent I am running (from routes.yml, RouteTable):

```ipv4_rib = RouteTable(dev).get(table='X.inet.0', dev_timeout=2400)```

This will fail to complete in 40 mins (I will get a timeout). If I run the same code against a table that has ~10,000 routes, it completes very quickly, as it does on a router. 

Any ideas on how I could optimise? Thanks

**Comment by moophat** [comment]
This is not the problem with netconf or the rpc, as we have collected text with that much length without problem before. You can test the actual pulling time by try executing the rpc get-route-information into text format & print to stdout. I believe the time will be significantly different. 

But what you are doing is getting those 1.7M route into a optable, which involve parsing the xml into Tableview object.  A single static route is a already a Node with at least 7-10 element inside it. If most of your 1.7M route is BGP the performance surely will suffer.

Saving the xml into a file then parse it using tableview later would be a better choice.

**Comment by nzjc** [comment]
@moophat thanks for that insight, I will try it that way!

Cheers

**Comment by rahkumar651991** [comment]
Closing the issue, as the optimisation suggested should work.
