### ISSUE TITLE
Config push using JSON format - severity: error, bad_element: operation

### ISSUE THREAD

**Issue by ameer131** [Juniper/py-junos-eznc#989]
Hi All,

I have a problem when I am doing a config push using JSON format. It works well when I am using XML.

Taking into example that I have an existing interface configuration for ge-1/1/6 as below:
```
unit 0 {
    description "Interface Testing";
    family inet {
        address 99.99.99.11/24;
    }
}
```

I am using the default replace operation and I have below YANG-model based format config to be pushed out:
XML:
```
<configuration>
  <interfaces>
    <interface>
      <name>ge-1/1/6</name>
      <unit>
        <name>0</name>
        <description>new configuration testing</description>
        <family>
          <inet>
           <address>
              <name>88.88.88.88/24</name>
            </address>
          </inet>
        </family>
      </unit>
    </interface>
  </interfaces>
</configuration>
```
JSON:
```
{
  "configuration": {
    "interfaces": {
      "interface": [
        {
          "name": "ge-1/1/6",
          "unit": [
            {
              "name": 0,
              "description": "new configuration testing",
              "family": {
                "inet": {
                  "address": [
                    {
                      "name": "88.88.88.88/24"
                    }
                  ]
                }
              }
            }
          ]
        }
      ]
    }
  }
}
```
Both works well but knowing JunOS, it allows an interface to have multiple family inet address, thus the config was appended instead of replaced. The `show | compare` output is as below:

```
# show | compare 
[edit interfaces ge-1/1/6 unit 0]
-    description "Interface Testing";
+    description "new configuration testing";
[edit interfaces ge-1/1/6 unit 0 family inet]
        address 99.99.99.11/24 { ... }
+       address 88.88.88.88/24;

[edit]
```
I figure out that in XML, we could add a specific replace operator which the YANG-model based format config looks like below:

XML:
```
<configuration>
  <interfaces>
    <interface>
      <name>ge-1/1/6</name>
      <unit>
        <name>0</name>
        <description>testing..1..2..33...</description>
        <family>
          <inet operation="replace">
            <address>
              <name>88.88.88.88/24</name>
            </address>
          </inet>
        </family>
      </unit>
    </interface>
  </interfaces>
</configuration>
```

JSON:
```
{
  "configuration": {
    "interfaces": {
      "interface": [
        {
          "name": "ge-1/1/6",
          "unit": [
            {
              "name": 0,
              "description": "testing..1..2..33...",
              "family": {
                "inet": {
                  "address": [
                    {
                      "name": "88.88.88.88/24"
                    }
                  ],
                  "@operation": "replace"
                }
              }
            }
          ]
        }
      ]
    }
  }
}
```

Result:
- Config push with XML format works fine
- Config push with JSON format throws an error as below (bad_element: operation):

```
>>> with Config(dev) as cu: cu.load(config_json, format="json")
... 
Traceback (most recent call last):
  File "/users/myusers/virt/lib/python3.6/site-packages/jnpr/junos/device.py", line 777, in execute
    ignore_warning=ignore_warning)
  File "/users/myusers/virt/lib/python3.6/site-packages/jnpr/junos/decorators.py", line 169, in wrapper
    raise ex
  File "/users/myusers/virt/lib/python3.6/site-packages/jnpr/junos/decorators.py", line 116, in wrapper
    rsp = function(self, *args, **kwargs)
  File "/users/myusers/virt/lib/python3.6/site-packages/jnpr/junos/device.py", line 1339, in _rpc_reply
    return self._conn.rpc(rpc_cmd_e)._NCElement__doc
  File "/users/myusers/virt/lib/python3.6/site-packages/ncclient/manager.py", line 236, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/users/myusers/virt/lib/python3.6/site-packages/ncclient/operations/third_party/juniper/rpc.py", line 49, in request
    return self._request(rpc)
  File "/users/myusers/virt/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 347, in _request
    raise RPCError(to_ele(self._reply._raw), errs=errors)
ncclient.operations.rpc.RPCError: error: syntax error, expecting '}' or "@"
error: invalid value
error: parse error
error: syntax error, expecting ']' or :

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/myusers/virt/lib/python3.6/site-packages/jnpr/junos/utils/config.py", line 456, in try_load
    **rpc_xattrs)
 File "/users/myusers/virt/lib/python3.6/site-packages/jnpr/junos/rpcmeta.py", line 277, in load_config
    return self._junos.execute(rpc, ignore_warning=ignore_warning)
  File "/users/myusers/virt/lib/python3.6/site-packages/jnpr/junos/decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "/users/myusers/virt/lib/python3.6/site-packages/jnpr/junos/decorators.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "/users/myusers/virt/lib/python3.6/site-packages/jnpr/junos/device.py", line 797, in execute
    errs=ex)
jnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: operation, message: error: syntax error, expecting '}' or "@"
error: invalid value
error: parse error
error: syntax error, expecting ']' or :)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/myusers/virt/lib/python3.6/site-packages/jnpr/junos/utils/config.py", line 539, in load
    ignore_warning=ignore_warning)
  File "/users/myusers/virt/lib/python3.6/site-packages/jnpr/junos/utils/config.py", line 460, in try_load
    raise ConfigLoadError(cmd=err.cmd, rsp=err.rsp, errs=err.errs)
jnpr.junos.exception.ConfigLoadError: ConfigLoadError(severity: error, bad_element: operation, message: error: syntax error, expecting '}' or "@"
error: invalid value
error: parse error
error: syntax error, expecting ']' or :)

```
I tried changing @operation to _operation, the results are the same.

Few questions that I have in mind:
1) What is the equivalent JSON code for <inet operation="replace"> ?
2) If XML is the best way to go, what is the preferred way to convert YAML -> XML
3) Should we first delete the interface configuration and push the configuration? If yes, how can we delete the interface configuration via PyEZ?
4) If the above way is wrong, what the best way to get the config push using JSON format?

**Comment by vnitinv** [comment]
What is the equivalent JSON code for ?
[nitinkr] Will check and get back to you

If XML is the best way to go, what is the preferred way to convert YAML -> XML
[nitinkr] YAML-XML?

Should we first delete the interface configuration and push the configuration? If yes, how can we delete the interface configuration via PyEZ?
[nitinkr] No

If the above way is wrong, what the best way to get the config push using JSON format?
[nitinkr] Let me check with the team.

**Comment by rampolisetty** [comment]
As an alternate can you try this and confirm if this works for you?

 {
     "configuration": {
         "interfaces": {
             "interface": [
             {
                 "name": "ge-1/1/6",
                 "unit": [
                 {
                     "name": 0,
                     "description": "testing..1..2..33...",
                     "family": {
                         "inet": {
                             "@" : {
                                 "operation" : "delete"
                             }
                         }
                     },
                     "family": {
                         "inet": {
                             "@" : {
                                 "operation" : "create"
                             },
                             "address": [
                             {
                                 "name": "88.88.88.89/24"
                             }
                             ]
                         }
                     }
                 }
                 ]
             }
             ]
         }
     }
 }

**Comment by ameer131** [comment]
@vnitinv , Thanks for checking this up. 
The reason why I wanted to convert YAML -> XML. I would like to have my users or engineer to define the configuration that they would like to push to the device in YAML format which to me is more user-friendly and easy-to-read. I will then create a script that will help to convert the YAML to XML before pushing it to the device.

Should we first delete the interface configuration and push the configuration? If yes, how can we delete the interface configuration via PyEZ?
[nitinkr] No
[ameer131] Can you help to quickly check the response from @rampolisetty as the solutions actually works! I just wondering why "replace" is not an element.

@rampolisetty , thank you so much for saving me tons of research time. The provided solution works great. I managed to get the desired output. It will be great if a replace option can be used in this case. If it isn't, I'll just use this method first.

**Comment by rampolisetty** [comment]
@ameer131 Thanks for confirming the provided solution is working. Yes, please use this option till 'replace' option is supported.
