### ISSUE TITLE
yml file with required_keys is not working with get

### ISSUE THREAD

**Issue by gowrisankarvs** [Juniper/py-junos-eznc#992]
Provided example in "https://www.juniper.net/documentation/en_US/junos-pyez/topics/task/program/junos-pyez-tables-config-defining.html" is not working. I am getting following error messge.
```
sankarvs-mbp:yml sankarvs$ python3 cli.py 
Traceback (most recent call last):
  File "cli.py", line 26, in <module>
    stats = stats.get()
  File "/usr/local/lib/python3.7/site-packages/jnpr/junos/factory/cfgtable.py", line 475, in get
    self.required_keys)
ValueError: ('This table has required-keys\n', OrderedDict([('user', 'name')]))
```
not working yml file
```
yml
---
UserTable:
  get: system/login/user
  required_keys:
    user: name
  view: UserView
UserView:
  fields:
    username: name
    userclass: class
    uid: uid
```

working yml file:-
```
UserTable:
  get: system/login/user
  key: name
  view: UserView
UserView:
  fields:
    username: name
    userclass: class
    uid: uid
```

**Comment by bswilden** [comment]
The `required_keys` parameter requires that you supply a value for that key when you retrieve the data in the Junos PyEZ application. For example:

`stats = stats.get(user='readonly')`

If you do not provide a value, you will get the error you noted:
`ValueError: ('This table has required-keys\n', OrderedDict([('user', 'name')]))`

**Comment by rahkumar651991** [comment]
As the comment explains it, closing the issue.
