### ISSUE TITLE
jnpr.junos.utils.sw needs to support "unlink" option in 18.1R2+ 

### ISSUE THREAD

**Issue by zerowaitstate** [Juniper/py-junos-eznc#994]
Per this article, https://kb.juniper.net/InfoCenter/index?page=content&id=KB31198&actp=METADATA EX2300/EX3400 switches may not be able to perform ordinary upgrades from 18.x to another 18.x/19.x release, due to storage limitations (I have confirmed this on an EX3400-48p out of box that shipped with 18.1R3.3).  An option was added in 18.1R2 to request-package-add called "unlink" which removes the package tarball immediately after unpack to make more space available for the upgrade ("force" may also possibly be necessary).  We need the ability to manipulate these flags in order for higher level tools like Ansible (who rely on PyEZ) to reliably perform JUNOS upgrades on these platforms.

**Comment by rahkumar651991** [comment]
@zerowaitstate  - Based on the discussion on [484](https://github.com/Juniper/ansible-junos-stdlib/issues/484) , kwargs can be used in juniper_junos_software or PyEZ to pass "unlink : true " parameter. 

Closing this issue.
